//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_019
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...As well as the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_116
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11160_c011">
I can't believe you were the princess all along. I wish I could go back in time and tell my younger self!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_118
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
But when they found out you were the princess, they practically hailed you as a hero. It was pretty satisfying!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_136
{
<NS>Gallica<NE>
<BUSTUP 6 0 0>
<LIPSYNC>
Are you serious? Wow, talk about confidence... I guess that's the princess in you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_112
{
<NS>Gallica<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_11156_c011">
We're going to win. And you'll be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_115
{
<NS>Gallica<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_11060_c011">
You'll be a great queen. Let's keep up the fight.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_125
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
You really know how to persevere. You clearly have what it takes to be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_col_0001_001_KING_LANDSCAPE_01_137
{
<NS>Gallica<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_11163_c011">
Maybe that's what draws people to you. I hope it keeps up, and you become a queen loved by the whole kingdom.
<WAIT>
}