//--------------------------
#SPEAKER_ID "11"
@MES_dng_start_12_001
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Gallica_talk_34_c011">
This is the end. The mission we were assigned, the duty the princess was born into... Let's see them both to success.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_dng_global_return_last_012_D7
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_Dpv_PC_Gallica_reply_01_c011">
All right, let's get going! To free the princess from her curse, we've got to succeed in this mission.
<WAIT>
}