//--------------------------
#SPEAKER_ID "11"
@MEScol_Stop
{
<NS>Gallica<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_11498_c011">
Wait, where are you going? We have to check on the princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MSG_Forest_KeyFreeHint_01
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_11135_c011">
I'm worried about the princess... Her life is in our hands.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MSG_Forest_KeyFreeHint_02
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
She believes in a world where people can make their own future, just like you. She's the only one who can see that dream become a reality!
<WAIT>
}