//--------------------------
#SPEAKER_ID "11"
@MES_ACC_AKADEMEIA_ACC_09_34
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Kind of a stupid plan if it involves giving your daughter's murderer a chance to take the throne... I don't see the logic.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_ACC_AKADEMEIA_ACC_CLASS_58_01
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
This looks like research documents about the <COLOR 4>Princess<COLOR -1> Archetype.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_ACC_AKADEMEIA_ACC_CLASS_58_03
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
"The one who embodies the virtues of all heroes, standing magnanimously above them... There is no need to name her, for she has been called this since antiquity: <COLOR 4>Princess<COLOR -1>."
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_ACC_AKADEMEIA_ACC_CLASS_58_05
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
"But much will be expected of this royal hero: She must protect the people's livelihoods and the safety of the country with her life."
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_ACC_AKADEMEIA_ACC_CLASS_58_06
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
"This cannot be accomplished alone. True strength comes from knowing one's allies well enough to combine their strengths in battle. Let no Princess forget this truth."
<WAIT>
}