//--------------------------
#SPEAKER_ID "0"
@MEScol_house_17
{
<NS>Whispering Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'm sure the princess who saved our village is dedicating herself to this country the very same way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MEScol_ancientmuralB_003
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
<LIPSYNC>
I'm sure it's a depiction of the village's sacrificial rite, but it reminds me too much of things with the princess. Not a good feeling, either way.
<WAIT>
}