//--------------------------
#SPEAKER_ID "51"
@MEScommon_AKADEMEIA_TALK_13_00
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51044_c051">
The <COLOR 4>Princess Archetype<COLOR -1> you've awakened to is... most unique. It possesses a power no other Archetype has.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MEScommon_AKADEMEIA_TALK_SELECT SEL 0
{
Archetypes<COLOR -1>
Studying Archetypes<COLOR -1>
Channelling Archetypes<COLOR -1>
Advanced Archetypes<COLOR -1>
Inheriting Skills<COLOR -1>
Archetypes and Wielder<COLOR -1>
Synthesis<COLOR -1>
Party Formation<COLOR -1>
Special Experiment: Masks<COLOR -1>
Special Experiment: Summoning<COLOR -1>
The Princess Archetype<COLOR -1>
I have nothing to ask.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_01_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
For a world where her ideals are made manifest... I swear it!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_02_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
To support the dreams of Her Highness the Princess, the country of her ideals...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_04_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
All in the name of Her Highness the Princess. I shall wield this power to its fullest.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_14_HULK_03
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Hulkenberg_aizuchi_02_c003">
I see now—'tis the power of the <COLOR 4>Knight<COLOR -1>... In Her Highness's name, I shall wield it well!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_15_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
To protect Her Highness the Princess and the world she dreamt of...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_16_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
Let this new mission find purpose within me. It coincides well with protecting Her Highness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_18_HULK_08
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Hulkenberg_aizuchi_02_c003">
...I understand. Soon I will be protecting not Her Highness the Princess, but the new queen of this land!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_26_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
I will master the art of healing. All for the victory of Her Highness the Princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_30_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
My soul is beside Her Highness the Princess. I shall push forward, my original resolution held fast in my heart.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_38_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
I offer victory to Her Highness the Princess. I believe that the future of the kingdom is beyond those laurels...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MEScommon_GET_CLASS_39_HULK_09
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
I shall stake my life on the offer of victory to Her Highness and to all. Such is my promise.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MEScommon_AKADEMEIA_ROYAL_OPEN_1ST_02
{
<NS>More<NE>
<BUSTUP 2 0 0>
<LIPSYNC>
You have awakened the <COLOR 4>Princess<COLOR -1> Archetype. The power within your way of life has influenced even your allies, and now, signs of a power beyond imagination present themselves.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MEScommon_AKADEMEIA_OPEN_KING_MAGIC_01
{
<NS>More<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_51008_c051">
Incredible... That you could awaken not only the <COLOR 4>Princess<COLOR -1>, but the power of all the <COLOR 4>Royal Archetypes<COLOR -1> besides...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MEScommon_AKADEMEIA_CHAT_05_00
{
<NS>More<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_51021_c051">
A race to determine the new ruler, is it...? How thrilling. I'm most intrigued to see how it all develops.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MEScommon_AKADEMEIA_LASTBATTLE_BEFORE_011
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51038_c051">
But you have already overturned your fated demise once. If you do emerge victorious and become queen, you will truly have proved your ideals correct.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MEScommon_AKADEMEIA_LASTBATTLE_BEFORE_005
{
<NS>More<NE>
<BUSTUP 2 0 0>
<VOICE "v_e14_026_001_026_c051">
Now. Onward, O Queen of a new dawn!
<WAIT>
}