//--------------------------
#SPEAKER_ID "N2103"
@MES_dng_npc_D07_02_02_005
{
<NS>Fierce Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
A rookie's got to make a name for herself, y'know? Give the rest of us a reason to remember your face.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_dng_npc_D07_02_02_006
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
A rookie's got to make a name for herself, y'know?
<WAIT>
}