//--------------------------
#SPEAKER_ID "2"
@MES_dng_npc_D11_01_Stroll_105
{
<NS>Strohl<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_Dpv_PC_Stroll_verify_02_c002">
Then it's settled. If you win, you're the new queen! What better motivation could there be than that?
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_dng_npc_D11_01_Stroll_109
{
<NS>Strohl<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_Dpv_PC_Stroll_verify_02_c002">
Then it's settled. If you win, you're the new queen! What better motivation could there be than that?
<WAIT>
}