//--------------------------
#SPEAKER_ID "10"
@MES_dng_D02_001_Party_10_000
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Mooselk_thought_02_c010">
Some time after the assault, together with a small entourage, we decided to take Her Highness out in secret, to an appropriate hiding place.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_dng_D02_001_Party_10_000_00
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She was attacked in the royal palace, the place where she was supposed to be safest. We knew not when she'd be attacked again if we stayed in Grand Trad.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_dng_D02_001_Party_10_001
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Naturally, Her Highness was considered missing and eventually her death was deemed official.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_dng_D02_001_Party_10_002
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
From that time on, our organisation was formed to restore Her Highness to power.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_dng_D02_001_Party_10_004
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
After all, even the royal guards who protected Her Highness were kept in the dark. If they had known, they would have had no choice but to stop us.
<WAIT>
}