//--------------------------
#SPEAKER_ID "10"
@MES_dng_0017_001_Party_10_000
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Mooselk_thought_02_c010">
You've done a fine job delivering that message, lass. It's finally time for us to act for Her Highness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_dng_0017_001_Party_10_001_01
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Mooselk_reply_03_c010">
Nothing but a mercenary... And yet, His Majesty gave me the honour of being Her Highness the Princess's tutor in swordplay.
<WAIT>
}