//--------------------------
#SPEAKER_ID "0"
@MES_D11_02_e04_022
{
<NS>Walla<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_D12_npc04_01_m1154">
She defies Lady Louis!
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_D11_04_e01_006
{
<NS>Eupha<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But as the magla cleared, the strong emotions of those who support her forced their way past the anxiety to reach us here.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_D11_02_e05_011
{
<NS>Walla<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_D12_npc14_01_m1164">
You're the rightful queen!
<WAIT>
}