//--------------------------
#SPEAKER_ID "0"
@MES_D11_05_e01_004
{
<NS>Walla<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_D12_npc04_01_m1154">
She defies Lord Louis!
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_D11_05_e03_023
{
<NS>Strohl<NE>
<BUSTUP 5 0 0>
<VOICE "v_co_2077_c002">
You ought to have heard the cheers for the princess! The flaws in your plan are beginning to show, Louis!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_D11_08_e01_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
These were strong emotions that travelled through the magla, weren't they? They're placing their trust in the princess... In us.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_D11_05_e03_006
{
<NS>Walla<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_D12_npc14_01_m1164">
You're the rightful queen!
<WAIT>
}