//--------------------------
#SPEAKER_ID "0"
@MES_D09_02_e02_004
{
<NS>Calculating Monk<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Careful. The royal magic protects her. But she'll surrender if we kill her allies. Aim for the mustari girl!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_D09_02_e04_002
{
<NS>Scornful Warrior Monk<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1070001_m1092">
Mm... She's protected by the royal magic, remember. No matter. Master Gideaux will still appreciate us bringing her in alive.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_D09_02_e06_005
{
<NS>Wary Monk<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The elda is a candidate. She will be shielded by the royal magic, so aim for the mustari girl first!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_D09_02_e03_001
{
<NS>Calm Monk<NE>
<BUSTUP 0 0 0>
<VOICE "v_fm129002_fm129">
Aha... so you're our mysterious intruder, little elda girl.
<WAIT>
}