//--------------------------
#SPEAKER_ID "4"
@MES_D07_10_e05_029
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Let's not force the deception, lass. It would seem he is above such parlour tricks.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_D07_10_e05_028
{
<NS>Officer<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_D7_npc08_07_m1142">
Lost? What a paltry excuse, girl! You could have never made it onto the bridge through sheer luck!
<WAIT>
}