//--------------------------
#SPEAKER_ID "10"
@MES_D02_01_e03_021
{
<NS>Grius<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_Dpv_PC_Mooselk_verify_02_c010">
Understood? Now try it for yourself, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_D02_05_e02_004
{
<NS>Grius<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Mooselk_talk_02_c010">
Look closely, lass. There's a gap between those collapsed rocks.
<WAIT>
}