//--------------------------
#SPEAKER_ID "13"
@MES_fld_Strategy_Strategy06_01
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13403_c013">
Engine's warm, pressure's steady. So, where to, lass?
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_fld_Strategy_Strategy08_05
{
<NS>Heismay<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_4472_c004">
Now, what does Her Royal Highness have in mind?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_fld_Strategy_Strategy09_01
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13224_c013">
My beloved runner's in tip-top shape. Just tell me when you're ready, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_fld_Strategy_Strategy06_06
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13408_c013">
Preparations are all in place. Simply say the word my girl, and we'll be on our way.
<WAIT>
}