//--------------------------
#SPEAKER_ID "0"
@MES_fld_npc_Speech_Audience_018
{
<NS>Irritated Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1320002_m1320">
Lord Milo has ceased holding court with his eloquent speeches, and it's all because that elda child interfered... I'll never forgive her! <i>Never</i>!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_npc_Speech_Audience_030
{
<NS>Impressed Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1321005_m1321">
That so-called princess exceeded my expectations, going so far as to debate Julian.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_npc_Speech_Audience_002
{
<NS>Scornful Resident<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1367009_m1367">
I must thank that elda girl for showing up Loveless. Since their debate, that wastrel has refrained from <i>entertaining</i> us with his so-called speeches.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_npc_Speech_Audience_010
{
<NS>Curious Resident<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333006_m1333">
Aye, there was a fella named Roger giving speeches here before, wasn't there? After he went at it with that elda girl, I stopped seeing him.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_npc_Speech_Audience_011
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
That candidate, Roger, debated an elda girl here.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_npc_Speech_Audience_014
{
<NS>Resentful Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1357002_m1357">
After debating that ridiculous elda girl, Rudolf's no longer giving speeches. Damn him!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_npc_Speech_Audience_015
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Stupid girl, daring to challenge Rudolf...
<WAIT>
}