//--------------------------
#SPEAKER_ID "4"
@MES_fld_Strategy_Strategy05_03_04
{
<NS>Heismay<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_4077_c004">
A misstep here would cost us a means to save Her Highness... We'll need you to make a prudent decision, <HERO_NAME>.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_fld_Strategy_Strategy06_04_02
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_3143_c003">
A fair proposal, but I believe we should focus on gathering support now. Saving the princess will be for nought if someone else pilfers the throne.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_fld_Strategy_Strategy06_07_03
{
<NS>Junah<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_5074_c005">
We'll just have to prepare however we can, dearies. Rallying support for the princess couldn't hurt either.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_fld_Strategy_Strategy06_08_03
{
<NS>Strohl<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_2076_c002">
We need to gain more rapport from the people as well. A victory for the princess becomes ever more unobtainable the further Louis pulls ahead.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_fld_Strategy_Strategy06_08_04
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13112_c013">
The heart of matter is—the lance's important, but helping people is what makes our lass special, and sets her apart from the chaff. The decision is yours, O Captain.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_fld_Strategy_Strategy08_01_04
{
<NS>Hulkenberg<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_3077_c003">
I concur. And to that end, 'tis imperative we gather our strength. Our sole focus should be on training until the day a new ruler is crowned.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_fld_Strategy_Strategy08_90_01
{
<NS>Basilio<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_8040_c008">
The day's here, huh. Well, if <HERO_NAME> just gives Louis a beatin' and becomes the new queen, that'll be our problem solved!
<WAIT>
}