//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_001
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1061_c001">
I ended up standing out more than I expected... I've gained a lot of interest, but I only consider this a part of my mission to aid the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_003
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1090_c001">
After solving the case, I've gained support from the people of Martira. I'm one step closer to Louis and executing our plan to save the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_004
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1061_c001">
After the events of the Exhibition, many people seem to have taken notice of me. I hope this eventually leads to saving the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_005
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1302_c001">
More people have taken an interest in me, and Louis has formally acknowledged it. Now, we just need to find the formula to the princess's curse...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_006
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1302_c001">
It seems the reputation I gained at the Exhibition saved me. All that remains is to break the princess's curse using the formula...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_007
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1235_c001">
After defeating the human and saving Eupha alongside Virga Island, I gained their support. We're blazing a path to defeating Louis and saving the princess, one step at a time...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_008
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1090_c001">
I finally defeated my arch-nemesis, Louis. This should break the princess's curse...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_009
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1061_c001">
My support has increased dramatically now that I've announced I am the princess, and I can't let the people down...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_fld_ElectionRankUP_010
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1061_c001">
Rella, the candidate in second place, has fallen... The believers who stood by her will likely transfer their support to "the princess"...
<WAIT>
}