//--------------------------
#SPEAKER_ID "2"
@MES_fld_Fellow_02_03_01
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It seems a long way off, but when you consider we have to break the curse Louis placed on the princess and prepare for her return, we've not much time to spare.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_fld_Fellow_03_02_00
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_3195_c003">
We'll free Alces from his dying regrets. For Her Highness's sake as well.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_fld_Fellow_03_02_01
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_3194_c003">
For Her Highness's sake, let us settle this.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_fld_Fellow_02_03_00
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_2106_c002">
The next ruler will be decided on the Day of the Hero, October 27th. That's four months from now.
<WAIT>
}