//--------------------------
#SPEAKER_ID "11"
@MES_RankArchetype02_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
They seem to be saying anyone can be ruler, but we know it's not that simple. If we focus on breaking the princess's curse, hopefully we won't have to worry about it!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_RankArchetype05_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
I know we stole a little bit of the spotlight, but remember, the purpose of all of this is to break the princess's curse!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_RankArchetype12_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
We're shouldering plenty already, I think. Even though you're lying about being the princess, we're not lying about wanting to make this a better country.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_RankArchetype16_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
I know it'll be tough to regain all the support you lost, but I'm sure you can do it. After all, you're the <i>real</i> princess now!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype01_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
The true ruler who the people wouldst choose must be as a culmination of the heroes of eld. If thou shouldst use thy power as 'tis meant to be, the path will open before thee.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype02_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must have many fateful encounters with comrades-to-be and amass the souls of many heroes...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype03_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must, on the course of thy journey, amass the souls of many heroes and display tremendous royal virtues...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_RankArchetype03_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
Remember, you're only in the running to be queen for the sake of the mission. There's no telling how many formidable foes stand between us and Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype05_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must draw strength from all resources at thy disposal, and grow thy strength along with the souls of heroes thou hath gathered...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype06_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must travel far and wide, together with the souls of heroes, and develop newfound power...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype07_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must not fight alone... Together with brave comrades, thou must delve into the possibilities within the souls of the heroes...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_RankArchetype07_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
I know we aren't really aiming for you to become queen, but if you're protected by the royal magic, I suppose that means we owe your supporters our thanks.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype08_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must sway the hearts of the people... Together with the souls of heroes, thou shalt continue to challenge fearsome trials...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype09_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must light the path with the power of the souls of heroes, and change thy very destiny...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype10_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must wield an impartial gaze. Fixate not on one road, but interact with the multitude of the heroes' souls...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype11_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must not shrink in the face of danger... Even in situations most dire, thou must grasp at all chance before thee...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype12_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must shoulder even fate most terrible, and complete this trial together with the souls of heroes...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype13_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must prepare for the final battle and gather the full force of the souls of heroes to complement thy strength...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype14_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must prove, together with we, the heroes' souls, the value of the future thou plan to create...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype15_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must reach the power of the heroes' souls even when shrouded in darkness... Thou must find a new point from which to view thyself...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype16_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must prove thine own existence together with thy new hero's soul...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype17_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
Believe in the lessons of thy journey thus far. To become the true ruler of this land, thou must charge valiantly into the face of anxiety, with us close to thy heart...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype18_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
Do not waver, and remain on the path thou hath tread. To become the true ruler of this land, thou must display to the people the chivalrous hearts of the many heroes' souls...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype19_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
Thou must not stop thy forward charge. To become the true ruler of this land, thou must make reality the ideals that we heroes so dreamed of...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype20_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
To become the true ruler of this land, thou must give the people a dream to foster. Together with the heroes' souls, lead by thy shining example...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype21_001
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
With dreams of fantasy in thy heart, thou art striving to change reality. Thou art now <COLOR 0>one who walks the path of ruler<COLOR -1>...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype21_002
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
Thou must display the culmination of thy power. In every age, the souls of heroes accompany the true ruler. With us at thy side, thine ideals shall find fruition...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_RankArchetype23_001
{
<NS>Heroes' Souls<NE>
<BUSTUP 0 0 0>
Thou art now one who hath amassed the heroes' souls, one who is worthy to be called the true queen... <COLOR 0>One who stands at the pinnacle<COLOR -1>.
<WAIT>
}