//--------------------------
#SPEAKER_ID "0"
@MES_fld_gaya_Skateboarding_010
{
<NS>Line 1<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1323018_m1323">
The elda riding that sword... It's the princess!? No way!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_gaya_Skateboarding_011
{
<NS>Line 2<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380004_m1380">
The princess riding around on a sword... I'm not sure if I should be surprised.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_gaya_Skateboarding_012
{
<NS>Line 3<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1379004_m1379">
Haha, look! It's the rumoured sword-riding princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_fld_gaya_Skateboarding_013
{
<NS>Line 4<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1321005_m1321">
I thought it was just a rumour, but the princess really does ride a sword.
<WAIT>
}