//--------------------------
#SPEAKER_ID "11"
@fld_FaceObject_MountWaiting_02
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
All we have to do now is beat Louis and put an end to this. For the princess's sake.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@fld_FaceObject_FirstAccess_01
{
<NS>Mysterious Voice<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Locus of her people's support, great custodian of their anxieties. At the foot of this monumental stone will their feelings gather as MAG.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@fld_FaceObject_DeviceThird_02
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
There's only one person who can be ruler. I want everyone to be able to face each other and speak honestly.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@fld_FaceObject_DeviceFourth_02
{
<NS>Gallica<NE>
<BUSTUP 5 0 0>
<LIPSYNC>
Honestly, though? I hardly care about Louis or "saving" this country anymore. I just want you to be queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@fld_FaceObject_Access_00
{
<NS>Mysterious Voice<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_68025_c068">
Thou who art destined to become queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@fld_FaceObject_FirstAccess_00
{
<NS>Mysterious Voice<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_68025_c068">
Thou who art destined to become queen...
<WAIT>
}