//--------------------------
#SPEAKER_ID "11"
@MES_fld_GAllicA_talk_Scenario_00_075
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_11614_c011">
I'm worried about the princess... Let's hurry to the village.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_fld_GAllicA_talk_Scenario_00_075_01
{
<NS>Gallica<NE>
<BUSTUP 7 0 0>
<VOICE "v_co_11139_c011">
How could things come to this... Is the princess still in the cave? Is she safe?
<WAIT>
}