//--------------------------
#SPEAKER_ID "N1196"
@MES_fld_npc_Fairy_024
{
<NS>Merry Fairy<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1311003_m1311">
Huh? Oh, hey! Miss Fairy over there with the woman child! Never seen you in these parts before, but it's nice to see more fairies in the area!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1196"
@MES_fld_npc_Fairy_032
{
<NS>Merry Fairy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Hey, woman child with the fairy! You two sure get along well, don't ya!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1198"
@MES_fld_npc_Fairy_035
{
<NS>Pondering Fairy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Remember that story about the king and queen? They're dead ringers! If you follow the story, the woman child would be the king and...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1831"
@MES_fld_npc_Fairy_038
{
<NS>Tactless Fairy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364004_m1364">
Wow, this woman child woke up after such a long nap, and then went right back to sleep!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_fld_npc_Fairy_039
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_11135_c011">
You've got it wrong. She's not sleeping...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N182"
@MES_fld_npc_Fairy_092
{
<NS>Simple Fairy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You know how crazy the world is right now, Miss Famous Person!? From wheres-it to whats-it, everything's gone <i>weird</i>!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N182"
@MES_fld_npc_Fairy_094
{
<NS>Simple Fairy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So, Miss Famous! Can you do something about this awful sky?
<WAIT>
}