//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_40_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332001_m1332">
I see a bright future for us with Her Highness the Princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_40_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347020_m1347">
It'd be nice if our next ruler is someone who won't destroy the Grand Cathedral.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_40_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1346005_m1346">
Who do you think would make for an interesting ruler?
<WAIT>
}