//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_05_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380004_m1380">
Single combat with Louis! Well she's gettin' right to it, our princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_05_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
No matter the place, no matter the time, I'm supporting the princess!
<WAIT>
}