//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_15_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1341018_m1341">
I can't believe the princess was alive all this time...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_15_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334014_m1334">
So even that elda girl can be queen...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_15_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361002_m1361">
Nobody really believes that <i>anyone</i> can become ruler...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_15_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361001_m1361">
Wow... <i>Anyone</i> can become ruler...
<WAIT>
}