//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0011_001_INN_01_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330003_m1330">
Wait, so that kid from the tavern... She's the elda from the Exhibition that everybody's talking about!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0011_001_INN_01_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328003_m1328">
Why would the princess come to a dive like this...? Oh, I mean, no, that was rude of me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0011_001_INN_01_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327001_m1327">
You have my support, Your Princessliness. Give that Louis what for!
<WAIT>
}