//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_31_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360001_m1360">
So the princess was still alive...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_31_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1313003_m1313">
The people decide who becomes ruler? How's that gonna work?
<WAIT>
}