//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_003_OCEAN_16_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1318004_m1318">
The Exhibition is where I'm gonna determine who's best fit to be ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_003_OCEAN_16_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326012_m1326">
It'll all end in tears, the way things are going to decide the ruler...
<WAIT>
}