//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_001_MOUNT_07_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328009_m1328">
Oi, it's that elda everyone's been talkin' about! Well, well, our candidate sure looks prepared, doesn't she?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_001_MOUNT_07_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1329005_m1329">
Your Highness! My faith's with you, lady!
<WAIT>
}