//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_12_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1349005_m1349">
The lass is the princess... Who could've known?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_12_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1378010_m1378">
The princess's words ring true... I trust she'll help anyone in need.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_12_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1354001_m1354">
Did you hear? That elda girl donated quite the sum to the town...
<WAIT>
}