//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_04_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360015_m1360">
I mean, I'd <i>like</i> to believe in the princess, but...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_04_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360004_m1360">
The princess is the one who saved this city. That much I know is true!
<WAIT>
}