//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_22_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370005_m1370">
Knock 'em dead out there, elda girl!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_22_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370005_m1370">
How's it going, elda girl?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_22_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370006_m1370">
Elda girl, become queen for us!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_22_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370009_m1370">
I believe in you, elda girl...
<WAIT>
}