//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_11_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333001_m1333">
That elda girl and her mates are pretty impressive, eh!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_11_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328003_m1328">
Never thought the city would be saved by Her Royal Highness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_11_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328013_m1328">
If the town supports the princess, won't that draw Louis's attention?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_11_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327004_m1327">
Let's get everyone in the town to throw in their lot with the princess!
<WAIT>
}