//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_01_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1348003_m1348">
Even if that elda chappie <i>is</i> the princess, her opponent is still Louis...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_01_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347005_m1347">
Hey, isn't that girl from the Exhibition kind of cute for an elda?
<WAIT>
}