//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_20_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334015_m1334">
Did the late king not want his own daughter to inherit the throne...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_20_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1335001_m1335">
Her Majesty the Queen is really doing her best out there, despite being so young...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_20_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334012_m1334">
I don't care who becomes ruler, as long as it's not some gormless twit...
<WAIT>
}