//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_07_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1387011_m1387">
After all that, we're still the ones saddled with deciding the ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_07_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364018_m1364">
What if someone no one expects becomes ruler...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_07_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1322004_m1322">
Exciting, innit? A new ruler crowned right before our eyes...!
<WAIT>
}