//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_29_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1351005_m1351">
H-Hey, that's...! That's Her Highness the Princess, right?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_29_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1386001_m1386">
P-Princess! I've been rooting for you...!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_29_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1345011_m1345">
What are the candidates for ruler even thinking?
<WAIT>
}