//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_25_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332012_m1332">
The only way to stop Louis from being king is to place our hopes on the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_25_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1323012_m1323">
Why go through all this just to pick the next ruler?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_25_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1323013_m1323">
A ruler needs all manner of certain qualities...
<WAIT>
}