//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_33_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326012_m1326">
Are you pro-Louis or pro-princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_33_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364004_m1364">
Eeeeeep! It's the princess! Oh, oh, look over here, Your Highness!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_33_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347005_m1347">
That girl looks just like the new queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_33_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1374012_m1374">
I just want the new ruler to protect us from humans...
<WAIT>
}