//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_36_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1329001_m1329">
She may be a princess, but she's wise in the ways of the world...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_36_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1329005_m1329">
I'm going to root for the princess. She's been out there in the world, she's seen what it's like to struggle.
<WAIT>
}