//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1379001_m1379">
Louis's impertinence makes no one happy... Least not Her Highness the Princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1384016_m1384">
I believe in Her Highness the Princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1354012_m1354">
Princess, don't you go losin' to Louis now!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334007_m1334">
The person who attack the Grand Cathedral first was Louis... Not the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328012_m1328">
Hey, Princess, this won't be the end of it, will it...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1336002_m1336">
You're saying the princess is a monster, but is Louis any different?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1357004_m1357">
Her Highness the Princess may still be able to stop Louis...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_012
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1341018_m1341">
Look, Her Highness the Princess is safe and sound. There's still hope yet...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_013
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
...We should believe in what Saint Rella said. She's really the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_CHEERING_014
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1341016_m1341">
Louis won't be the one getting the last laugh... It'll be our princess!
<WAIT>
}