//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0011_002_INN_01_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330003_m1330">
Look, that elda kid... is she the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0011_002_INN_01_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330003_m1330">
Look at that elda kid... is she really the princess?
<WAIT>
}