//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_CHEERING_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334001_m1334">
We ain't afraid of Louis! We got the princess on our side!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_CHEERING_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332001_m1332">
Look, the princess is here! Now everything'll sort itself out...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_CHEERING_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361001_m1361">
I supported Goddard, but... We should entrust our hopes now in the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_CHEERING_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360001_m1360">
Look, over there! Her Highness remains safe!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_CHEERING_011
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370009_m1370">
Soldiers! Protect Her Highness from the rioters!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_CHEERING_012
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1349004_m1349">
You Louis-supporting fools! Her Highness is passing by!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_CHEERING_013
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1372002_m1372">
Phew, Her Highness is a stubborn one... She's well worth our support.
<WAIT>
}