//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_CHEERING_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1352002_m1352">
Now's the time to show Her Highness the way faith ought to be!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_CHEERING_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1373001_m1373">
It's Her Highness... Oh God, let light shine upon Sanctism!
<WAIT>
}