//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_10_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360002_m1360">
What're the Sanctists doing now? Quit givin' our princess a hard time!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_10_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1357007_m1357">
Hang on, what's happened with our princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_10_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333004_m1333">
I'm not afraid of Louis. I know our princess is gonna win!
<WAIT>
}