//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_01_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1315002_m1315">
First Her Highness the Princess, now even His Majesty... What's to become of us?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_01_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1323018_m1323">
Unbelievable... That elda girl was the princess all along...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_01_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1336004_m1336">
Her Highness the Princess has returned!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_01_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328003_m1328">
It's hard to believe the will of the people will determine the next ruler...
<WAIT>
}