//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_12_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361004_m1361">
Hey! Louis and the princess— How 'bout we stick the loser's bonce out on display?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_12_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1315002_m1315">
Decide on the ruler...? What are those toffs thinking...
<WAIT>
}