//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_002_CLIFF_01_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1384015_m1384">
We owe her a debt for saving the city, sure, but if we oppose Louis now...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_002_CLIFF_01_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1377006_m1377">
Let us pray for her victory. We too must demonstrate courage.
<WAIT>
}