//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_13_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1372002_m1372">
Choosing a ruler just based on an impression? How ridiculous.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_13_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1372002_m1372">
The tournament's a charade... Just a mindless spectacle where we pretend we're choosing the ruler ourselves...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_001_OCEAN_13_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330003_m1330">
So... the ruler really will be chosen by those who shout loudest in the crowd, no thought behind it at all...
<WAIT>
}