//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_12_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1342005_m1342">
So, what did the queen end up doing?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_12_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358002_m1358">
Anyone can become the next ruler...? Wait, except a paripus, right?
<WAIT>
}