//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_003_OCEAN_18_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1362004_m1362">
Heh heh heh... Welcome, lass. Make yourself <i>comfortable</i>.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_003_OCEAN_18_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369005_m1369">
I heard the princess used to board at one of these piss-poor inns!
<WAIT>
}