//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_20_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332001_m1332">
I still have hope for this country's future. <i>She's</i> the princess, after all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_20_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333006_m1333">
You needn't worry about anything while you're on this island, dear princess of ours.
<WAIT>
}