//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_06_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1353014_m1353">
That elda Bardon brought here is the princess everyone was gossiping about.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_06_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1352007_m1352">
Joanna deceived us, and I ain't sure we can trust the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_06_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1387001_m1387">
Ye know, she didn't abandon the small towns... She ought to be queen!
<WAIT>
}