//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_09_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360012_m1360">
Doubt it. No one would support that monstrous princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_09_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1348007_m1348">
Electing a ruler... I've never heard such rubbish.
<WAIT>
}