//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0011_001_INN_02_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1359004_m1359">
We're Her Highness the Princess's tavern of choice... Hah, wouldn't that be something.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0011_001_INN_02_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330005_m1330">
Oi, Princess! Hope you ate well!
<WAIT>
}