//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_003_OCEAN_05_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1359011_m1359">
If I'd known that elda would become famous, I'd have given her accommodations...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_003_OCEAN_05_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1339014_m1339">
You monstrous princess! Get out, <i>get out</i>!
<WAIT>
}