//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_001_MOUNT_CHEERING_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1319017_m1319">
Look, it's Her Highness the Princess! If Her Highness is alive, perchance there's a sliver of hope yet!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_001_MOUNT_CHEERING_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
Let the rioters do their worst! My loyalties are with the princess, to very end!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_001_MOUNT_CHEERING_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1312016_m1312">
Don't be swindled by Louis's lies! Lady Rella believed in Her Highness.
<WAIT>
}