//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_004_CLIFF_02_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1336004_m1336">
That's right. This whole town is an ally to the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_004_CLIFF_02_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1371001_m1371">
It may be strange, given everything that's happened, but I ain't worried at all. The princess will do right by us.
<WAIT>
}