//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_20_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1345002_m1345">
It wasn't Louis who was helping people! It was the princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_20_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347005_m1347">
Look, look! Isn't that Her Highness the Princess over there!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_20_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
The new ruler will change the world for us...
<WAIT>
}