//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_14_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1367002_m1367">
Isn't deciding a ruler by consensus just careless at this point? Look at our situation.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_14_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347014_m1347">
All this ruler tosh has gotten exciting, hasn't it...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_14_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347004_m1347">
I'm looking forward to seeing who'll be ruler...
<WAIT>
}