//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_05_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1315007_m1315">
Looks like we've got to pick between Louis and the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_05_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1317002_m1317">
Letting the people decide the next ruler? What a farce...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_05_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1313004_m1313">
Hm, what qualities would be good in a ruler? What I say is...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_05_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1314005_m1314">
Hm. What I'd like to see under the next ruler reign is freedom, with no strings attached!
<WAIT>
}