//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_23_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364004_m1364">
Eeee! It's her! It's Her Highness the Princess! Over here, Your Highness!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_23_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1344002_m1344">
The people deciding the ruler... That's not normal, if you ask me!
<WAIT>
}