//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_36_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1367007_m1367">
We're in for more of these incidents before the ruler decided, I think...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_36_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1335004_m1335">
Honestly, I don't care who the ruler ends up being, as long as it's exciting.
<WAIT>
}