//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_03_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
I'd like to entrust my fate to Her Highness, the saviour of this island.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_03_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1383001_m1383">
That girl may truly have the aptitude to be queen.
<WAIT>
}