//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_11_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1344001_m1344">
The princess might actually be my type, maybe...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_11_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1320001_m1320">
I'm going to support the princess! She's kind of handsome!
<WAIT>
}