//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_004_MOUNT_CHEERING_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1375001_m1375">
We mustn't abandon our faith! This kingdom still has its princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_004_MOUNT_CHEERING_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1378001_m1378">
I'll believe in Her Highness until the very end of my days!
<WAIT>
}