//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_003_MOUNT_16_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369005_m1369">
Well now, if it ain't that elda... You reckon she has a relic?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_003_MOUNT_16_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370005_m1370">
Hey, isn't that the princess everyone's been talking about?
<WAIT>
}