//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_17_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1388003_m1388">
Our trust and support is really <i>actually</i> going to determine the ruler...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_17_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1351005_m1351">
The new ruler going to be decided at the Grand Cathedral here...!
<WAIT>
}