//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_16_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1331004_m1331">
I like this princess fellow. She had to work her way up on her own, didn't she?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_16_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358011_m1358">
I couldn't care less who becomes ruler, so long as they give me money.
<WAIT>
}