//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_04_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358011_m1358">
I don't care who's ruler. I'll support anyone that gives me some coin...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_04_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1357003_m1357">
Ah, too right. I say I don't care who becomes ruler, and this is what happens...
<WAIT>
}