//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_03_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1345002_m1345">
You've got to be kidding? <i>She's</i> really Her Highness the Princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_003_CLIFF_03_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1354012_m1354">
This city can trust Her Highness the Princess...
<WAIT>
}