//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_004_CLIFF_03_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369001_m1369">
If that girl is truly Her Highness, then we may have some hope left yet...!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_004_CLIFF_03_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1373003_m1373">
I want to support the princess, but if that means exposing the city to danger, well...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_004_CLIFF_03_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360001_m1360">
On my honour as a soldier, I swear that I shall fully dedicate myself to the defence of all of the princess's supporters!
<WAIT>
}