//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_CHEERING_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1351005_m1351">
The princess we saw in this town was always fighting for someone's sake!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_CHEERING_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364005_m1364">
The princess is no monster. She's kind, and a regular patron at the Honeybee.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_CHEERING_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360013_m1360">
Louis will abandon the weak... The princess wouldn't do that.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_CHEERING_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1384016_m1384">
Oh Princess, please... Put an end to this fighting.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_CHEERING_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340005_m1340">
Hey Princess... I believe in you...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_CHEERING_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330012_m1330">
Don't you lose now, Princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_CHEERING_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1329005_m1329">
I believe Her Highness the Princess will win. Until then, protecting this city is our responsibility...!
<WAIT>
}