//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_002_CLIFF_06_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1336001_m1336">
The elda candidate made a donation, so I'd say she's travelling with a fine bunch indeed.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_002_CLIFF_06_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1336004_m1336">
We're all rooting for Her Royal Highness the Princess, aren't we!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_002_CLIFF_06_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326019_m1326">
So we either make an enemy out of Louis, or we totally neglect our obligation to the princess...
<WAIT>
}