//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_13_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1319003_m1319">
I think that's that candidate. Is she here to destroy our traditions too?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_13_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1384004_m1384">
Did you see Her Highness's gallantry? She'll make short work of Louis!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_13_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1367001_m1367">
The island owes a debt to that candidate—to the princess.
<WAIT>
}