//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_13_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1374004_m1374">
Hey look, this town's got nothin' to be scared of, we got the princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_13_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333006_m1333">
No two ways about it, I support the princess, and that's that.
<WAIT>
}