//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_09_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326018_m1326">
The blighted girl candidate. I never expected her to still be in the race.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_09_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1372004_m1372">
Aha, I knew that was the princess, right from the very start.
<WAIT>
}