//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_11_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326012_m1326">
I bet Louis and the princess are both busy preparing for the decisive battle ahead...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_11_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369006_m1369">
Hey, let's close up early so we can see the moment the ruler decided...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_11_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1339013_m1339">
The days of fighting over who'll be ruler feel like a faraway past now...
<WAIT>
}