//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0012_002_INN_01_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330003_m1330">
I hear that elda kid is actually the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0012_002_INN_01_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327004_m1327">
The princess was the one who revealed that Heismay was framed. I believe in her.
<WAIT>
}