//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_30_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334005_m1334">
Would it be good marketing if I say the princess herself bought equipment here...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_30_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1331003_m1331">
Damn, there's a lot more chaps out here wanting to be ruler than I expected...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_30_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1357009_m1357">
Life's gotten a lot more stable thanks to the queen...
<WAIT>
}