//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_18_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1366007_m1366">
I don't give a damn who's ruler, can someone just hurry up and do something about this city?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_18_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364014_m1364">
Tsk. If people have got enough free time on their hands to dawdle around and talk about who should be ruler, then they should be able to spare a moment to help me out a bit here...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_18_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330004_m1330">
I am witnessing the dawn of the new era, and it's all thanks to the new ruler.
<WAIT>
}