//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_01_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1362005_m1362">
H-Hey, the princess... That's the elda we saw around here, right...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_01_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358011_m1358">
I don't give a toss who's ruler, I just want some coin.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_01_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333013_m1333">
Oi, Queen! Thanks for protecting the country!
<WAIT>
}