//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_21_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334008_m1334">
Wait, so we're going to choose the ruler...? I don't get it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_21_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1353013_m1353">
Does deciding the ruler mean we decide the country's future?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_21_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1318004_m1318">
Yeah, I say we need a new form of government which doesn't vest all the power in one ruler...
<WAIT>
}