//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_04_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330005_m1330">
Oi, Princess! So we're on your side, eh!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_04_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328007_m1328">
The princess is a human, you say? ...You're talkin' nonsense, mate.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_04_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334002_m1334">
Don't let Louis sucker ya in with smooth talk! The princess has our backs!
<WAIT>
}