//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_13_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
I'm going to support the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_13_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360007_m1360">
Doesn't matter who the ruler is. Doesn't affect our lives one bit...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_13_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326013_m1326">
If the ruler changes, will the army change a bit too...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_13_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1388001_m1388">
I'm glad that child became queen in the end...
<WAIT>
}