//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_14_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334012_m1334">
I don't care who the ruler ends up being as long as I can keep running my business...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_14_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360004_m1360">
How about celebrating the new ruler in advance by buying something?
<WAIT>
}