//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_002_CLIFF_04_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1330003_m1330">
What's that? You telling me Her Highness the Princess saved this city?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_002_CLIFF_04_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1372009_m1372">
I got some donated money from the city. Apparently it's from an elda girl...
<WAIT>
}