//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0012_002_INN_02_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1384005_m1384">
It's you... Are you really the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0012_002_INN_02_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1368004_m1368">
This town is on the princess's side. Three cheers to the princess!
<WAIT>
}