//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_42_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380004_m1380">
That elda girl and her mates are pretty impressive, eh!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_42_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1359011_m1359">
Is the ruler really going to be decided through popularity alone...?
<WAIT>
}