//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_06_006
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1352003_m1352">
I never thought she'd be the last remaining candidate for queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_06_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1324001_m1324">
We gotta do right by her for saving our city! Let's promise her our support!
<WAIT>
}