//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_08_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1363005_m1363">
Did you see that? There's a girl's face on that rock...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0004_001_PAGAN_08_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1365007_m1365">
Much as I'd like to support the princess, it terrifies me to think of what Louis would do to me...
<WAIT>
}