//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_CHEERING_000
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364005_m1364">
The princess hasn't given up on this country... And neither have we!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_CHEERING_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361001_m1361">
The princess is alive and well... Perhaps this country can still be saved...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_CHEERING_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1378010_m1378">
The princess hasn't forsaken this country...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_CHEERING_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1357008_m1357">
I hear the former candidate Lina's supporting the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0003_002_OCEAN_CHEERING_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1367008_m1367">
Look, there's Her Highness! It's too early to give up now...
<WAIT>
}