//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_26_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326020_m1326">
Come on, Princessy, I've got all my savings riding on you...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_26_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1329004_m1329">
I wagered my life savings on the princess, so... I'm over the moon here, mate!
<WAIT>
}