//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_16_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332011_m1332">
Is it wrong to put all my hopes on the princess...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_16_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360015_m1360">
What's the point in spending so much time deciding on a ruler?
<WAIT>
}