//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_27_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361001_m1361">
The queen really seems to be giving it her all out there...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_27_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327001_m1327">
It's nice to know it's our trust and support that'll determine who the ruler is.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_002_KING_27_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326012_m1326">
Are either of them truly fit to be ruler...?
<WAIT>
}