//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_CHEERING_002
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364005_m1364">
Look, you can see the princess for yourself! Does she look like a monster to you!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_CHEERING_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
The rest of you can do what you want, but I believe in the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_CHEERING_011
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361005_m1361">
If you really want a big reward, put your faith in Her Highness. Don't you think I'm right?
<WAIT>
}