//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_11_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1325004_m1325">
Imagine being stupid enough to want to be a ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_11_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1348003_m1348">
The next ruler won't do anything but get entangled in politics...
<WAIT>
}