//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_14_004
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1379011_m1379">
Can we trust that gauntlet runner is her?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0002_001_CLIFF_14_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1380014_m1380">
I might give another look to that young woman... Or should I say, Her Royal Highness!
<WAIT>
}