//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_28_009
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1345011_m1345">
If it's between Louis and the princess... Hmm, I'd go with the princess, I guess...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_003_KING_28_008
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326012_m1326">
"Anyone can be ruler..." Even now it still sounds ridiculous to me...
<WAIT>
}