//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_06_010
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1335004_m1335">
We must act fast and find a way into the princess's inner circle. While we still can...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_06_005
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358005_m1358">
It's <HERO_NAME>! She's still alive.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0001_001_KING_06_007
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1339004_m1339">
We've got no choice but to support the new queen, however awful she is...
<WAIT>
}