//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_03_001
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1365003_m1365">
I wonder if the princess will lend her hand to the needy?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_gaya_0005_002_MOUNT_03_003
{
<NS>Local Chatter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328003_m1328">
So who was it that placed a curse on the princess?
<WAIT>
}