//--------------------------
#SPEAKER_ID "0"
@MESini_SPOT02_SHOP07_00
{
<NS>Sturdy-Looking Villager<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Speaking of, I've heard some elda girl has been impersonating the princess. As an elda yourself, I'm sure it's only made things worse for you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MESini_SPOT02_SHOP02_sel_1 SEL 0
{
The village.<COLOR -1>
The next ruler.<COLOR -1>
Small talk.<COLOR -1>
Never mind.
<WAIT>
}