//--------------------------
#SPEAKER_ID "0"
@MESini_SPOT16_SHOP15
{
<NS>Ishkia Hermit<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
We may lead hermetic lives, but we're actually quite curious to learn who becomes ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MESini_SPOT16_SHOP10_1 SEL 0
{
The village.<COLOR -1>
The next ruler.<COLOR -1>
Small talk.<COLOR -1>
Never mind.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MESini_SPOT16_SHOP22
{
<NS>Ishkia Hermit<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oh, I'm glad I'm not out there with all that going on. Last thing I'd want is to lose my life in some meaningless conflict over ruler. No thank you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MESini_SPOT16_SHOP23
{
<NS>Basilio<NE>
<BUSTUP 10 0 0>
<VOICE "v_co_8073_c008">
Even after everything that's happened, you still don't care who's ruler?
<WAIT>
}