//--------------------------
#SPEAKER_ID "11"
@MSG_KeyFreeHint_09_06
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_11618_c011">
Anyway, let's rest up. Now that the princess's curse has been lifted, we can't just mope around.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MSG_KeyFreeHint_10_05
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_11545_c011">
This magla that I'm sensing... I'm worried about the princess. We need to hurry over to the hideout on the lower level.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MSG_KeyFreeHint_10_06
{
<NS>Protagonist<NE>
<BUSTUP 7 0 0>
<VOICE "v_co_1348_c001">
I need to get to the princess as quickly as I can...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MSG_KeyFreeHint_10_07
{
<NS>Gallica<NE>
<BUSTUP 7 0 0>
<VOICE "v_co_11137_c011">
The princess is in the <COLOR 0>prayer room on the lower level<COLOR -1>. I don't want to believe it... but we need to see her for ourselves.
<WAIT>
}