//--------------------------
#SPEAKER_ID "N334"
@MES_npc_NEWS_017_KING
{
<NS>Knowledgeable Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1272004_m1272">
Oh, if it isn't Her Majesty, in the flesh... visiting the Honeybee again? You're quite the whimsical one, aren't you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N334"
@MES_npc_0011_001_INN_Louis1_005
{
<NS>Knowledgeable Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If the ruler is to now be chosen through the support of the people... Well, there's no denying that he's the frontrunner for the throne.
<WAIT>
}