//--------------------------
#SPEAKER_ID "N859"
@MES_npc_0003_002_OCEAN_14_004
{
<NS>Coastal Sailor<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370005_m1370">
So you're the real princess, eh...? Dunno if that's true, but ever since the Exhibition the rumours about you haven't stopped.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_14_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
So you're the real princess, eh... Well, I'd choose you over Louis.
<WAIT>
}