//--------------------------
#SPEAKER_ID "85"
@MES_npc_QUEST_115_001_000
{
<NS>Loveless<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_85007_c085">
Hey! Still lickin' my wound from that arse whoopin' you gave me the other day. Damn, you're strong. Guess I shoulda expected it, seein' as you're the princess and all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "85"
@MES_npc_QUEST_115_001_004
{
<NS>Loveless<NE>
<BUSTUP 2 0 0>
<LIPSYNC>
Got me thinkin', you'd be a better queen than I ever could! So you go after Milo and anyone like him and hand 'em all their own sorry arses!
<WAIT>
}
//--------------------------
#SPEAKER_ID "85"
@MES_npc_QUEST_115_001_024
{
<NS>Loveless<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
We knew no matter who became ruler, it wouldn't change our tribe, or how folks look at us. We didn't expect anythin' to change.
<WAIT>
}