//--------------------------
#SPEAKER_ID "N939"
@MES_npc_HEATHEN_029_OCEAN
{
<NS>Masked Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1291001_m1291">
So we meet again, throne-bound elda girl.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N939"
@MES_npc_HEATHEN_038_OCEAN
{
<NS>Masked Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1291004_m1291">
Word of your renown has reached even my ears. They say you are far stronger than you look, and a brave candidate to be queen.
<WAIT>
}