//--------------------------
#SPEAKER_ID "N176"
@MES_npc_0001_002_KING_35_021
{
<NS>Igniter-Fixated Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I mean, come on! You'd be surprised too if the princess walked up on you all of a sudden...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_002_KING_35_019
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Long as nothing changes, I don't care who's ruler.
<WAIT>
}