//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_002_MOUNT_22_01_005
{
<NS>Jovial Eugief<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1346005_m1346">
Well, it's the girl candidate I got my eye on. Ever since the Exhibition, she's steadily improved her standing.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_002_MOUNT_22_01_008
{
<NS>Roussainte Peddler<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327004_m1327">
The only reason people support her is because she's an elda. You watch, they'll dump her without a second thought as soon as the novelty wears off.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_002_MOUNT_22_01_011
{
<NS>Puzzled Roussainte<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327011_m1327">
It's been a long time coming, but here we finally are. A final contest between Louis and the princess. Who could have foreseen it?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_002_MOUNT_22_01_012
{
<NS>Forlorn Rhoag<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'd never have thought that girl candidate would turn out to be the princess... And she's eldan royalty to boot? There's no precedent.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_002_MOUNT_22_01_013
{
<NS>Bored Rhoag<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1367001_m1367">
Oh, why not? Even Lady Rella acknowledges her mettle as a leader. I'll cast my lot with the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_002_MOUNT_22_01_018
{
<NS>Enthused Eugief<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Hear, hear! I have my doubts about whether that princess is even the genuine thing...
<WAIT>
}