//--------------------------
#SPEAKER_ID "N474"
@MES_npc_0002_002_CLIFF_03_000
{
<NS>Local Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360004_m1360">
You're a new face... Oh, are you that helper lass I heard about? Didn't expect you to be an elda...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N474"
@MES_npc_0002_002_CLIFF_03_038
{
<NS>Local Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I had no idea the lass Bardon brought to town would be Her Royal Highness the Princess, anointed by the sanctoress herself...
<WAIT>
}