//--------------------------
#SPEAKER_ID "N928"
@MES_npc_0003_003_OCEAN_05_009_00
{
<NS>Enchanting Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...And in times like these, it's the steadfast things that remain the same which are the most precious. Don't waver, my dearest elda princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_003_OCEAN_05_015
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Being true to yourself is most important, my dear elda princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N928"
@MES_npc_0003_003_OCEAN_05_016
{
<NS>Enchanting Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1348005_m1348">
Oh, hello, my dear princess. Hmm, something about you seems a little... different from the last time we met. But I can tell you're still trying your best.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N928"
@MES_npc_0003_003_OCEAN_05_016_01
{
<NS>Enchanting Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If you win, my dear princess, I'll make sure to give you a special reward to celebrate. That's a promise.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N928"
@MES_npc_0003_003_OCEAN_05_001
{
<NS>Enchanting Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Would you like to play with me for a little while, sweet girl? There are just so many things I'd <i>love</i> to do to you...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N928"
@MES_npc_0003_003_OCEAN_05_003
{
<NS>Enchanting Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1348006_m1348">
Well now, if it isn't my darling eldan girl. You've become quite famous, or so my customers tell me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_003_OCEAN_05_013
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You've become quite famous, my dear elda girl...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N928"
@MES_npc_0003_003_OCEAN_05_007
{
<NS>Enchanting Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Do come back to my city again when you've gotten a little older, dear girl.
<WAIT>
}