//--------------------------
#SPEAKER_ID "N308"
@MES_npc_0011_007_BARRACK_09_001
{
<NS>Demo Man Goddard<NE>
<BUSTUP 0 0 0>
<VOICE "v_fm117001_fm117">
That's rich! A mere fledgling—with no history or experience to speak of—as queen? The idea makes me sick to my stomach!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0011_007_BARRACK_09_004
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Ruler should be old and wise!
<WAIT>
}