//--------------------------
#SPEAKER_ID "N96"
@MES_npc_0001_001_KING_57_006
{
<NS>Excited Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I couldn't thank you then, so please allow me to do so now! You truly are a Hero King, Your Majesty!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_57_007
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Thank you! You're truly a Hero King!
<WAIT>
}