//--------------------------
#SPEAKER_ID "N1153"
@MES_npc_0004_001_PAGAN_023_01_005
{
<NS>Relieved Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But if someone like you became the ruler, well then I'd reevaluate a lot of things.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_023_01_006
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If you became queen, I'd rethink my worldview.
<WAIT>
}