//--------------------------
#SPEAKER_ID "N1519"
@MES_npc_TAROT_003_MOUNT
{
<NS>Dry Seer<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1263001_m1263">
As you can see, I'm a fortune teller. You must be the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1519"
@MES_npc_TAROT_Before_Vote_00_MOUNT
{
<NS>Dry Seer<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1263003_m1263">
Oh, if it isn't Her Highness. My apologies, but I've closed for the day.
<WAIT>
}