//--------------------------
#SPEAKER_ID "N300"
@MES_npc_0001_003_KING_SHOP_04_000
{
<NS>Masked Shopkeeper<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1383005_m1383">
...Young woman, have you some interest in this shop's wares?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N300"
@MES_npc_0001_003_KING_SHOP_04_009
{
<NS>Masked Shopkeeper<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1383005_m1383">
We meet again, young woman. We still have plenty of goods and... things... from across the land. Interested?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N300"
@MES_npc_0001_003_KING_SHOP_04_012
{
<NS>Masked Shopkeeper<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1383005_m1383">
Young woman. Might I interest you in our shop's wares? This is no ordinary mustari shop...
<WAIT>
}