//--------------------------
#SPEAKER_ID "N246"
@MES_npc_COMPETITION_000_KING
{
<NS>Hammy Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1295004_m1295">
Hmm? An elda? ...So long as you're a woman among women, it matters not!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N246"
@MES_npc_COMPETITION_004_KING
{
<NS>Hammy Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1295002_m1295">
Oho! Now here is a woman among women! Come, eat as much as you can!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N246"
@MES_npc_COMPETITION_006_KING
{
<NS>Hammy Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1295006_m1295">
You're doing great there, lassie! But there's more where that came from!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N246"
@MES_npc_COMPETITION_013_KING
{
<NS>Hammy Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1295009_m1295">
Wow, look at you go at it! Now here's a real woman's woman! I think I just may be falling for you!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N246"
@MES_npc_COMPETITION_019_KING
{
<NS>Hammy Shopkeep<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
My search... it must continue. I must discover a <i>new</i> woman amongst women... Now, go! Be off with you!
<WAIT>
}