//--------------------------
#SPEAKER_ID "N391"
@MES_npc_0002_001_CLIFF_08_003
{
<NS>Pompous Clergyman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1376007_m1376">
Did you hear? That girl who solved those kidnappings around town... Apparently, she was actually a <i>human</i>.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N398"
@MES_npc_0002_001_CLIFF_08_004
{
<NS>Whispering Noble<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If that's true, I wonder if Lady Joanna was just being used by her? The elda do bring calamity with them wherever they go...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N398"
@MES_npc_0002_001_CLIFF_08_005
{
<NS>Whispering Noble<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1317011_m1317">
But that girl is also the one who brought peace to the town. Just what are we meant to make of all this?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_001_CLIFF_08_007
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That girl, a human? I don't know what to believe.
<WAIT>
}