//--------------------------
#SPEAKER_ID "N83"
@MES_npc_0001_001_KING_43_030
{
<NS>Gate Guard<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
What do you think of the current queen? In my opinion... She's a victim of the last one.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N83"
@MES_npc_0001_001_KING_43_029
{
<NS>Gate Guard<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334014_m1334">
An elda... The queen tribe. Won't catch anyone badmouthing them now... Not openly, anyway.
<WAIT>
}