//--------------------------
#SPEAKER_ID "N405"
@MES_npc_QUEST_017_001_051
{
<NS>Gloomy Youth<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1329003_m1329">
You're... really the princess, aren't you? Crikey, and here I was, asking you to run my errands... You aren't here to throw me in the royal dungeon, are ye!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N405"
@MES_npc_QUEST_017_001_041
{
<NS>Gloomy Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If we've got to have a new ruler, I hope they'll at least be somebody who'll put a stop to these pushy nobles, ruinin' our lives over their whims...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N405"
@MES_npc_QUEST_017_001_042
{
<NS>Gloomy Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oi, do me a favour and put a stop to this kind of tyranny when you're queen.
<WAIT>
}