//--------------------------
#SPEAKER_ID "N298"
@MES_npc_0001_003_KING_SHOP_02_005
{
<NS>Paripus Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360004_m1360">
Good woman, you hungry at all? I'm proud of the food we sell...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N298"
@MES_npc_0001_003_KING_SHOP_02_013
{
<NS>Paripus Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360016_m1360">
Much obliged, my good woman! Come back again any time!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N298"
@MES_npc_0001_003_KING_SHOP_02_014
{
<NS>Paripus Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360001_m1360">
And here you are! I'm confident that this one's got the flavour! Come back any time, my good woman!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N298"
@MES_npc_0001_003_KING_SHOP_02_015_01
{
<NS>Paripus Shopkeep<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'm real sorry, my good woman, I know it's a long-awaited day and all, but I just can't give you any discounts. I'd be glad to serve you at regular price, though!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N298"
@MES_npc_0001_003_KING_SHOP_02_018
{
<NS>Paripus Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360004_m1360">
Oho, if it isn't my good woman! The world's in dire straits, I know, but I've been sellin' things as usual. I've even refined my craft a bit!
<WAIT>
}