//--------------------------
#SPEAKER_ID "N841"
@MES_npc_0003_002_OCEAN_01_002_01
{
<NS>Artisan<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347002_m1347">
Heyyy... You, elda girl there! You're that showboating candidate from the Exhibition, aren't ya?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_01_012
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
An elda impersonating royalty... You've got guts, girl.
<WAIT>
}