//--------------------------
#SPEAKER_ID "84"
@MES_npc_0003_001_OCEAN_06_006
{
<NS>Milo<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_84007_c084">
You're the young woman who dazzled at the Exhibition, aren't you? I enjoyed your... unique presentation tremendously.
<WAIT>
}
//--------------------------
#SPEAKER_ID "84"
@MES_npc_0003_001_OCEAN_06_002
{
<NS>Milo<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_84009_c084">
No need to be shy, dear girl. Finding yourself drawn to beautiful things is only natural, after all.
<WAIT>
}