//--------------------------
#SPEAKER_ID "96"
@MES_npc_0003_001_OCEAN_07_042
{
<NS>Lina<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_96011_c096">
...I've decided! We at Kayden Workshop will support you! For the future of gauntlet runners... become queen of this country!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_001_OCEAN_07_043
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
For the future of gauntlet runners... become queen of this country!
<WAIT>
}