//--------------------------
#SPEAKER_ID "N1532"
@MES_npc_0005_003_MOUNT_19_01_004_01
{
<NS>Weeping Nidia<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You? What can you do with those spindly little... Hold on. Are you... the princess, by chance?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1532"
@MES_npc_0005_003_MOUNT_19_01_004_02
{
<NS>Weeping Nidia<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
How rude! If you insist on being a degenerate little— Hold on. Aren't you... the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1532"
@MES_npc_0005_003_MOUNT_19_01_004_03
{
<NS>Weeping Nidia<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Yes. Yeees. This country still has its princess! What was I thinking? We can't give up hope yet!
<WAIT>
}