//--------------------------
#SPEAKER_ID "N1161"
@MES_npc_0004_001_PAGAN_031_01_006
{
<NS>Prison Guard<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1372004_m1372">
I can't believe I locked up our nation's princess. Maybe it's true that one of our people's faults is hard-headedness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_031_01_007
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Can't believe I locked up the princess...
<WAIT>
}