//--------------------------
#SPEAKER_ID "N1148"
@MES_npc_0004_001_PAGAN_018_01_006
{
<NS>Quiet Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1384001_m1384">
Is it true that you are the princess, then? Though, after all you have done, I see no reason to doubt you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_018_01_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
It is a strange feeling to see the princess right before my eyes...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1148"
@MES_npc_0004_001_PAGAN_018_01_000
{
<NS>Quiet Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1384001_m1384">
You have strange eyes, girl. It is as though they are looking not <i>at</i>, but <i>through</i>...
<WAIT>
}