//--------------------------
#SPEAKER_ID "N343"
@MES_npc_MAGIC_000_00_KING
{
<NS>Cautious Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1354004_m1354">
...Never expected Her Highness would become one of my customers. My merchandise isn't quite legal, so keep that in mind.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N343"
@MES_npc_MAGIC_003_01_KING
{
<NS>Cautious Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1354004_m1354">
Haha, to think Her Highness would grace us at this shop in particular. I offer a discount on Idlesday... That's not insulting, is it?
<WAIT>
}