//--------------------------
#SPEAKER_ID "N501"
@MES_npc_0002_002_CLIFF_18_000_00
{
<NS>Consoling Mother<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Worry not, honey. Blue skies are coming, don't you worry! ...You've heard about Her Highness the Princess who saved the town, haven't you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N501"
@MES_npc_0002_002_CLIFF_18_000_01
{
<NS>Consoling Mother<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She'll bring sunny days back to the town, and the whole country, too! We just need to do what we can until then. Okay, honey?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_18_001
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Let's trust Her Highness the Princess. We'll make do somehow...
<WAIT>
}