//--------------------------
#SPEAKER_ID "N135"
@MES_npc_ACTIVIST_027_KING
{
<NS>Activist Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1284001_m1284">
Oh, Ms. Elda Lady... We meet again. I still haven't managed to collect many donations for the cause...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N135"
@MES_npc_0001_002_KING_003_01_041
{
<NS>Activist Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That the new queen is elda—with people from every tribe in key positions—is also probably a major factor.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N135"
@MES_npc_0001_002_KING_003_01_044
{
<NS>Activist Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1284001_m1284">
Under the current queen, people are finally starting to question the discrimination against the "inferior" tribes.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_002_KING_003_01_046
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Despite the new queen, tribal friction remains.
<WAIT>
}