//--------------------------
#SPEAKER_ID "N1507"
@MES_npc_0005_003_MOUNT_07_01_001
{
<NS>Irritated Elder<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1317003_m1317">
How disgraceful... The only remaining candidate capable of challenging Louis is an elda who dares to claim she is the long lost princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1507"
@MES_npc_0005_003_MOUNT_07_01_001_00
{
<NS>Irritated Elder<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Nonetheless, with Saint Rella gone, I suppose we have no choice but to rely on her...
<WAIT>
}