//--------------------------
#SPEAKER_ID "N236"
@MES_npc_0001_003_KING_09_014_00
{
<NS>Comforting Lady<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It'll be all right. We saw it together, didn't we? Her Highness came in her gauntlet runner to save Grand Trad.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N236"
@MES_npc_0001_003_KING_09_014_01
{
<NS>Comforting Lady<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1368011_m1368">
Saint Rella believed in Her Highness the Princess, so I'm sure she'll take care of it for us. She just has to...
<WAIT>
}