//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_017
{
<NS>Nodding Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The winds out there rustle our hair too, you're sayin'... Speaking of that candidate, though—I hear she's an elda.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_018
{
<NS>Dodgy Rhoag<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358004_m1358">
Aye. Didn't believe it myself at first. Bringing in an elda? I thought there was no chance... But she did a smashin' job of it. Happy I was wrong on that one.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_044
{
<NS>Nodding Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...The candidate that resolved the incidents, the one you were talking about earlier? She's still pretty small-time... but she's giving it her all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_046
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That candidate that put an end to the incidents... she's giving it her all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_051
{
<NS>Encouraging Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Her Highness the Princess, the one we've been hearing rumours about—it's <HERO_NAME>, isn't it!? The saviour of our town!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_052
{
<NS>Agitated Rhoag<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358004_m1358">
To think she was holdin' on to a secret like that... nonetheless, eh, I'm certainly in no place to doubt 'im. She's trustworthy.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_054
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That candidate that put an end to the incidents... she's giving it her all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_057
{
<NS>Nodding Roussainte<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1315002_m1315">
Damn right... First off, why the hell is anyone in <i>this</i> city believing some ridiculous rumour about the princess being a monster?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_058
{
<NS>Nodding Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
We know better. We remember the young woman's name... and we remember her there with her comrades at the Visca Alba.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_059
{
<NS>Lamenting Clemar<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1319004_m1319">
Same goes for her kindness, saving a little town like this, not turnin' her back... It's her, all right—he's the one who's truly fit to be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_060
{
<NS>Grumpy Rhoag<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You got that right. I'll not speak an ill word against that young woman. Even if it makes an enemy of Louis... We stand by the lassie until the end, eh!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_062
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It's <HERO_NAME>, all right—she's the one who's truly fit to be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_043
{
<NS>Smiling Clemar<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1319004_m1319">
While we're on the subject... did ye all notice? That elda girl in the corner over there. Isn't that...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_004
{
<NS>Grumpy Rhoag<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Hah, exactly. There could be nobody left here by the time the next ruler decided.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_20_042
{
<NS>Nodding Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If you live in this country, it's relevant to you. We should all think hard on who the next ruler should be.
<WAIT>
}