//--------------------------
#SPEAKER_ID "N1093"
@MES_npc_0013_002_BAR_01_013
{
<NS>Curt Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1320005_m1320">
Her Highness the Princess... Apologies. I don't care who you are. I deserve to enjoy my food in peace.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0013_002_BAR_01_015
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Princess or not, no one disrupts the peace of a dining experience.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1093"
@MES_npc_0013_002_BAR_01_019
{
<NS>Curt Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Does Her Highness the Princess understand how invaluable it is...?
<WAIT>
}