//--------------------------
#SPEAKER_ID "N400"
@MES_npc_0002_001_CLIFF_09_007
{
<NS>Drunk Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Eh, girly... Tell me... Is it really true? Hardly believe she was just... evil, right down to the core...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N400"
@MES_npc_0002_001_CLIFF_09_013
{
<NS>Drunk Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1337005_m1337">
Now I'm not boastin' or nothin', but can't say I was surprised. When we heard ye was the princess, I mean.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N400"
@MES_npc_0002_001_CLIFF_09_002
{
<NS>Drunk Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1337005_m1337">
Say, girly... somethin' different about you? Or 'ave I got a wee bit bladdered and me eyes ain't workin'...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_001_CLIFF_09_005
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Odd rumours goin' round about ye, girly... But we dinnae care!
<WAIT>
}