//--------------------------
#SPEAKER_ID "N119"
@MES_npc_0001_002_KING_09_006
{
<NS>Bandit<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Must be damn skilled. Welp, we'll probably never run into her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N120"
@MES_npc_0001_002_KING_09_015_01
{
<NS>Bandit's Buddy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334012_m1334">
...There ain't a ruler that exists who takes kindly to thieves. No matter what the circumstances.
<WAIT>
}