//--------------------------
#SPEAKER_ID "N1517"
@MES_npc_0005_003_MOUNT_17_01_000
{
<NS>Pleading Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328001_m1328">
You have to believe me! That princess is the real deal—her heart is pure! Upon my honour, she won't abandon you, no matter your race!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1515"
@MES_npc_0005_003_MOUNT_17_01_000_00
{
<NS>Enraged Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That's as may be, but you won't catch me sinkin' with the rest of ya when her ship goes down! Sorry mate, but I'm backin' the more likely winner.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_003_MOUNT_17_01_001
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I might be willing to side with the princess, but it'd take a miracle...
<WAIT>
}