//--------------------------
#SPEAKER_ID "85"
@MES_npc_0005_003_MOUNT_18_01_004_00
{
<NS>Loveless<NE>
<BUSTUP 5 0 0>
<VOICE "v_co_85016_c085">
She's here! That damn black-hearted princess! You might think you're gettin' away with your wicked schemes...
<WAIT>
}
//--------------------------
#SPEAKER_ID "85"
@MES_npc_0005_003_MOUNT_18_01_004_01
{
<NS>Loveless<NE>
<BUSTUP 5 0 0>
<VOICE "v_co_85016_c085">
She's here! That black-hearted human princess! You might think you're gettin' away with your wicked schemes...
<WAIT>
}
//--------------------------
#SPEAKER_ID "85"
@MES_npc_0005_003_MOUNT_18_01_007
{
<NS>Loveless<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
On the other hand, I think you'd be a good queen. So go on, do us all a favour and take care of the loonies like Milo, would'ya?
<WAIT>
}