//--------------------------
#SPEAKER_ID "N1661"
@MES_npc_0015_002_BAR_01_01_009
{
<NS>Mustari Tavernkeep<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To speak frankly, I think what you've accomplished so far is amazing. Even without the title of a princess, you did well to climb out of obscurity and achieve your current notoriety...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1661"
@MES_npc_0015_002_BAR_01_01_010
{
<NS>Mustari Tavernkeep<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It's just... I am still a mustari at heart. To think that you might be queen... I'm hesitant to allow myself that much optimism. This is how I feel, truly.
<WAIT>
}