//--------------------------
#SPEAKER_ID "N333"
@MES_npc_0011_001_INN_02_026
{
<NS>Paripus Regular<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327011_m1327">
Y'know, sometimes I think we're all daft to believe you. The scamp who lodged at the Hushed Honeybee was a princess this whole time?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0011_001_INN_02_029
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Princess or not, I'm rooting for you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N333"
@MES_npc_0011_001_INN_02_016
{
<NS>Paripus Regular<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Anyway, I heard... You're part of the Tournament, aren't ya? An elda queen... Good luck with that, mate.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0011_001_INN_02_018
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
An elda queen...
Good luck.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N333"
@MES_npc_0011_001_INN_02_024
{
<NS>Paripus Regular<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Thanks to you, it feels like the Tournament actually matters to folks like me. It's startin' to settle in that we may actually help decide who the next ruler be.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N333"
@MES_npc_0011_001_INN_02_030
{
<NS>Paripus Regular<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327005_m1327">
It's finally time for you to settle the score with Louis... The ruler all but decided now, I suppose.
<WAIT>
}