//--------------------------
#SPEAKER_ID "N426"
@MES_npc_0002_001_CLIFF_17_012
{
<NS>Runner-Gazer<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360001_m1360">
Haha! Every time I hear the rumour I laugh so much I almost piss meself. Y'know, the story going 'round about you being... <i>Princess</i>.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N426"
@MES_npc_0002_001_CLIFF_17_015
{
<NS>Runner-Gazer<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360004_m1360">
Bardon really brought quite the rare bird to town, didn't he? A self-proclaimed princess, who's an elda rumoured to be human...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N426"
@MES_npc_0002_001_CLIFF_17_005
{
<NS>Runner-Gazer<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Maybe you've got a bit of the daredevil in you... Damn good show, Ms. Candidate. And thanks to it, they're saying the kidnappings were resolved.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N426"
@MES_npc_0002_001_CLIFF_17_010
{
<NS>Runner-Gazer<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I rather like seeing you in town like this every so often. I'm pulling for you, future queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_001_CLIFF_17_011
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I'm pulling for you, future queen!
<WAIT>
}