//--------------------------
#SPEAKER_ID "N33"
@MES_npc_0001_001_KING_004_01_071
{
<NS>Chatty Elder<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
A sincere young woman loved by fairies finds happiness... Folktales aren't just tired, old stories for dreamers...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N33"
@MES_npc_0001_001_KING_004_01_074
{
<NS>Chatty Elder<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1277001_m1277">
Why, if it isn't... You're the young woman with the fairy in tow I used to see around here, aren't you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N33"
@MES_npc_0001_001_KING_004_01_075
{
<NS>Chatty Elder<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Ah, yes. Now that I mention it, I do recall people saying the new queen had a fairy in her retinue... I can't believe it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_004_01_076
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I recall hearing the new queen had a fairy...
<WAIT>
}