//--------------------------
#SPEAKER_ID "N25"
@MES_npc_TAROT_001_KING
{
<NS>Genial Seer<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Good evening, young woman. I am a fortune teller. Please come to visit me, if ever you wish to know which way the wind blows.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N25"
@MES_npc_TAROT_003_KING
{
<NS>Genial Seer<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1260001_m1260">
Young woman... How about a fortune? I can tell you what the weather will be for the next two days.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N25"
@MES_npc_TAROT_006_KING
{
<NS>Genial Seer<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oh, it seems you don't have enough money. I do not share my gifts for free, young woman.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N25"
@MES_npc_TAROT_012_KING
{
<NS>Genial Seer<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1260001_m1260">
Oh, my! Has Her Majesty come to have her fortune told? Hoho. I jest, of course.
<WAIT>
}