//--------------------------
#SPEAKER_ID "N17"
@MES_npc_0001_001_KING_10_013_01
{
<NS>Forlorn Guardsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I suppose that's just how this job goes. Yet I wish we could get a ruler that actually gave a damn about her soldiers...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_10_014
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I hope the next ruler treats her soldiers better...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N17"
@MES_npc_0001_001_KING_10_010
{
<NS>Forlorn Guardsman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369010_m1369">
The talk around these parts has grown deranged... More and more people are openly talking about how they're going to put "the infidel claiming to be the princess" to the gallows.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N17"
@MES_npc_0001_001_KING_10_013_00
{
<NS>Forlorn Guardsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
From a lowly guard's perspective, it doesn't matter which one is ruler. We're all expendable to them.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N17"
@MES_npc_0001_001_KING_10_017_00
{
<NS>Forlorn Guardsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Please... Stop Louis. If you can't, this country will fall apart even before a new ruler can be decided...
<WAIT>
}