//--------------------------
#SPEAKER_ID "N721"
@MES_npc_0012_002_BAR_02_02_006
{
<NS>Drunk Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If someone other than His Eminence Forden were to be ruler, I hope it'd be someone like you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0012_002_BAR_02_02_007
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'd like someone like you to be ruler...
<WAIT>
}