//--------------------------
#SPEAKER_ID "N868"
@MES_npc_QUEST_064_001_082
{
<NS>Brewer<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333004_m1333">
Hah, don't worry. When you become queen, I'll raise this cup in your honour!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N868"
@MES_npc_QUEST_064_001_085
{
<NS>Brewer<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1333004_m1333">
When you become queen, I'll raise a toast in your honour—with the cup you brought me! Give 'em hell, kid!
<WAIT>
}