//--------------------------
#SPEAKER_ID "N414"
@MES_npc_BUNGEE_001
{
<NS>Spirited Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To take the plunge, you must first <i>believe in yourself</i>! You will return a braver woman indeed! Come now, test the strength of your will!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N414"
@MES_npc_BUNGEE_024
{
<NS>Spirited Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Ah, I'm just joking, lassie. There's something special about you. Hope you'll come back and show us all what you've got.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N414"
@MES_npc_BUNGEE_025
{
<NS>Spirited Youth<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1299010_m1299">
The brave lass returns! I'm sorry, but that was my most dangerous rope.
<WAIT>
}