//--------------------------
#SPEAKER_ID "N1150"
@MES_npc_0004_001_PAGAN_020_01_000
{
<NS>Amicable Girl<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355005_m1355">
Everyone on the island seems much happier. Is that because of your power, miss?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1150"
@MES_npc_0004_001_PAGAN_020_01_004
{
<NS>Amicable Girl<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355005_m1355">
...Wow. So you were the princess all along!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1150"
@MES_npc_0004_001_PAGAN_020_01_005
{
<NS>Amicable Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Miss, do you like this island? I hope you do!
<WAIT>
}