//--------------------------
#SPEAKER_ID "N112"
@MES_npc_0001_002_KING_02_013
{
<NS>Beggar<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1362001_m1362">
...Ho now! The princess coming out of the Honeybee? What's led to this occasion?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N112"
@MES_npc_0001_002_KING_02_015
{
<NS>Beggar Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1362001_m1362">
Haha, still can't believe it, no matter how many times I see it—the queen walkin' out of the Honeybee...
<WAIT>
}