//--------------------------
#SPEAKER_ID "0"
@MES_npc_0006_005_FOREST_005_01_007
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
She survived two assassination attempts? Incredible...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1825"
@MES_npc_0006_005_FOREST_005_01_008
{
<NS>Unlikely Survivor<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1381003_m1381">
That figure who just darted by...!? Is he not the one who came to murder the princess!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0006_005_FOREST_005_01_010
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
The princess's assassin ran off, towards the stairs!
<WAIT>
}