//--------------------------
#SPEAKER_ID "N349"
@MES_npc_0011_007_BARRACK_04_005
{
<NS>Recruiter on Break<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
They think they have a shot at becoming ruler... Heh, what a bunch of jokers.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N349"
@MES_npc_0011_007_BARRACK_04_008
{
<NS>Recruiter on Break<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Blimey. An elda trying to become queen? It's the end of days.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N349"
@MES_npc_0011_007_BARRACK_04_012
{
<NS>Recruiter on Break<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Back then I thought it was daft that an elda could aspire to be queen... But the way the world's going, you can never be sure of anything anymore.
<WAIT>
}