//--------------------------
#SPEAKER_ID "N5"
@MES_npc_0001_001_KING_03_019_01
{
<NS>Mercenary Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
B-But she saved that town from her, didn't she? We can't be sure that she's a bad person...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N5"
@MES_npc_0001_001_KING_03_015
{
<NS>Mercenary Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1381005_m1381">
What do you think of that young man? The one who says she's the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N6"
@MES_npc_0001_001_KING_03_016
{
<NS>Portly Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...She's better than Louis, though I'm not sure that matters much anymore. The Church has collapsed, so it really feels like the end of days.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_03_018
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
That "princess"... I kind of like her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N5"
@MES_npc_0001_001_KING_03_021
{
<NS>Mercenary Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1381005_m1381">
So Louis and the princess are going to tussle at the Grand Cathedral... What do you think will happen?
<WAIT>
}