//--------------------------
#SPEAKER_ID "N190"
@MES_npc_0001_002_KING_39_004
{
<NS>Weapon Shopkeeper<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It's reassuring to hear that from the queen herself... Still, nothing goes quite the way you expect to, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N190"
@MES_npc_0001_002_KING_39_000
{
<NS>Weapon Shopkeeper<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1239008_m1239">
Seems rumours of the queen running about in Sunshade Row were true. Haha, I've no intention of prying, now.
<WAIT>
}