//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_002_KING_12_003
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Can't believe there's an elda here... Ugh, no! She's looking over here!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N116"
@MES_npc_0001_002_KING_12_015
{
<NS>Young Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328002_m1328">
Just as Forden's goose seems cooked, an elda princess has come swooping in.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N117"
@MES_npc_0001_002_KING_12_016
{
<NS>Youth's Friend<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It's unbelievable: a lesser tribe member daring to call herself princess? Ugh... So Louis has it, then, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N116"
@MES_npc_0001_002_KING_12_023_02
{
<NS>Young Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The queen held it together this year, but who knows if she'll last another?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N116"
@MES_npc_0001_002_KING_12_008
{
<NS>Young Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1328004_m1328">
Fancy a wager on who'll become the next ruler? I'm going all or nothing on Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N116"
@MES_npc_0001_002_KING_12_017
{
<NS>Young Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To that point, might you recall a certain wager between you and I over who'll become ruler? Behold... my glorious victory.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N117"
@MES_npc_0001_002_KING_12_021_00
{
<NS>Youth's Friend<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...No, things got quite violent in Montario, didn't they? And to think such a fellow is to be ruler after all this time...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N117"
@MES_npc_0001_002_KING_12_023_01
{
<NS>Youth's Friend<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327003_m1327">
They're saying those disgusting humans are our <i>ancestors</i>! Nothing but crazy stories since the new queen took the throne.
<WAIT>
}