//--------------------------
#SPEAKER_ID "N1542"
@MES_npc_QUEST_120_001_000
{
<NS>Ornamented Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332005_m1332">
That outfit... Aren't you the candidate who claims to be the princess? If you are possessed of princessly skills, then I have a task for you...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1542"
@MES_npc_QUEST_120_001_004
{
<NS>Ornamented Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332012_m1332">
That's why I figured I might enlist someone so <i>princessly</i> in my stead. Of course I'll reward you handsomely, and you're sure to find other treasure there, too. What say you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1542"
@MES_npc_QUEST_120_001_044
{
<NS>Ornamented Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332006_m1332">
If you do, I hope you'll come show it to me. In the meantime, I'm in your corner, O future queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1542"
@MES_npc_QUEST_120_001_045
{
<NS>Ornamented Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1332005_m1332">
If you become queen, perhaps the sword you have now will become legendary.
<WAIT>
}