//--------------------------
#SPEAKER_ID "N288"
@MES_npc_0001_003_KING_37_009
{
<NS>Merchant on Break<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I want the next ruler to do something that'll help us make money. There was that bloke Roger, yeah? Someone like him will be good, I reckon.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_37_010
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
The next ruler help us make money...
<WAIT>
}