//--------------------------
#SPEAKER_ID "N1667"
@MES_npc_NEWS_MOUNT_Shop_003
{
<NS>Informed Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
When the saint died, he drowned his sorrows in drink. "She couldn't have killed the princess, it's all a lie," he bitterly wailed.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1667"
@MES_npc_NEWS_MOUNT_tower_002_07
{
<NS>Informed Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1378004_m1378">
Don't you intend to become queen? Well then, you can't exactly afford to lose here, can you? Give it your best effort.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1667"
@MES_npc_NEWS_MOUNT_food_000
{
<NS>Informed Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1378005_m1378">
Hmm. A queen candidate like you cooks as well? There's a lot of shops stocked to the ceiling for Saint's Day.
<WAIT>
}