//--------------------------
#SPEAKER_ID "95"
@MES_npc_0003_004_OCEAN_03_015
{
<NS>Roger<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But in the end, it all feels a bit ridiculous—the next ruler going to be chosen based on how they perform in pointless hunts and empty rituals, not the content of their character.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_004_OCEAN_03_017
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Deciding the next ruler through sport... Something feels wrong.
<WAIT>
}