//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_24_079
{
<NS>Ishkia Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1314002_m1314">
There's to be a duel between him and the young girl claiming to be the princess. We can only hope there won't be another tragedy like the one at the royal funeral.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_24_083
{
<NS>Irritated Rioter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358002_m1358">
Hey, ain't ya that town crier, Batlin? Mighty strange how you seemed to favour that princess at the Tournament...
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_npc_0001_003_KING_24_087
{
<NS>Batlin<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_46228_c047">
But let me say this as a citizen of this country: the princess is not your enemy by any means.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_24_088
{
<NS>Irked Louis Supporter<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1367002_m1367">
Any enemy of Louis is an enemy of ours! You're just working for the princess, aren't you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_24_092
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Sanctist cheat! Take your princess and go!
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_npc_0001_003_KING_24_093
{
<NS>Batlin<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_46223_c047">
She never abandons people in need, and she doesn't shy away from people in the country's underbelly either. The princess that I know has always been that way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_24_099
{
<NS>Shouting Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I also support the princess, just like Batlin. I'm tired of being scared and staying silent!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_24_021
{
<NS>Clemar Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326012_m1326">
They say anyone can be ruler, but everyone knows it'll ultimately come down to Louis or Forden.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_24_030
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
They say anyone can be ruler, but...
<WAIT>
}