//--------------------------
#SPEAKER_ID "11"
@MES_npc_0006_004_FOREST_004_01_005
{
<NS>Gallica<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
Don't worry, we're all okay, and the princess is safe, too. We'll take care of the bandit.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1804"
@MES_npc_0006_004_FOREST_004_01_007
{
<NS>Elda Guard<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Wait, what? The princess too?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0006_004_FOREST_004_01_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
The princess is safe too...?
<WAIT>
}