//--------------------------
#SPEAKER_ID "N794"
@MES_npc_QUEST_062_002_045
{
<NS>Pompous Noble<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Yes, a thrilling tale, well-told! I applaud you, young lady. Thus have you saved me from boredom.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N794"
@MES_npc_QUEST_062_002_060
{
<NS>Pompous Noble<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1314005_m1314">
The princess, eh... Things are finally getting interesting. Keep it up, and show me just what you're capable of!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N794"
@MES_npc_QUEST_062_002_013_00
{
<NS>Pompous Noble<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1314005_m1314">
Ah, you're the candidate who offered up the head of a noble at the Exhibition. You've got fine tastes, girl. I'll hear what you have to say.
<WAIT>
}