//--------------------------
#SPEAKER_ID "N1821"
@MES_npc_0006_005_FOREST_001_01_000
{
<NS>Faith Leader<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369003_m1369">
To be completely honest, there are those within the sanctum who think ill of both Her Highness and the Resistance.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1821"
@MES_npc_0006_005_FOREST_001_01_001
{
<NS>Faith Leader<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But life is priceless. For her to have died in such a way, at so tender an age...
<WAIT>
}