//--------------------------
#SPEAKER_ID "N121"
@MES_npc_0001_002_KING_10_007
{
<NS>Anxious Guardsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
How can you just go around claiming to be the princess!? Isn't there anyone decent 'round here!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N121"
@MES_npc_0001_002_KING_10_008
{
<NS>Anxious Guardsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Strange thieves, a swindler, now a fake princess... Bloody hell! I feel like I'm goin' nuts!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N121"
@MES_npc_0001_002_KING_10_014_00
{
<NS>Anxious Guardsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Right, Your Highness? Princess? That's what you are, aren't you!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N121"
@MES_npc_0001_002_KING_10_016_00
{
<NS>Anxious Guard<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It may be better than it was before, but this is still Sunshade Row. It's no place for a queen, Your Majesty.
<WAIT>
}