//--------------------------
#SPEAKER_ID "N118"
@MES_npc_0001_002_KING_06_015
{
<NS>Dejected Pauper<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358003_m1358">
Whoever ends up as ruler... They wouldn't know a thing about me... wouldn't even look my way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_002_KING_06_016
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
No matter who becomes ruler, they still won't spare me a glance...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N118"
@MES_npc_0001_002_KING_06_019
{
<NS>Dejected Pauper<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358002_m1358">
You might be queen... but nothing'll change.
<WAIT>
}