//--------------------------
#SPEAKER_ID "N930"
@MES_npc_0003_003_OCEAN_06_007
{
<NS>Subcontractor<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That's on account of some eldan lass who defeated the monster that was causing it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N929"
@MES_npc_0003_003_OCEAN_06_008
{
<NS>Shipwright Magnate<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You mean the one everyone's talking about? Well, colour me impressed. Maybe she's a strong as the rumours say.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_003_OCEAN_06_011
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Rumours are an eldan lass defeated the monster haunting the seas.
<WAIT>
}