//--------------------------
#SPEAKER_ID "11"
@MES_npc_0006_005_FOREST_007_01_000
{
<NS>Gallica<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_11522_c011">
Russell, the princess is...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0006_005_FOREST_007_01_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
She sacrificed herself for us,
despite our failure?
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_npc_0006_005_FOREST_007_01_003_00
{
<NS>Russell<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
How could this be!? Her Highness... resurrected?
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_npc_0006_005_FOREST_007_01_005
{
<NS>Russell<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To think she'd been alive and well, residing in a body composed from magla particles...
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_npc_0006_005_FOREST_007_01_006
{
<NS>Russell<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She furthered her goals by storing her mind within another vessel... 'tis reminiscent of His Majesty's royal magic!
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_npc_0006_005_FOREST_007_01_008_00
{
<NS>Russell<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Of course. And with the princess only just having woken... That accursed assassin went racing out of the cave.
<WAIT>
}