//--------------------------
#SPEAKER_ID "N238"
@MES_npc_0001_003_KING_11_011_00
{
<NS>Nodding Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Yeah, that elda bloke who nabbed that sanctoress is way better. She seems like a better fit to be Louis's underling.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N238"
@MES_npc_0001_003_KING_11_021
{
<NS>Nodding Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If not Louis, then how about that elda lass? She didn't do half bad at the Exhibition of the Brave.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N237"
@MES_npc_0001_003_KING_11_013
{
<NS>Excited Youth<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1329002_m1329">
What's gonna happen to this town if that "princess" ends up queen? Way I see it, Santicism'll rise right back up again.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N238"
@MES_npc_0001_003_KING_11_013_00
{
<NS>Nodding Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Yeah... I had hopes for that kid when they executed the sanctoress, but she was a royal in the end. Disappointing, really.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N238"
@MES_npc_0001_003_KING_11_017_01
{
<NS>Nodding Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Queen or not, she's not that old. I'm sure she's doing her best, but in the end, she's just the old king's daughter. I don't expect very much of her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N238"
@MES_npc_0001_003_KING_11_017_00
{
<NS>Nodding Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'd like to think that the new queen already knows... But frankly, I don't think much has changed in the last year.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_11_018
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Don't get your hopes up about the queen.
<WAIT>
}