//--------------------------
#SPEAKER_ID "N262"
@MES_npc_0001_003_KING_22_016
{
<NS>Sighing Soldier<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1375002_m1375">
The person who destroys the country and the human princess who can't protect it... We have to choose one of the two to be ruler?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N262"
@MES_npc_0001_003_KING_22_010_00
{
<NS>Sighing Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...Whoops. You heard nothing, girl.
<WAIT>
}