//--------------------------
#SPEAKER_ID "N894"
@MES_npc_QUEST_040_001_010
{
<NS>Craftsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If only the candidate who captured the nation's imagination at the Exhibition, already renowned for her charity, would oh-so-serendipitously find me in my moment of need...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N894"
@MES_npc_QUEST_040_001_019
{
<NS>Craftsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The only one who can save me now is the young hero who captured the kingdom's imagination at the Exhibition of the Brave... If only she was here...! Ahem.
<WAIT>
}