//--------------------------
#SPEAKER_ID "N72"
@MES_npc_0001_001_KING_38_023
{
<NS>Grumbling Nidia<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1364001_m1364">
So you're an elda, but you're also the princess... Hm, I like that. Sounds like something that would happen in the pages of a storybook.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_38_025
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
An elda was the princess all along...
<WAIT>
}