//--------------------------
#SPEAKER_ID "N472"
@MES_npc_0002_002_CLIFF_16_016
{
<NS>Suffering Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
My... I've known about you for a while, and I must say, you really are a gallant young woman.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N472"
@MES_npc_0002_002_CLIFF_16_017
{
<NS>Suffering Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Of course, I hope you become queen. And not just me... everyone in this city does, too.
<WAIT>
}