//--------------------------
#SPEAKER_ID "N336"
@MES_npc_0011_002_BAR_01_01_015
{
<NS>Curt Owner<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Don't know why you'd come to me to ask that... Huh? Nobody else would talk to you? Ah, for goodness sake, lass...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N336"
@MES_npc_0011_002_BAR_01_01_019
{
<NS>Curt Owner<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1337005_m1337">
Ah... the elda lass. Again, I don't mind serving you a hot meal...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N336"
@MES_npc_0011_002_BAR_01_01_035
{
<NS>Curt Owner<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1337005_m1337">
Well, well... If it isn't Her Highness. Aren't you worried about being seen in a place like this?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N336"
@MES_npc_0011_002_BAR_01_01_048
{
<NS>Curt Owner<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1337002_m1337">
Haha, for whatever reason, customers often come to me for advice... but I never thought I'd be talking candidly with a princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N336"
@MES_npc_0011_002_BAR_01_01_027
{
<NS>Curt Owner<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'm not saying it's <i>not</i> a good idea... but who would've thought, an elda, with aspirations of being queen?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0011_002_BAR_01_01_037_00 SEL 0
{
Is Louis's following growing?<COLOR -1>
How's the situation in Grand Trad?<COLOR -1>
Am I fit to be queen...?<COLOR -1>
It's nothing.
<WAIT>
}