//--------------------------
#SPEAKER_ID "11"
@MES_BARRACK_Q63_010_OCEAN
{
<NS>Gallica<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_11453_c011">
Ugh... Even as the princess you're still criticised. In that case, we can't refuse this one.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_BARRACK_Q14_025_OCEAN
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_11086_c011">
Yeah. Take a good look at her now because she's about to become even more famous!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N344"
@MES_BARRACK_Q14_026_OCEAN
{
<NS>Recruiter Dispatcher<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I suppose you don't proclaim yourself the princess for nothing. I look forward to seeing more of your work.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_BARRACK_Q134_038_OCEAN
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11047_c011">
But in the end, that soldier did eventually decide to support us. I'm sure it'll be easier to resolve this problem once you're queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N344"
@MES_BARRACK_Q80_045_OCEAN
{
<NS>Recruiter Dispatcher<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You're not only strong, but willing to put your life on the line for others... I believe those are qualities befitting a true queen.
<WAIT>
}