//--------------------------
#SPEAKER_ID "N7"
@MES_npc_0003_001_OCEAN_11_005
{
<NS>Gossipy Noble<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1312003_m1312">
A girl claiming to be the lost princess and Louis have forced themselves to the top of the race... Just what will become of the Tournament?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N7"
@MES_npc_0003_001_OCEAN_11_003
{
<NS>Gossipy Noble<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1312005_m1312">
Did you hear? The story about a girl who defeated the monster in the eastern sea...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_001_OCEAN_11_009
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Did you hear about the girl who defeated the sea monster?
<WAIT>
}