//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_000
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355019_m1355">
Uh, um... P-Please, Miss, make me your apprentice!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_003
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So I want to be like you, Miss. Please let me be your apprentice!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_035
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355004_m1355">
You're really nice, Miss! Then, will you bring me a flower?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_npc_QUEST_068_001_037
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_11048_c011">
You can become <HERO_NAME>'s supporter in return! Basically, you just gotta cheer her on to help her become queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_043
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oh, really... Right, I guess you must be really really busy, miss. But if you have time, I'm always waiting!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_051
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Thanks, miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_npc_QUEST_068_001_058
{
<NS>Gallica<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_11430_c011">
Hooold on there, kid. You really think she should confess to your friend in your place? What if your friend falls in love with her instead?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_075
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355001_m1355">
I'm sure this flower will make my friend happy. Thanks, miss.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_077
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355019_m1355">
You've been doing great lately, right, miss? Everyone says you're amazing!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_079
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355002_m1355">
Everything's getting really really weird around here. But it's all right! We know you can fix this, miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_080
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
My friend, my mum, my dad and everyone in the neighbourhood are cheering you on, miss! You can do it!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N945"
@MES_npc_QUEST_068_001_084
{
<NS>Kindly Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355003_m1355">
You're a liar, miss. You said you'd bring me a flower...
<WAIT>
}