//--------------------------
#SPEAKER_ID "N153"
@MES_npc_0001_002_KING_20_000
{
<NS>Curt Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358005_m1358">
What're you doing here? This ain't a place for a girl of your stature...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N153"
@MES_npc_0001_002_KING_20_008
{
<NS>Curt Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358006_m1358">
Seen you a lot lately, elda lass. Thinkin' you'll stay a while?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N153"
@MES_npc_0001_002_KING_20_026
{
<NS>Curt Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The first time I saw you was the night before the royal funeral, if I recall. No offense, but you didn't exactly look like a princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N153"
@MES_npc_0001_002_KING_20_029
{
<NS>Curt Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358006_m1358">
I see you a lot lately, elda lass. You be careful. Life 'round here's surprisingly fleeting.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N153"
@MES_npc_0001_002_KING_20_033
{
<NS>Curt Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358006_m1358">
Oi, elda lass. Goin' somewhere?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N153"
@MES_npc_0001_002_KING_20_025
{
<NS>Curt Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1358004_m1358">
...Oi, oi. Here's a mug I haven't forgotten. You're the queen now, ain't ya?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N153"
@MES_npc_0001_002_KING_20_027_04
{
<NS>Curt Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You're a good bloke, and I think you'll make a fine queen, but don't think you can just spruce the place up a bit and that'll solve the problem.
<WAIT>
}