//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_004
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
And so... Wait, hold on. You don't have horns either, huh Miss?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_006
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...Huh? You don't have horns either, Miss?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_002_KING_01_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
You're not clemar, Miss...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_027
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340005_m1340">
El-dah, you're the princess...? Wasn't the old king a clemar?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_015
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340005_m1340">
I bet the next ruler gonna punish the bad tribes.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_025
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340002_m1340">
El-dah, you wanna be queen? You can't. 'Cause everyone hates el-dahs.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_025_00
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...Everyone says bad things about you, so why do you wanna be their queen anyway?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_002_KING_01_026
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
There's no way an el-dah can be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_029_01
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So, if you beat Louis, it's okay if you become queen, even if you're el-dah.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_031
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340004_m1340">
Whoa, el-dah! You really became queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N111"
@MES_npc_0001_002_KING_01_031_00
{
<NS>Playing Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Queen! Hey queen! Oh <i>kiiiiing</i>! Ahaha!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_002_KING_01_032
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Hey queen! You're the <i>kiiiiing</i>! Ahaha!
<WAIT>
}