//--------------------------
#SPEAKER_ID "N1824"
@MES_npc_0006_005_FOREST_004_01_001
{
<NS>Wizened Attendant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Perhaps that's reflected in the current state of affairs... That child is royalty, yet her life has been defined by tragedy beyond anything that I have experienced.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1824"
@MES_npc_0006_005_FOREST_004_01_003
{
<NS>Wizened Attendant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To look upon a mere girl such as she and revile her... Their souls are truly cursed.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1824"
@MES_npc_0006_005_FOREST_004_01_005
{
<NS>Wizened Attendant<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1356002_m1356">
Well, I'll be... Am I correct in presuming that you are the princess now?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1824"
@MES_npc_0006_005_FOREST_004_01_007
{
<NS>Wizened Attendant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To think that you are the princess's other half... Ah, fate is a fickle one...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0006_005_FOREST_004_01_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
That you could be the princess's other half...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1824"
@MES_npc_0006_005_FOREST_004_01_006
{
<NS>Wizened Attendant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I hadn't heard of any elda girl joining the Resistance's ranks and going out on missions, so seeing you took me by surprise.
<WAIT>
}