//--------------------------
#SPEAKER_ID "N941"
@MES_npc_TOBAKU_023
{
<NS>Gambling Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1335004_m1335">
Seems you've lost this time, but chin up lass, everyone has days like this. Don't beat yourself up.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N941"
@MES_npc_TOBAKU_029
{
<NS>Gambling Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1335005_m1335">
Welly, welly, well... If it isn't the famed "princess". Any particular reason you'd grace us with your presence today, m'lady?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N941"
@MES_npc_TOBAKU_014
{
<NS>Gambling Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But don't worry, I'll still be here if you decide to come after that. And may Lady Luck be a gentle mistress, girl.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N941"
@MES_npc_TOBAKU_026
{
<NS>Gambling Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oi, you don't have enough money. This isn't a charity, girl.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N941"
@MES_npc_TOBAKU_003
{
<NS>Gambling Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Nice one... Besides, if your goal is to be queen, you've gotta take some risks.
<WAIT>
}