//--------------------------
#SPEAKER_ID "N27"
@MES_npc_0001_001_KING_15_021
{
<NS>Menacing Soldier<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1374003_m1374">
Elda— No, wait, that's not what I meant. Y-Y-Your Highness the Princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_15_023
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Y-Y-Your Highness the Princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N27"
@MES_npc_0001_001_KING_15_024
{
<NS>Menacing Soldier<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1374002_m1374">
Tch. I knew it was all rubbish when they said you were the princess. Damned human... The people won't tolerate your tricks for long.
<WAIT>
}