//--------------------------
#SPEAKER_ID "87"
@MES_npc_0003_002_OCEAN_08_030
{
<NS>Goddard<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
There <i>are</i> kind and principled people among today's youth, too, aren't there. Young princess... I wish you the best of luck.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_08_032
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Young princess... You have my respect.
<WAIT>
}
//--------------------------
#SPEAKER_ID "87"
@MES_npc_0003_002_OCEAN_08_013
{
<NS>Goddard<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_87003_c087">
You didn't think the Sanctoress would walk away safe, did you? Of all the short-sighted, immature... You're far too young to be queen!
<WAIT>
}