//--------------------------
#SPEAKER_ID "N1172"
@MES_npc_0004_001_PAGAN_042_01_005
{
<NS>Fisherman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If possible, I'd like to sell my fish to the mainland, too. I hope if you become queen, you make trade easier.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_042_01_006
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I'm thinking if you become queen, we'll have free trade.
<WAIT>
}