//--------------------------
#SPEAKER_ID "N48"
@MES_npc_0001_001_KING_27_000
{
<NS>Happy Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1320004_m1320">
Haha! The weather's absolutely gorgeous today! And look what we have here... There's the princess, just over there!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N49"
@MES_npc_0001_001_KING_27_000_00
{
<NS>Woman in Stitches<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Aww, isn't she just adorable... Louis will kill you soon enough, though. Gyahaha!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_27_001
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
That princess is going to die soon enough! Gyahaha!
<WAIT>
}