//--------------------------
#SPEAKER_ID "N1185"
@MES_npc_0004_001_PAGAN_052_01_000
{
<NS>Clumsy Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340005_m1340">
Hey, miss... You saved our island, right?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1185"
@MES_npc_0004_001_PAGAN_052_01_002
{
<NS>Clumsy Boy<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340004_m1340">
Okay, I'm gonna go play now... Thanks, miss elda! Bye bye!
<WAIT>
}