//--------------------------
#SPEAKER_ID "N23"
@MES_npc_0001_001_KING_14_014_00
{
<NS>Attentive Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That's if we're to believe Saint Rella's words... I still doubt if that "princess" is really capable of taking down someone like Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_14_015
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Can that "princess" really go head to head with Louis...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N22"
@MES_npc_0001_001_KING_14_018
{
<NS>Chatting Youth<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369005_m1369">
After all that fuss across the kingdom, the one who ended up on the throne was the blood heiress after all. Oh, the irony.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N23"
@MES_npc_0001_001_KING_14_018_00
{
<NS>Attentive Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She had the strength to take down Louis, I'll give her that. But in the end, I guess blood's all that ever matters.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N22"
@MES_npc_0001_001_KING_14_018_01
{
<NS>Chatting Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Eh, she was the only viable choice of the lot. Who knows if she'll be a decent queen? Suppose that all depends on what she does next.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N22"
@MES_npc_0001_001_KING_14_012_01
{
<NS>Chatting Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I mean... An elda queen would never be recognised by the Montario folk. They've all got sticks up their arses.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_14_013
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Some would never recognise an elda queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_14_019
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
We've got to wait and see with this queen.
<WAIT>
}