//--------------------------
#SPEAKER_ID "0"
@MES_npc_0014_002_BAR_03_01_001
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Young woman... are drunks in the outside world like this as well?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1295"
@MES_npc_0014_002_BAR_03_01_003
{
<NS>Teetotaller Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
They must've finally realised the shame in their conduct. Young woman... it's all thanks to you and Lady Eupha.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0014_002_BAR_03_01_005
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Young woman... are drunks in the outside world like this as well?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1295"
@MES_npc_0014_002_BAR_03_01_007
{
<NS>Teetotaller Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...I hope the drunks in here aren't giving you any trouble. I'm sure any princess would find their behaviour uncouth...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0014_002_BAR_03_01_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
The country's princess, here in this tavern...? I hope she's okay...
<WAIT>
}