//--------------------------
#SPEAKER_ID "N38"
@MES_npc_0001_001_KING_19_023
{
<NS>Sharp-Eyed Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1314005_m1314">
You are a sensible candidate... Which is to say, I know that you are indeed Her Highness the Princess. Since it's rare for me to have the ear of royalty, allow me to give you some advice.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N38"
@MES_npc_0001_001_KING_19_015
{
<NS>Sharp-Eyed Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1314005_m1314">
Hello there. You've become quite the popular topic around these parts. I hear you're working diligently towards becoming the next queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_19_018
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
So you have queen aspirations...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N38"
@MES_npc_0001_001_KING_19_027
{
<NS>Sharp-Eyed Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1314004_m1314">
Hello there, Your Majesty the Queen... I still remember that night in the city, when I first laid eyes on you.
<WAIT>
}