//--------------------------
#SPEAKER_ID "N787"
@MES_npc_0003_001_OCEAN_17_011
{
<NS>Kind Old Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1383005_m1383">
Eyy now, it's the wee man. Hahaha, you did quite well for yerself at the Exhibition, didn't you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N787"
@MES_npc_0003_001_OCEAN_17_017
{
<NS>Kind Old Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1383001_m1383">
Ah, it's you... Oh ho, to think I would be able to meet Her Highness the Princess.
<WAIT>
}