//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_000
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355019_m1355">
'Eyyy elda! Yeah, you, Missus Elda! How d'ye prefer yer valmo, roasted or stewed?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_002
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Naw, you're jokin'? You got tae have valmo slow roasted, missus! All proper <i>connoisseurs</i> like valmo stewed!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_004
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Ach, that's right. I didnae mean to talk to you about valmo. Missus Elda, are ye interested in my special foods?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_005
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Yeahhh! Me too, me too! You're a proper <i>connoisseur</i>, eh Missus...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_007
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Well now, Missus <i>connoisseur</i> Elda, wanna buy some special foods?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_009
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
There now, that set ye right? Now Missus Elda, wanna do a little shoppin'?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_011
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I've also got the <COLOR 3><ITEM 16602 2><COLOR -1> and the <COLOR 3><ITEM 16864 2><COLOR -1>! I'm sellin' it to help me poor ol' ma... C'mon Missus, buy it! C'mon!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_013
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You have tae pay me, Missus... Just 'cause I'm a nipper disnae mean I was born yesterday!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_014
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355021_m1355">
Thanks, Missus Elda! Come around again, okay? Anytime ye like!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_016
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355019_m1355">
Oh, hullo Missus Elda! Wanna buy mah veg, or some seeds?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N567"
@MES_npc_0002_003_CLIFF_SHOP_02_016_01
{
<NS>Greengrocer Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Anyway, Missus Elda, wanna buy some beans or seeds?
<WAIT>
}