//--------------------------
#SPEAKER_ID "N1135"
@MES_npc_COMPETITION_000_PAGAN
{
<NS>Hearty Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1298001_m1298">
Hey there! Yes, you, the young, strappin' lass! Care to take on the Hundred-eyed Faux-loach Squirm-'n-Swallow Challenge?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1135"
@MES_npc_COMPETITION_013_PAGAN
{
<NS>Hearty Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1298008_m1298">
Oh-ho, she goes back for another! You must have some mustari blood in you after all! Here, take this.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1135"
@MES_npc_COMPETITION_018_PAGAN
{
<NS>Hearty Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1298001_m1298">
Hey lass. I see that hungry look in your eye. Begging your pardon, but the faux-loaches just haven't been biting lately.
<WAIT>
}