//--------------------------
#SPEAKER_ID "N1533"
@MES_npc_0005_003_MOUNT_20_01_004
{
<NS>Desperate Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The princess! Others may have been defeated, but we can believe in the princess! Now, come back from there, pleaaase!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_003_MOUNT_20_01_005
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Remember, there's still the princess!
<WAIT>
}