//--------------------------
#SPEAKER_ID "N258"
@MES_npc_0001_003_KING_18_016
{
<NS>Troubled Soldier<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360003_m1360">
I don't care who you really are. If you're truly the princess, please give us some sort of guidance!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N258"
@MES_npc_0001_003_KING_18_012_02
{
<NS>Troubled Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Please stop him and become queen. I'm really counting on you.
<WAIT>
}