//--------------------------
#SPEAKER_ID "N1350"
@MES_npc_QUEST_114_001_003
{
<NS>Portly Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
An elda and a fairy travelling together... Wait—you're that princess people have been talking about?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1350"
@MES_npc_QUEST_114_001_017
{
<NS>Portly Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
What, so it's not just a rumour? There's a princess going 'round helping people? Well, I'm sure someone like me is near last on the list.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1350"
@MES_npc_QUEST_114_001_040
{
<NS>Portly Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360002_m1360">
What business does a princess have with me? I told you, I'm done sustaining your wars.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1350"
@MES_npc_QUEST_114_001_055
{
<NS>Portly Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360001_m1360">
The rumours said you were a good-natured princess. One who can't abandon anyone in need. And now... I suppose I've seen for myself that's true.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1350"
@MES_npc_QUEST_114_001_058
{
<NS>Portly Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Just leave this to me! I'll make sure anyone who buys a blanket knows Her Highness was responsible for it.
<WAIT>
}