//--------------------------
#SPEAKER_ID "N344"
@MES_BARRACK_KING2_STOP2_000_KING
{
<NS>Recruiter Dispatcher<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1257004_m1257">
Hey... Sorry, but I'm not handing out bounties right now. A certain princess is gonna fight Louis in the Grand Cathedral, y'see.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N344"
@MES_BARRACK_KING2_STOP2_001_KING
{
<NS>Recruiter Dispatcher<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Could be the biggest mess we've seen since the royal funeral. So I'm closing up shop here. Never expected that Her Highness would appear out of the blue...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_BARRACK_Q63_010_KING
{
<NS>Gallica<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_11453_c011">
Ugh... Even as the princess you're still criticised. In that case, we can't refuse this one.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_BARRACK_Q14_025_KING
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_11086_c011">
Yeah. Take a good look at her now because she's about to become even more famous!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N344"
@MES_BARRACK_Q14_026_KING
{
<NS>Recruiter Dispatcher<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I suppose you're no self-proclaimed princess for nothing. I'm looking forward to seeing more of your work.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_BARRACK_Q134_038_KING
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11047_c011">
But in the end, that soldier did eventually decide to support us. I'm sure it'll be easier to resolve this problem once you're queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N344"
@MES_BARRACK_Q80_045_KING
{
<NS>Recruiter Dispatcher<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You're not only strong, but willing to put your life on the line for others... I believe those are qualities befitting a true queen.
<WAIT>
}