//--------------------------
#SPEAKER_ID "N351"
@MES_npc_0011_010_MADOUKI_01_01_008
{
<NS>Igniter Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1247006_m1247">
Good lady... It would seem that you've developed quite a rapport with our field representative.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N351"
@MES_npc_0011_010_MADOUKI_01_01_102
{
<NS>Igniter Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1247001_m1247">
Requesting an appraisal, lady? Of course, I would be happy to. If you would just allow me to take the item in question, then—
<WAIT>
}
//--------------------------
#SPEAKER_ID "N351"
@MES_npc_0011_010_MADOUKI_01_01_121
{
<NS>Igniter Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'm sure our field representative has more important matters to attend to... Ahem. I understand, though, lady, and perhaps I was hasty...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_npc_0011_010_MADOUKI_01_01_124
{
<NS>Gallica<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
Now, listen real carefully: <HERO_NAME> here is a candidate in the Tournament for the Throne. And she's also a personal acquaintance of Brigitta's. Still feel like lying to us?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N351"
@MES_npc_0011_010_MADOUKI_01_01_126
{
<NS>Igniter Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Eek... I-I meant no offence, lady, I simply mispoke... y-yes, how careless of me. I understand you now, my apologies. Now, allow me to correct my earlier mistake...
<WAIT>
}