//--------------------------
#SPEAKER_ID "N3"
@MES_npc_0001_001_KING_02_027
{
<NS>Church Crier<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1376007_m1376">
Uh, um... today, a duel between Louis and Her Highness the Princess will take place...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_02_027_00
{
<NS>Whispering Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Her Highness the Princess... is it really wise to trust her? After all, she is an elda...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N3"
@MES_npc_0001_001_KING_02_027_01
{
<NS>Church Crier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I-I am uncertain of the details... however, according to the words of Saint Rella, Her Highness is...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_02_028
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Saint Rella said the princess is...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N3"
@MES_npc_0001_001_KING_02_014
{
<NS>Church Crier<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1376001_m1376">
The Tournament for the Throne will decide our next ruler! The candidates will be showcased in an Exhibition of the Brave, to be held in the Principality of Oceana!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_02_029_02
{
<NS>Doubting Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Nah, they're just tryin' to put on a good show for the new queen. Doing things like they always have would only send 'em spiralling further.
<WAIT>
}