//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_000
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1386007_m1386">
Excuse me, could you possibly be... the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_010_03
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1386003_m1386">
Why, Her Highness works so hard to save her people. I just want her to have a moment to relax, and to offer a little extra monetary support.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_037
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That sounds like Her Highness's seal of approval! Now, all that's left is to reproduce this princess-infused water... Hehe!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_038
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1386004_m1386">
Ah, so astute! Its finest quality! Yes, I'd expect no less of a princess's senses!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_042
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
"Her Highness Herself Recognised Its Value Instantly!" A perfect seal of approval for the label! Now, to reproduce the princess-infused water...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_044
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1386004_m1386">
A water imparting true cosiness! Yes, a perfect seal of approval! Now, all I have to do is reproduce this princess-infused water!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_046
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Well, making bath salts is my business, you see... and what better way to sell products than to say they satisfied even Her Highness?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_npc_QUEST_111_001_047
{
<NS>Gallica<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
So you just wanted to use her for advertising!? <i>That's</i> what this was about? You're the worst...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_069
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1386001_m1386">
Just picture it! "Would you like to smell as though Her Highness herself is holding you in her arms?"
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_079
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
For now, they have Her Highness the Princess's seal of approval. Yet one day, they will have the endorsement of a queen! As always, you have my support!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1521"
@MES_npc_QUEST_111_001_005
{
<NS>Gentle Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1386001_m1386">
And then after learning that your lineage was as remarkable as your deeds... I knew for certain! You are worthy of being the next queen!
<WAIT>
}