//--------------------------
#SPEAKER_ID "87"
@MES_npc_0001_003_KING_47_002
{
<NS>Goddard<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_87001_c087">
You had a keen eye to recognise the danger Louis posed, and are braver still to have fought him. You had a queen calibre I never truly possessed.
<WAIT>
}
//--------------------------
#SPEAKER_ID "87"
@MES_npc_0001_003_KING_47_003
{
<NS>Goddard<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Still, a single year is but a drop in the proverbial bucket. Stay vigilant, queen.
<WAIT>
}