//--------------------------
#SPEAKER_ID "N114"
@MES_npc_0001_002_KING_04_023_01
{
<NS>Insatiable Gossip<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Indeed. I thought I'd seen her around the capital, too. Up to no good, no doubt.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N115"
@MES_npc_0001_002_KING_04_025_00
{
<NS>Timid Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I-It'll be all right. We don't know for certain that Louis will win... Her Highness the Princess will surely figure something out.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N115"
@MES_npc_0001_002_KING_04_025_01
{
<NS>Timid Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I know she's just an elda, but I've heard rumours that she wields this incredible power—that she can cast magic without an igniter.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N114"
@MES_npc_0001_002_KING_04_025
{
<NS>Insatiable Gossip<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1354003_m1354">
The ruler will be decided today. If it goes to Louis, my family is done for...
<WAIT>
}