//--------------------------
#SPEAKER_ID "N26"
@MES_npc_ENERGY_004_KING
{
<NS>MAG Broker<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1255006_m1255">
Hey now, elda lass. That's a nice sword you've got there...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N26"
@MES_npc_ENERGY_006_KING
{
<NS>MAG Broker<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1255005_m1255">
Why, Your Majesty... Surely Your Queen has no further need of my paltry sums for your MAG.
<WAIT>
}