//--------------------------
#SPEAKER_ID "N16"
@MES_npc_0001_001_KING_09_009
{
<NS>Drunk Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334004_m1334">
Eyy! Aren't you doin' well for yourself, lass? Heard you gave Forden what for back at the Exhibition!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N16"
@MES_npc_0001_001_KING_09_013
{
<NS>Drunk Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1334003_m1334">
Oi, lassie... Think maybe I've had a bit too much to drink for one day...
<WAIT>
}