//--------------------------
#SPEAKER_ID "N14"
@MES_npc_0003_002_OCEAN_17_016
{
<NS>Paripus Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360010_m1360">
I dunno too much about her, but she seems like a sound fella. I might throw my lot in with her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_17_028
{
<NS>Perceptive Rhoag<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
By the by... Have a look at the corner of the king's rock. That elda girl's appeared.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_17_052
{
<NS>Nidia Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Louis's supporters are undeniably a threat, but we've still got Her Highness to fight against them.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_17_054
{
<NS>Overarching Summary<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Her Highness is still fighting against Louis...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_17_057
{
<NS>Nidia Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1387003_m1387">
If that were the case, we'd be unable to execute criminals. Villains would do as they pleased... Choosing a ruler would be the last thing on our minds.
<WAIT>
}