//--------------------------
#SPEAKER_ID "N242"
@MES_npc_0001_003_KING_13_019
{
<NS>Attentive Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It has indeed. When that elda lass's face showed up, it was the first thing I noticed that morning.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N242"
@MES_npc_0001_003_KING_13_016_00
{
<NS>Attentive Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Indeed, I do. Suddenly, Her Majesty's face eclipsed the others for the briefest of moments, then it all crumbled away like sand. Over a bit too soon after all that palaver, I'd say.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N242"
@MES_npc_0001_003_KING_13_016_02
{
<NS>Attentive Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I liked her coronation speech, but I can't say she's accomplished much of any importance since then.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N301"
@MES_npc_0001_003_KING_13_016_01
{
<NS>Man Viewing Cathedral<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Her strength certainly was incredible during the final battle in Grand Trad, but I wonder what people in other cities who didn't see that sight think of things...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N301"
@MES_npc_0001_003_KING_13_016
{
<NS>Man Viewing Cathedral<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1326004_m1326">
I miss the days when the face rock was here. Never knew what to expect back then—joyful one moment, miserable the next. Remember? After Louis was defeated and the queen decided...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_13_017
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I wonder what the queen reputation is like in other towns?
<WAIT>
}