//--------------------------
#SPEAKER_ID "N221"
@MES_npc_0001_003_KING_01_026
{
<NS>Sentry<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1381007_m1381">
I believe that you are Her Highness the Princess, so allow me to ask you frankly. Is it possible to stop this chaos?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_npc_0001_003_KING_01_011
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11051_c011">
So it seems that the bigger the candidate's face on the rock, the more qualified they are to be ruler.
<WAIT>
}