//--------------------------
#SPEAKER_ID "N365"
@MES_npc_0011_002_BAR_04_009
{
<NS>Deferent Staff<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1350001_m1350">
Oh, it's you... Wait, my apologies for being so rude, I shouldn't speak so casually. You're the princess, after all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0011_002_BAR_04_011
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I never thought this tavern would host the princess!
<WAIT>
}