//--------------------------
#SPEAKER_ID "N483"
@MES_npc_0002_002_CLIFF_11_000
{
<NS>Delighted Girl<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355005_m1355">
Bardon's been saying all around town that he supports you, Ms. Princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N483"
@MES_npc_0002_002_CLIFF_11_001
{
<NS>Delighted Girl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You and Bardon are friends, right, Ms. Princess? Make sure to be nice to him! Okay?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_002_CLIFF_11_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Be nice to Bardon! Okay, Miss Princess?
<WAIT>
}