//--------------------------
#SPEAKER_ID "86"
@MES_npc_0005_002_MOUNT_24_01_019
{
<NS>Julian<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oh, I haven't the slightest concern about you. Now that you've openly opposed Louis, you'll be a wanted woman come tomorrow.
<WAIT>
}
//--------------------------
#SPEAKER_ID "86"
@MES_npc_0005_002_MOUNT_24_01_002_01
{
<NS>Julian<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Perhaps it's time I took to the pulpit. Electing a ruler and looking to the future requires the acumen of an enlightened thinker.
<WAIT>
}