//--------------------------
#SPEAKER_ID "N785"
@MES_npc_LETTERWRITING_000
{
<NS>Troubled Old Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1308001_m1309">
Say, lass... Yes, you young man there. Can ya read and write?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N785"
@MES_npc_LETTERWRITING_005_08
{
<NS>Troubled Old Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
"What struck me was that I heard there was a girl younger than you among the candidates, and apparently she's an elda." Hmm?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N785"
@MES_npc_LETTERWRITING_012
{
<NS>Troubled Old Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1308004_m1309">
I'm truly lucky to have met you, lass. It's impressive, to read and write so well when you're still just a wee nipper.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N785"
@MES_npc_LETTERWRITING_005_06
{
<NS>Troubled Old Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
"Lately, everyone's nattering on about a tournament to decide the next ruler. I never expected an era would come where us common folk could choose."
<WAIT>
}
//--------------------------
#SPEAKER_ID "N785"
@MES_npc_LETTERWRITING_005_11
{
<NS>Troubled Old Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That's right, there were beautiful candidates, and if such a ruler were crowned, I'd need to live a long life... Hmm? I feel like something's off. Ah well.
<WAIT>
}