//--------------------------
#SPEAKER_ID "N898"
@MES_npc_WATER_000_OCEAN
{
<NS>Cheery Water Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1236001_m1236">
'Ey, you there, lass! Findin' yourself parched? Then do I have the water for you!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N898"
@MES_npc_WATER_003_OCEAN
{
<NS>Cheery Water Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1236010_m1236">
Luck be a tall glass of water, lass! Got our Idlesday sale goin' on, so buy some water! Then buy more!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N898"
@MES_npc_WATER_003_00_OCEAN
{
<NS>Cheery Water Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1236010_m1236">
Good t'see ya, lass. Today's Forgiveness Day, y'know. Our prices are cheaper than normal, so you oughta stock up!
<WAIT>
}