//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_006
{
<NS>Surprised Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1369003_m1369">
But look, over there. It's still small, but I can see that elda girl's face.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_007
{
<NS>Suspicious Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Who is she really? Her and those companions of her... Think they're after our relic?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_012
{
<NS>Reformed Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Even though the chief dropped out of the tournament, we should have trusted her decision to join it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_017
{
<NS>Cheerful Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The tournament brought new hope with it. That elda girl's face has appeared on the rock...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_018
{
<NS>Reformed Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1379001_m1379">
Indeed. We've always resented this "country" we're supposedly a part of, but if she became its queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_020
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
If she became queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_025
{
<NS>Calm Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The group that saved us and currently travels with Lady Eupha... I've heard they are the princess and her royal guard.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_031
{
<NS>Downcast Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Her Highness and Lady Eupha's ideals are failing to reach the people... How frustrating!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_010
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Who is that outsider girl?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0004_001_PAGAN_046_01_008
{
<NS>Wary Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I certainly hope not. It's not as though the island's troubles would be solved by a new ruler, besides.
<WAIT>
}