//--------------------------
#SPEAKER_ID "N97"
@MES_npc_QUEST_005_001_044
{
<NS>Young Nidia Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327003_m1327">
Er, I heard a rumour that you were the princess... I can't believe I asked someone so above my station to research cooking for me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N97"
@MES_npc_QUEST_005_001_045
{
<NS>Young Nidia Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But the princess being an elda is really something! All those fools who judge people based on their tribe... I bet their whole world's been turned upside down!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_QUEST_005_001_046
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
So you're the princess... Amazing!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N97"
@MES_npc_QUEST_005_001_047
{
<NS>Young Nidia Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1327011_m1327">
There's been some nasty rumours about you at the hotel I work at. "I knew there could never be an elda princess," that kind of thing.
<WAIT>
}