//--------------------------
#SPEAKER_ID "N135"
@MES_npc_ACTIVIST_000_MOUNT
{
<NS>Activist Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1286001_m1286">
You there! You are an elda, are you not? Huh, wait... forgive me if I'm mistaken, but you're Her Highness the Princess, aren't you!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N135"
@MES_npc_ACTIVIST_017_05_MOUNT
{
<NS>Activist Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Those in power say there's no way that someone like you could ever be queen. But right now, I have more faith in you than in any of their teachings.
<WAIT>
}