//--------------------------
#SPEAKER_ID "11"
@MES_npc_QUEST_Arena_420
{
<NS>Gallica<NE>
<BUSTUP 7 0 0>
<VOICE "v_co_11030_c011">
Alone!? As in, no one can heal her!? <COLOR 0>You'll have a hard time recovering<COLOR -1> if you get poisoned or something...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_QUEST_Arena_602
{
<NS>Coliseum Host<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1275010_m1275">
Whoops! And that is time! Regretfully, our challenger, <HERO_NAME>, was unable to defeat all her opponents!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1014"
@MES_npc_QUEST_Arena_004
{
<NS>Spirited Receptionist<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
All that's left... is for you to become queen and make this coliseum even more thrilling! I'm afraid that will have to do!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1014"
@MES_npc_QUEST_Arena_130_11
{
<NS>Spirited Receptionist<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1276007_m1276">
You'll be able to take on the <COLOR 0>greatest battle in coliseum history<COLOR -1>! You'll fight <COLOR 0>nine<COLOR -1> battles in total! Win, and you'll be queen of the coliseum!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1014"
@MES_npc_QUEST_Arena_511
{
<NS>Spirited Receptionist<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Today's fight will be carved into the history of the Varmareno Coliseum... You're the queen of this place!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_npc_QUEST_Arena_523
{
<NS>Gallica<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_11162_c011">
Well, I guess we should hit the road. Let's fight just like we did here until the very end. You good with that, O Queen of the Coliseum?
<WAIT>
}