//--------------------------
#SPEAKER_ID "N843"
@MES_npc_0003_002_OCEAN_03_006
{
<NS>Roussainte Sailor<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I heard an elda lass did the deed. Though Sanctifex Forden's claimed the credit.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N844"
@MES_npc_0003_002_OCEAN_03_008
{
<NS>Roussainte Child<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1355005_m1355">
The princess is alive? Why was she hiding?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N844"
@MES_npc_0003_002_OCEAN_03_010
{
<NS>Roussainte Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Why? The princess is stronger than the navy, right? Heyyyyy... C'mon, why? What do you mean?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_002_OCEAN_03_014
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
The princess was alive?
<WAIT>
}