//--------------------------
#SPEAKER_ID "N783"
@MES_npc_QUEST_067_001_003
{
<NS>Classy Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Well, well. An elda with a fairy companion... You must be the fool who thinks she can defy her tribe's legacy, and take the throne.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N783"
@MES_npc_QUEST_067_001_015
{
<NS>Classy Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I do not. If I could choose a ruler to serve, I'd want a true gourmet with a refined palate... but by the looks of you, I'm sure your tastes must be pedestrian.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N783"
@MES_npc_QUEST_067_001_065
{
<NS>Classy Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1322001_m1322">
Chefs and ruler alike must seek out new knowledge and new challenges to bring the people joy. Indeed, that is how I know you would make a fine ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N783"
@MES_npc_QUEST_067_001_077
{
<NS>Classy Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1322006_m1322">
If, by chance, you were to become queen... I would not be opposed to working in the royal palace once again. And now, farewell.
<WAIT>
}