//--------------------------
#SPEAKER_ID "N867"
@MES_npc_QUEST_062_001_077
{
<NS>Overfamiliar Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1312004_m1312">
Hah! I never imagined you'd turn out to be the princess herself.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N867"
@MES_npc_QUEST_062_001_069
{
<NS>Overfamiliar Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
And what better challenge than to help a dear, loyal friend become our next queen?
<WAIT>
}