//--------------------------
#SPEAKER_ID "N75"
@MES_npc_0001_001_KING_41_008
{
<NS>Dejected Youth<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361011_m1361">
The new ruler... It'd be nice if they're someone like those Hero Kings from the old tales.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_41_015
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
It'd be nice if the new ruler was like the Hero Kings of old...
<WAIT>
}