//--------------------------
#SPEAKER_ID "N243"
@MES_npc_0001_003_KING_001_01_037
{
<NS>Burly Butcher<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1251008_m1251">
Today's Idlesday, is it? All right, then. Enjoy your discount, lassie!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N243"
@MES_npc_0001_003_KING_001_01_037_03
{
<NS>Burly Butcher<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1251009_m1251">
Well, what a surprise this is. Customers who come in days like these are real treasures. What'll it be, lass?
<WAIT>
}