//--------------------------
#SPEAKER_ID "50"
@MES_npc_0004_001_PAGAN_EDENI_058
{
<NS>Edeni<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
But don't worry, my faith in you will not waver. I'm just glad you made it through safely, my princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "50"
@MES_npc_0004_001_PAGAN_EDENI_063
{
<NS>Edeni<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Promise me you'll live through this. The world I've longed for... With you as queen, it might have a chance...
<WAIT>
}