//--------------------------
#SPEAKER_ID "67"
@MES_npc_0011_001_Fabienne_01_042
{
<NS>Fabienne<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_67004_c067">
Who would've believed you were Her Highness, the actual princess? I apologise for the less than royal accommodations, but try to have a good rest regardless.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0011_001_Fabienne_01_112
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Who would've believed you were Her Highness, the actual princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_npc_0011_001_Fabienne_01_043
{
<NS>Fabienne<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_67055_c067">
Grius would've been taken aback to see the princess duelling Louis... No, on second thought, this is exactly what that man would've wanted.
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_npc_0011_001_Fabienne_01_050
{
<NS>Fabienne<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_67031_c067">
There are those whose faith still lies with the princess. So stand tall and give Louis what he has always deserved.
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_npc_0011_001_Fabienne_01_055
{
<NS>Fabienne<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_67053_c067">
To think that the queen of our country would sneak over to my tavern, without so much as a single bodyguard with her... you never change, do you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_npc_0011_001_Fabienne_01_022
{
<NS>Fabienne<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_67001_c067">
A tournament to be ruler, huh? That's certainly something I thought I'd never see, but obviously you have my support.
<WAIT>
}