//--------------------------
#SPEAKER_ID "N1801"
@MES_npc_0006_004_FOREST_001_01_000
{
<NS>Elda Youth<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1372005_m1372">
Are you associated with the group that's been sheltering the princess? It's all because of them that another calamity has befallen us...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1801"
@MES_npc_0006_004_FOREST_001_01_002
{
<NS>Elda Youth<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I had heard that the princess was the only elda within the Resistance...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0006_004_FOREST_001_01_003
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I had heard that the princess was the only elda in the Resistance...
<WAIT>
}