//--------------------------
#SPEAKER_ID "N428"
@MES_npc_0002_001_CLIFF_19_009
{
<NS>Listening Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So you think all those other candidates who came to town, they're all just trifles? What about that elda and the folks with her—didn't they save us?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N427"
@MES_npc_0002_001_CLIFF_19_010
{
<NS>Country Crier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
They were saviours to our city, that is correct. But whether she ought to be queen is a different question. First off, she <i>is</i> an elda...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_001_CLIFF_19_011
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
She is our saviour, but should she be queen?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N427"
@MES_npc_0002_001_CLIFF_19_013
{
<NS>Country Crier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Unbelievable. In a town like this, where people were saved by Her Royal Highness the Princess... such ungratefulness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N428"
@MES_npc_0002_001_CLIFF_19_014
{
<NS>Listening Roussainte<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1337002_m1337">
Didn't you say before that, "there was no way an elda was going to be queen"? You didn't like her at all!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N427"
@MES_npc_0002_001_CLIFF_19_015
{
<NS>Country Crier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I... well... I was rude, and now I regret it! Certainly hadn't a whit of an idea that she was Her Royal Highness the Princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N428"
@MES_npc_0002_001_CLIFF_19_018
{
<NS>Listening Roussainte<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Aye, where the hell are they hiding? I thought everyone in this town was for Her Highness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_001_CLIFF_19_019
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I thought this town was on the princess's side.
<WAIT>
}