//--------------------------
#SPEAKER_ID "N244"
@MES_npc_WATER_001_01_KING
{
<NS>Water Merchant<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But honestly, my only wish is to run this shop with my husband, for as long as I can. And I want a queen who'd support that dream.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N244"
@MES_npc_WATER_012_KING
{
<NS>Water Merchant<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1252007_m1252">
Well, if it isn't Your Majesty! Hello there! Ah, even I don't have the pluck to try selling water to the queen.
<WAIT>
}