//--------------------------
#SPEAKER_ID "N773"
@MES_npc_0003_001_OCEAN_10_004
{
<NS>Scornful Guardsman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360015_m1360">
The princess being an elda? Pfff, you must be having a laugh. Still, as no one knows what Her Highness looks like, s'pose no one can prove ya wrong.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N773"
@MES_npc_0003_001_OCEAN_10_005
{
<NS>Scornful Guardsman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Rightly impressive, persuading people to support you with such a ridiculous pronouncement. But there's no way I can believe the princess is an elda.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0003_001_OCEAN_10_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
No way the princess can be an elda.
<WAIT>
}