//--------------------------
#SPEAKER_ID "N944"
@MES_npc_QUEST_060_001_006
{
<NS>Exhausted Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
An elda girl, accompanied by a fairy... Then you must be the self-proclaimed princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N944"
@MES_npc_QUEST_060_001_005
{
<NS>Exhausted Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...Now that I mention it, I do recall seeing an elda girl at the Exhibition. One that looked to be the same age as...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N944"
@MES_npc_QUEST_060_001_044
{
<NS>Exhausted Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1350001_m1350">
If someone like you were to become queen, this country would surely change... I will do what I can to help make that happen.
<WAIT>
}