//--------------------------
#SPEAKER_ID "N1361"
@MES_npc_0005_001_MOUNT_13_01_004
{
<NS>Travelling Performer<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Though I daresay there's nary a soul who expected a winner-take-all duel between the princess and Louis. Unpredictable as ever, fate is.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_001_MOUNT_13_01_005
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
One final duel for the princess and Louis...
<WAIT>
}