//--------------------------
#SPEAKER_ID "N9"
@MES_npc_0001_001_KING_05_024
{
<NS>Runner Fanatic<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1359004_m1359">
Hello there, my eldan good lady! This gauntlet runner of yours has been quite the hot topic around these parts lately.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N9"
@MES_npc_0001_001_KING_05_010
{
<NS>Runner Fanatic<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1359001_m1359">
I heard that you're supposedly the princess. But... that doesn't matter.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N9"
@MES_npc_0001_001_KING_05_017
{
<NS>Runner Fanatic<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1359011_m1359">
Ugh... Can't believe the owner of this sweet gauntlet runner ended up queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_05_018
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
The queen gauntlet runner was the best!
<WAIT>
}