//--------------------------
#SPEAKER_ID "N123"
@MES_npc_HEATHEN_000_KING
{
<NS>Masked Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1289001_m1289">
Greetings, elda girl... We don't see many of your tribe in the Royal Capital, though we're similar in that way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N123"
@MES_npc_0001_002_KING_002_01_050
{
<NS>Masked Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1289002_m1289">
Ah, it's you. It's been quite some time, hasn't it? Ever since the new queen reign, matters have changed a great deal for the tribe's teachings.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N123"
@MES_npc_0001_002_KING_002_01_054
{
<NS>Masked Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1289001_m1289">
The mustari's place in this world will surely find new footing with Lady Eupha making great efforts as one of the Queen Six Partisans...
<WAIT>
}