//--------------------------
#SPEAKER_ID "N222"
@MES_npc_0001_003_KING_03_016
{
<NS>Clemar Child<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1340005_m1340">
Hey, Miss Princess! Is it true you can use magic?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N222"
@MES_npc_0001_003_KING_03_024_01
{
<NS>Clemar Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So... Miss Princess, can you kill Louis?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N222"
@MES_npc_0001_003_KING_03_026_00
{
<NS>Clemar Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But y'know, Miss Queen, I've been cooking instead of my mum, and I'm trying really hard...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N222"
@MES_npc_0001_003_KING_03_026_02
{
<NS>Clemar Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
My mum is watching me from the sky, isn't she? Just like your dad, Miss Queen?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N222"
@MES_npc_0001_003_KING_03_020
{
<NS>Clemar Child<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Then why are you trying to be queen? You're stupid!
<WAIT>
}