//--------------------------
#SPEAKER_ID "N564"
@MES_npc_0002_003_CLIFF_07_020
{
<NS>Frightened Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1360003_m1360">
Your H-Highness the P-Princess...!? As I live and b-breathe...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0002_003_CLIFF_07_022
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I haven't any idea how to act in front of a p-princess...
<WAIT>
}