//--------------------------
#SPEAKER_ID "N1090"
@MES_npc_0013_002_BAR_01_01_000
{
<NS>Eloquent Tavernstaff<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1343005_m1343">
Young lass! Is there something you need besides food?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1090"
@MES_npc_0013_002_BAR_01_01_016
{
<NS>Eloquent Tavernstaff<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1343011_m1343">
Why, young lass... or rather, you're the princess now, aren't you? Good to see you again...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1090"
@MES_npc_0013_002_BAR_01_01_013
{
<NS>Eloquent Tavernstaff<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The tavern's always buzzing with talk about the "next ruler". Ale and politics are rarely a good mix, and there's trouble sometimes...
<WAIT>
}