//--------------------------
#SPEAKER_ID "N1343"
@MES_npc_0005_001_MOUNT_03_01_001
{
<NS>Grumpy Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1318003_m1318">
If the girl's been entrusted with Saint Rella's will, have we any choice but to put our faith in her?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_001_MOUNT_03_01_004
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Who'd have thought this much blood would have to be spilled just to elect the new ruler...
<WAIT>
}