//--------------------------
#SPEAKER_ID "N1020"
@MES_npc_OCEAN_WORM_OLDMAN_01_407
{
<NS>Elderly Entomophile<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Thanks to you, young woman, my long-held theory about dragons has been confirmed...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1020"
@MES_npc_OCEAN_WORM_OLDMAN_02_601
{
<NS>Elderly Entomophile<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_D5_npc01_01_m1127">
Young woman, I would be most gratified if you would make this a country where people can research bugs freely... or do any other type of research, of course.
<WAIT>
}