//--------------------------
#SPEAKER_ID "N295"
@MES_npc_0001_003_KING_43_017
{
<NS>Anxious Shopkeep<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Now that I think about it, it might have been Her Highness. If I remember correctly, she was using this extraordinary magic I'd never seen before...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_43_019
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Did I see Her Highness back then?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N295"
@MES_npc_0001_003_KING_43_009
{
<NS>Anxious Shopkeep<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1361011_m1361">
Ugh... Can you believe that we have to choose our own ruler? Not sure this country has a future...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N295"
@MES_npc_0001_003_KING_43_010
{
<NS>Anxious Shopkeep<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
They think it's easy as picking your veg suppliers? I know what a good vegetable looks like. But a ruler? I haven't the foggiest.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N296"
@MES_npc_0001_003_KING_43_011
{
<NS>Friendly Customer<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1336004_m1336">
I don't find ruler and vegetables so different, really. So let's hear it— Who's your candidate of choice?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_003_KING_43_012
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Can you pick ruler like veggies?
<WAIT>
}