//--------------------------
#SPEAKER_ID "0"
@MES_npc_MILKING_000_03
{
<NS>Man with Cow<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1300001_m1300">
Say lass, are ye the one going by Princess these days? ...Naww, there's nae chance someone so famous would be in a place like this.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_MILKING_021
{
<NS>Man with Cow<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If ye want to spend time with my bonnie cow, we'll be here waiting. Mind how you go now, lass.
<WAIT>
}