//--------------------------
#SPEAKER_ID "N504"
@MES_npc_0005_002_MOUNT_23_01_011_07
{
<NS>Guard<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1373004_m1373">
As you can see, Julian's using it at the moment to denounce the princess. Though if you plan to shut him up, I'd welcome the relief.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_npc_0005_002_MOUNT_23_01_004
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11051_c011">
So it seems that the bigger the candidate's face on the rock, the more qualified they are to be ruler.
<WAIT>
}