//--------------------------
#SPEAKER_ID "N1522"
@MES_npc_FOLKTALE_037_MOUNT
{
<NS>Chipper Old Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1280005_m1280">
Excellent. Listen carefully, young woman. Now, where were we...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1522"
@MES_npc_FOLKTALE_033_MOUNT
{
<NS>Chipper Old Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1280002_m1280">
Oh, it's you—the girl with the fairy companion.
<WAIT>
}