//--------------------------
#SPEAKER_ID "N11"
@MES_npc_0001_001_KING_06_019
{
<NS>Elderly Noble<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Is it that little whelp who claims to be princess? What in the world was the saint thinking, saying what she did!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N11"
@MES_npc_0001_001_KING_06_024_00
{
<NS>Elderly Noble<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Quite. I don't know if I trust that princess or whatever she calls herself just yet, but I daresay she has a chance.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_06_025
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I don't trust the princess, but what choice do we have?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N11"
@MES_npc_0001_001_KING_06_026_00
{
<NS>Elderly Noble<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Grin and bear it for now. This queen as much a dreamer as the last. She'll be crushed under the weight of her lofty ideals soon enough.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N10"
@MES_npc_0001_001_KING_06_022
{
<NS>Dapper Noble<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1313010_m1313">
Why have we needed this long to decide upon a ruler? Was "His Majesty" in the sky so dissatisfied with His Eminence Forden?
<WAIT>
}