//--------------------------
#SPEAKER_ID "83"
@MES_npc_0001_001_KING_32_000
{
<NS>Rudolf<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_83008_c083">
To think that you, of all people, would end up becoming the queen... I never expected it, but I will tell you one thing.
<WAIT>
}
//--------------------------
#SPEAKER_ID "83"
@MES_npc_0001_001_KING_32_001
{
<NS>Rudolf<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Wax poetic about your ideals all you want, but when it comes to protecting the country, only power will suffice. The people don't all approve of a dreamer queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "83"
@MES_npc_0001_001_KING_32_006
{
<NS>Rudolf<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I've watched silently for a year, and I still don't accept you as my queen. You're all ideals and no power... Same as the king before you.
<WAIT>
}