//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_17_040
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
An elda within the church!? She'll sully the place with her filth!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N36"
@MES_npc_0001_001_KING_17_023
{
<NS>Restless Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347002_m1347">
Y-Y-You!? The princess!? Saint Rella says it is so, but... it just can't be. That's absurd, the princess could never be an elda!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N36"
@MES_npc_0001_001_KING_17_025
{
<NS>Restless Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347002_m1347">
Louis or an elda pretending to be the princess... Are these two all we have to choose from? I would hardly call that a choice!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N36"
@MES_npc_0001_001_KING_17_029
{
<NS>Restless Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347003_m1347">
An elda... Wait, aren't you Her Majesty the Queen!? Why would you be in a place like this...
<WAIT>
}
//--------------------------
#SPEAKER_ID "N36"
@MES_npc_0001_001_KING_17_035
{
<NS>Restless Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347003_m1347">
Ugh, it's that creepy elda girl! It's disgusting, the way you maintain this pretence of being a legitimate candidate for the throne.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N36"
@MES_npc_0001_001_KING_17_027_06
{
<NS>Restless Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
For an elda to be our last hope... This country must truly be in a sorry state. It's awful to think about... But prove me wrong, girl. Save this country!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N36"
@MES_npc_0001_001_KING_17_019
{
<NS>Restless Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347003_m1347">
...I must be losing my mind. You think you'll ever be queen? Hah, remember your tribe, and the hole that they all crawled out of. You ought to know your place!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_17_020
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
An elda as queen would bring disaster to us all!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_17_034
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
It doesn't matter how hard you try. An elda queen will never happen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N36"
@MES_npc_0001_001_KING_17_029_01
{
<NS>Restless Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1347002_m1347">
Psh, so you say. Just because the queen an elda doesn't mean everyone's accepted it, you know.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0001_001_KING_17_030
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
An elda queen!? What a world...
<WAIT>
}