//--------------------------
#SPEAKER_ID "N1539"
@MES_npc_QUEST_042_001_002
{
<NS>Obsessive Sanctist Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
An elda and a fairy... You must be that self-proclaimed princess. Don't attempt to stop me. It's too late to turn back.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1539"
@MES_npc_QUEST_042_001_029
{
<NS>Obsessive Sanctist Soldier<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1318004_m1318">
No matter who it may be, you'll pay genuine attention to anyone in need... You're far more qualified to be queen than Louis.
<WAIT>
}