//--------------------------
#SPEAKER_ID "N1511"
@MES_npc_0005_003_MOUNT_11_01_001
{
<NS>Prattling Man<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1338005_m1338">
You think that princess is worth our attention? Ridiculous. I have no doubt a man of Louis's quality will hound that girl to the ends of the earth.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1512"
@MES_npc_0005_003_MOUNT_11_01_001_00
{
<NS>Retorting Woman<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Yet she is the sole opponent "a man of Louis's quality" deemed worthy! The princess even managed to attain the support of the Sanctists, has she not?
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1511"
@MES_npc_0005_003_MOUNT_11_01_001_01
{
<NS>Prattling Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So you believe the tide is turning in the princess's favour? While I would admit she has the potential to upend the current circumstances...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_0005_003_MOUNT_11_01_003
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Louis against the princess in a duel... And both had to claw their way up.
<WAIT>
}