//--------------------------
#SPEAKER_ID "N784"
@MES_npc_QUEST_070_001_053
{
<NS>Sullen Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
How could I not? You were kind to some random girl raving about seeing tooth monsters.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N784"
@MES_npc_QUEST_070_001_065
{
<NS>Sullen Woman<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1359004_m1359">
Oh, if it isn't the man who saved my teeth! I'm still using that toothbrush, you know.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N784"
@MES_npc_QUEST_070_001_063
{
<NS>Sullen Man<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Wish we could have a queen as kind as you. That way, we might have a shot at peace! Don't give up, now!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_npc_QUEST_070_001_064_00
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
We need your queen kindness!
<WAIT>
}