//--------------------------
#SPEAKER_ID "N408"
@MES_npc_TAROT_000_CLIFF
{
<NS>Spirited Seer<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1250006_m1250">
Giant sand... worm? Sorry, young woman. Don't know a thing about it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N408"
@MES_npc_TAROT_Before_Vote_00_CLIFF
{
<NS>Spirited Seer<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1250006_m1250">
Oh, Your Highness. Isn't the ruler being decided tomorrow? Should you really be standing around chatting with seers?
<WAIT>
}