//--------------------------
#SPEAKER_ID "N174"
@MES_npc_0001_002_KING_33_007
{
<NS>Former Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Ho ho ho... You'd find no fault in thinking so, young woman. In today's world, "magic" and igniters go hand in hand.
<WAIT>
}
//--------------------------
#SPEAKER_ID "N174"
@MES_npc_0001_002_KING_33_008
{
<NS>Former Soldier<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Ho ho ho... Careful takin' the piss with your elders, girl. But yes, I can see how a young lass could believe it.
<WAIT>
}