//--------------------------
#SPEAKER_ID "11"
@MES_f01_FLT_normal_SayHello_004
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
True, we did come to Grand Trad just so that we could lift the princess's curse. But I don't think that was the true beginning of our adventure.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_f01_FLT_normal_SayHello_006
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
Yup. At first, we were just taking a trip to undo the princess's curse.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_f01_FLT_normal_SayHello_008
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
That's why I consider this place, and that moment, the real start of it all. The beginning of the long, winding road that led to you becoming <i>our</i> queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_f01_FLT_normal_SayHello_206
{
<NS>Gallica<NE>
<BUSTUP 6 0 0>
<LIPSYNC>
But here I am struggling to keep the queen of the whole dang country in one place for a few seconds! You catch my drift?
<WAIT>
}