//--------------------------
#SPEAKER_ID "2"
@MES_f02_FLT_normal_022_000
{
<NS>Strohl<NE>
<BUSTUP 10 0 0>
<VOICE "v_co_2156_c002">
I grow tired of the cries of support for Louis and Forden, and I cannot wait to put forward the princess's return.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_f02_FLT_normal_022_006
{
<NS>Strohl<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
This could be our opportunity to break the princess's curse, so we really ought to infiltrate the Charadrius before the day's end.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_f02_FLT_normal_044_000
{
<NS>Strohl<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_2151_c002">
I could never justify cursing the princess. Yet had I been in Rella's situation, I...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_f02_FLT_normal_052_000
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_2392_c002">
The Day of the Hero, which will decide the next ruler, draws near. We must settle the score with Louis before then.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_f02_FLT_normal_SayHello_020
{
<NS>Strohl<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_2245_c002">
Have you been sneaking about the city again? And have you dodged Hulkenberg? Queen or not, you've hardly changed.
<WAIT>
}