//--------------------------
#SPEAKER_ID "3"
@MES_f03_003_001_048
{
<NS>Hulkenberg<NE>
<LIPSYNC>
Yet for all my searching, I never found the princess. For long seasons I wandered, aimless and liegeless...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_003_001_055
{
<NS>Hulkenberg<NE>
<LIPSYNC>
When I left the capital, I did so with the sole purpose of helping the princess. But at times, I can't help but think...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_003_001_056
{
<NS>Hulkenberg<NE>
<VOICE "v_co_3152_c003">
...But let us speak no more of what-ifs. I've no intention of changing my path now. Together, we shall move forward for the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_003_001_057
{
<NS>Hulkenberg<NE>
<VOICE "v_co_3152_c003">
...But let us speak no more of what-ifs. I am here now, and once more, I may stand as guardian to the princess.
<WAIT>
}