//--------------------------
#SPEAKER_ID "M0126_001"
@MES_f03_004_001_048
{
<NS>Rhodanthe<NE>
<VOICE "v_fm012008_fm012">
Hmph... I see your whelp hasn't learned to hold her tongue.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0126_001"
@MES_f03_004_001_052
{
<NS>Rhodanthe<NE>
<VOICE "v_fm012008_fm012">
Hmph. 'Tis almost comical. The girl is clearly possessed of more sense than you.
<WAIT>
}