//--------------------------
#SPEAKER_ID "3"
@MES_f03_005_001_015
{
<NS>Hulkenberg<NE>
<VOICE "v_co_3042_c003">
After our training concluded, Rhodanthe was openly being considered for an appointment to the princess's royal guard.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_005_001_044
{
<NS>Hulkenberg<NE>
<LIPSYNC>
Of course, in my time as a knight, I failed to protect the princess, and abandoned my post to seek her out with no more honour than a thief in the night...
<WAIT>
}