//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_playspot_NotOccur_010
{
<NS>Hulkenberg<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_3061_c003">
I wonder what the Archetypes are, really? Such a power I've never seen, even through all my travels in search of the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_playspot_NotOccur_058
{
<NS>Hulkenberg<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_3061_c003">
A thought keeps occurring... Had I not ventured out in search of the princess, and stayed with the knighthood instead, could I have prevented its degeneration?
<WAIT>
}