//--------------------------
#SPEAKER_ID "3"
@MES_f03_002_001_008
{
<NS>Hulkenberg<NE>
<LIPSYNC>
'Twas not long after joining that I was assigned to the princess's retinue, so I was desperate to improve. I was younger even than you are now, and notably unskilled.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0126_001"
@MES_f03_002_001_041
{
<NS>Rhodanthe<NE>
<VOICE "v_fm012007_fm012">
Ah, of course. When you couldn't save the princess, any dignity you had as a royal guard was well and duly snuffed, wasn't it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0126_001"
@MES_f03_002_001_041_00
{
<NS>Rhodanthe<NE>
<LIPSYNC>
I suppose you had little choice but to cling to your search for her shadow.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_002_001_055
{
<NS>Hulkenberg<NE>
<VOICE "v_co_3152_c003">
<HERO_NAME>... Let us fight onward in the name of Her Royal Highness. That is the path I walk now.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0126_001"
@MES_f03_002_001_026
{
<NS>Rhodanthe<NE>
<VOICE "v_fm012006_fm012">
You associate with this girl? Disgraceful.
<WAIT>
}