//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_000_000
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_3164_c003">
I confess I was relieved to see Her Highness. Though she's certainly grown since I knew her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_011_000
{
<NS>Hulkenberg<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_3187_c003">
I-I can hardly follow such turns... I never thought Her Highness's gauntlet runner would hold such a secret...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_023_000
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_3390_c003">
If all goes to plan, perhaps I shall finally be reunited with Her Highness the Princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_023_001
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
What ought we discuss first...? And how to tell her about the Tournament for the Throne?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f03_FLT_normal_023_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
What should I say to Her Highness...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_024_000
{
<NS>Hulkenberg<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_3162_c003">
'Tis a bitter setback that we've lost the means to break Her Highness's curse.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_025_000
{
<NS>Hulkenberg<NE>
<BUSTUP 7 0 0>
<VOICE "v_co_3187_c003">
The sea monster is still about! We cannot let it damage Her Highness's runner!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_041_000
{
<NS>Hulkenberg<NE>
<BUSTUP 9 0 0>
<VOICE "v_co_3134_c003">
Could Forden truly have killed Her Highness? If the attack was by his hand, we must have our answers from him, no matter the means.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_041_001
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The true culprit behind the curse must be brought to justice, and fast. Her Highness's life is at stake...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f03_FLT_normal_041_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
We must kill the curse's source. For Her Highness...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_042_000
{
<NS>Hulkenberg<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_3166_c003">
To masquerade as Her Highness the Princess... It seems insolent to claim her identity, and yet...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_042_001
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I cannot put my finger on why, but I approve of the suggestion—though not without reservation. As the princess's royal guard, you shall have my protection.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_043_001
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Ruse or not, announcing that you are the princess will bring us no small share of hardship.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_044_000
{
<NS>Hulkenberg<NE>
<BUSTUP 9 0 0>
<VOICE "v_co_3134_c003">
Though Rella was the princess's true assailant, she was but another victim of Forden's schemes.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_051_000
{
<NS>Hulkenberg<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_3390_c003">
And so Her Highness returns to the royal capital in triumph and glory... In truth, I'd have liked to welcome her back with a grand feast...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_SayHello_008
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
I was but a wanderer searching in vain for the princess, and it was through you I learned she yet lived. And in the end, it was your ascent to the throne I supported.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_SayHello_010_02
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
They know they protect not just a queen, but a ruler who stands beside her people and hears their voices in clarion truth.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f03_FLT_normal_054_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I shall witness the moment you become queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_SayHello_005
{
<NS>Hulkenberg<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_3186_c003">
Well—that is, think of your station! How else would the knights' captain address the land's queen?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_SayHello_010_00
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Soldiers take up their sword not for the those in power, but for the people. And as the champion of the people yourself, we will do all in our power to protect you, our queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f03_FLT_normal_SayHello_020_04
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
Your dedication to the people makes you a queen worthy of protection. And as the Royal Guard, I am unwavering in my determination to protect you with my life.
<WAIT>
}