//--------------------------
#SPEAKER_ID "4"
@MES_f04_004_001_020
{
<NS>Heismay<NE>
<VOICE "v_co_4210_c004">
This is <HERO_NAME>. A travelling companion of mine. She's standing in the Tournament for the Throne.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_004_001_021
{
<NS>Heismay<NE>
<VOICE "v_co_4210_c004">
This is <HERO_NAME>. A travelling companion of mine. She's standing in the Tournament for the Throne, against that knave Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f04_004_001_022 SEL 0
{
Nice to meet you.<COLOR -1>
I'm the future queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f04_004_001_022_01
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_co_1130_c001">
Nice to make your acquaintance. I'm the future queen.
<WAIT>
}