//--------------------------
#SPEAKER_ID "4"
@MES_f04_008_001_036_00
{
<NS>Heismay<NE>
<VOICE "v_f04_008_001_036_00_c004">
After all this, you are like a daughter to me yourself, you know. Your life, your ideals... I will protect them as my own.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_008_001_037_00
{
<NS>Heismay<NE>
<VOICE "v_f04_008_001_037_00_c004">
After all this, you are like a daughter to me yourself, you know. Your life, your ideals... I will protect them as my own.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_008_001_038_00
{
<NS>Heismay<NE>
<VOICE "v_f04_008_001_037_00_c004">
After all this, you are like a daughter to me yourself, you know. Your life, your ideals... I will protect them as my own.
<WAIT>
}