//--------------------------
#SPEAKER_ID "4"
@MES_f04_007_001_055
{
<NS>Heismay<NE>
<LIPSYNC>
And the one responsible stands before you now. This is my friend, <HERO_NAME>, and she will change this country!
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_007_001_072
{
<NS>Heismay<NE>
<VOICE "v_co_4151_c004">
<HERO_NAME>, and we who follow her, will light our way forward! If you live and strive with hope in your heart, then a better future is within your grasp!
<WAIT>
}