//--------------------------
#SPEAKER_ID "4"
@f04_FieldTalk_Rank06_NG_000_04
{
<NS>Heismay<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_4108_c004">
No bright ideas, either, eh? Not to worry, lass. I know I asked a lot of you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@f04_FieldTalk_Rank06_OK_000_01
{
<NS>Heismay<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_4003_c004">
A new age is dawning? What do— Oh! You mean a new ruler!
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@f04_FieldTalk_Rank06_OK_000_02
{
<NS>Heismay<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
Indeed, a new ruler will be a momentous occasion. Not even that village could avoid being swept into the tides of change.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@f04_FieldTalk_Rank06_OK_000_03
{
<NS>Heismay<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
Yes, I can see our approach now— We unveil you to them as the queen! My grandiloquence will not sway them alone.
<WAIT>
}