//--------------------------
#SPEAKER_ID "4"
@MES_f04_002_002_043
{
<NS>Heismay<NE>
<VOICE "v_co_4120_c004">
We can save this for any time when you're free, lass. I'm grateful that you'll help me, though, and I daresay... tonight I'll rest well.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_002_002_017
{
<NS>Heismay<NE>
<VOICE "v_co_4042_c004">
It's the way of the eugief, girl. We burn the bodies of the dead, leaving only bones.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_002_002_029
{
<NS>Heismay<NE>
<VOICE "v_co_4099_c004">
We've an important mission to accomplish. No room for detours of any inconvenience, girl. I can't put that burden on you.
<WAIT>
}