//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_012_000
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_4177_c004">
The day of the princess's awakening may be nearer than we realise... We've got to make our preparations before that soiree.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_013_030
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_4043_c004">
You know, since things are a bit quieter now, I ought to ask... How are you feeling, lass? Stresswise?
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_043_010
{
<NS>Heismay<NE>
<BUSTUP 9 0 0>
<VOICE "v_co_4016_c004">
I still struggle to believe it. That Rella, of all people, might have a hand in the princess's fall...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f04_FLT_normal_043_012
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Rella, of all people, connected to the princess's fall...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_044_000
{
<NS>Heismay<NE>
<BUSTUP 5 0 0>
<VOICE "v_co_4138_c004">
Rella did not deserve such cruelty, then or now. Forcing her to assassinate the princess—even threatening Junah's life to manipulate her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_051_000
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_4069_c004">
First you were Louis's subordinate, then a false princess. And now, you have awakened as Her true Highness...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_SayHello_007
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I've realised over the past year just how much a nation is defined by its people. No matter how great a queen, she alone does not a country make.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_SayHello_008
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_4091_c004">
Yet she stands for those very people, as symbol and representative.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_SayHello_009
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That the queen and those around her are of mixed tribes— It has already caused a great shift in sentiment, even for those in the rural villages.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_051_001
{
<NS>Heismay<NE>
<BUSTUP 3 0 0>
<LIPSYNC>
None have walked so strange a path as you. And after all of this, you still mean to be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_SayHello_000
{
<NS>Heismay<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_4247_c004">
Well, well. I see our queen is out on some personal business, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f04_FLT_normal_SayHello_002 SEL 0
{
Times are changing.<COLOR -1>
An outcast became ruler, too.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f04_FLT_normal_SayHello_005
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_1127_c001">
They needn't look further than the outcast who became their ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_f04_FLT_normal_SayHello_020
{
<NS>Heismay<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_4247_c004">
Well, well. I see our queen is out on some personal business, eh?
<WAIT>
}