//--------------------------
#SPEAKER_ID "5"
@MES_f05_000_001_014_02
{
<NS>Junah<NE>
<VOICE "v_f05_000_001_014_02_c005">
Oh, the key to capturing hearts, some tips and tricks for carrying yourself with dignity... Rather useful to a queen candidate, no?
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_f05_000_001_014_04
{
<NS>Junah<NE>
<VOICE "v_f05_000_001_014_04_c005">
Right? Every heart and mind has a key. And unlocking them is a skill any queen candidate should know.
<WAIT>
}