//--------------------------
#SPEAKER_ID "5"
@MES_f05_FLT_normal_041_000
{
<NS>Junah<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_5139_c005">
We murdered Louis, but the princess's curse is unbroken. We went through so much to get here, I can't help but feel conflicted.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_f05_FLT_normal_043_010
{
<NS>Junah<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_5137_c005">
I still can't believe my own sister was behind the princess's attempted murder. I knew she was hiding something, but this...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_f05_FLT_normal_052_005
{
<NS>Junah<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_5396_c005">
The Day of the Hero is around the corner... And the next ruler will be crowned. We can throw all the tantrums we want, but time waits for no one.
<WAIT>
}