//--------------------------
#SPEAKER_ID "5"
@MES_f05_FLT_playspot_001_000
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_5242_c005">
Oh, are you feeling all right, my good woman?
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_f05_FLT_playspot_001_001
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
You know, all work and no play makes a dull queen. That said, why don't you come out shopping with me?
<WAIT>
}