//--------------------------
#SPEAKER_ID "8"
@MES_f08_FLT_normal_043_010
{
<NS>Basilio<NE>
<BUSTUP 9 0 0>
<VOICE "v_co_8195_c008">
Truth is, I'm still strugglin' to believe that Lady Rella's the one who tried to assassinate the princess... She wouldn't hurt a soul.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_f08_FLT_normal_045_001
{
<NS>Basilio<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'd have figured you'd be nervous about callin' yourself the princess, yeah? Not that I'd prefer you being a shaky mess, I s'pose.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f08_FLT_normal_045_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Ain't this princessy business make you nervous?
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_f08_FLT_normal_050_010
{
<NS>Basilio<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_8009_c008">
So you were the real princess this whole time? Not just... pretending?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f08_FLT_normal_050_012
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Princess or no, I think you're shameless...
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_f08_FLT_normal_052_000
{
<NS>Basilio<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_8389_c008">
This "Day of the Hero", that's when they decide the ruler once and for all, yeah? So if we don't get Louis before then, we're dead in the water.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_f08_FLT_normal_052_005
{
<NS>Basilio<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_8008_c008">
Feels like we're not taking this serious enough, if you ask me. Can we afford to relax? The Day of the Hero's right 'round the corner, and that'll decide the next ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_f08_FLT_normal_SayHello_010
{
<NS>Basilio<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
Maybe I've got nothin' to report today, but it's not like bad people just stopped bein' bad 'cause you're queen now.
<WAIT>
}