//--------------------------
#SPEAKER_ID "8"
@MES_f08_002_001_018
{
<NS>Basilio<NE>
<VOICE "v_co_8098_c008">
Nothin' like that. <HERO_NAME> here's a comrade... no, a friend. Don't have to watch what you say, anyway. She don't care what tribe you are.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0129_001"
@MES_f08_002_001_023
{
<NS>Vinca<NE>
<VOICE "v_fm070005_fm070">
Hell, you even told her about the facility, eh...? Must be some friend, if you could talk about all that mess.
<WAIT>
}