//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_000_000
{
<NS>Neuras<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_13372_c013">
What do you think of this groundbreaking invention!? Feast your eyes, lass!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_001_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13104_c013">
What's the matter, lass? Already said you can leave the maintenance to me. Go ahead and put your feet up, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f09_FLT_normal_001_001
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
You can rest up all you like, my lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f09_FLT_normal_011_001
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Ready for battle, lass?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_012_000
{
<NS>Neuras<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_13208_c013">
...Eep! D-Don't startle me like that, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_013_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13369_c013">
What's the matter, lass? If you're feeling bored, how about joining me for a song?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_013_030
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13367_c013">
Why hello, lass. What's the matter? You want to sing with me again, do you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_021_030
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13369_c013">
What is it, lass? We're making good time here.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_021_050
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13072_c013">
Say, lass, I've got to ask. What was the inside of the Charadrius like? They've got plumbing inside, do they?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_035_000
{
<NS>Neuras<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_13017_c013">
Always knew you were a gutsy one, but to think you had it in you to claim yourself as the princess! Bravo, old chap.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_035_001
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13184_c013">
You know, this gauntlet runner was originally commissioned for Her Highness's exclusive use. I'll do what I can to make it one worthy of her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f09_FLT_normal_035_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
I'll make this runner worthy of a princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_050_000
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13375_c013">
To think, the princess herself is returning to Grand Trad in this very runner, her birthright... Feels like all the work I've put into her has really meant something!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_050_040
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13292_c013">
This strange fate you and Louis share... It's time it was brought to a proper end. If you've any loose ends to tie up first, lass, now's the time.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_200_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13124_c013">
If I were to apply the cleaning mechanism, then the runner's transmission power would... Hm? Sorry, lass, but might I have some time alone?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f09_FLT_normal_200_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Apologies, lass. Come back later.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_normal_SayHello_000_00
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13031_c013">
Hohoho! What brings her Royal Majesty here? Come to feel the wind on your face too, have you?
<WAIT>
}