//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_002_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13047_c013">
Ah, yes. How's the relic hunt going, lass?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_004_001
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Thank you for looking for them, lass. If you find any more little oddities, do sling them my way, would you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_select_OK_000
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13249_c013">
Oho, glad to hear it, lass! Much obliged!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_LP_Inspection_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oho, that you, lass? Just in time. Mind helping me out a bit?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_UniqueTalk_Night_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Hello, lass. Your own preparations going smoothly, I trust? No need to worry for our sakes—we're fully prepared for this sandflash.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_NotOccur_007
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
Apologies to Her Highness, as it's her runner, but I'd even be quite happy to be entombed on it. Though don't tell Hulkenberg, or it'll happen sooner than preferred.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_NotOccur_055
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13011_c013">
I say, you seem a little more mature these days. When I first met you, you seemed like a lass out of her depth.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_Inspection_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13200_c013">
You know, my girl, you've got a look on your face like you want to take care of the runner's reactor. How about it?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FLT_playspot_NotOccur_017
{
<NS>Neuras<NE>
<BUSTUP 10 0 0>
<LIPSYNC>
Cookery's just so bally hard to measure! How much heat for this? How long do I mix that? It's mystifying, my girl, utterly mystifying.
<WAIT>
}