//--------------------------
#SPEAKER_ID "13"
@MES_f09_003_001_025
{
<NS>Neuras<NE>
<VOICE "v_co_13088_c013">
Oho, well, it still might be! You're young, lass, still got all the time and freedom in the world for ill-advised romantic peccadillos.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_003_001_044
{
<NS>Neuras<NE>
<VOICE "v_co_13248_c013">
Hope I can keep counting on you for the rest of these relics, eh, lass?
<WAIT>
}