//--------------------------
#SPEAKER_ID "13"
@MES_f09_001_001_010
{
<NS>Neuras<NE>
<VOICE "v_f09_001_001_010_c013">
I say, lass. Did you find this for my sake?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_001_001_012
{
<NS>Neuras<NE>
<VOICE "v_f09_001_001_012_c013">
Why, I'm... I'm bally well touched. It positively chokes a man up. You may be just a lass, but you've the heart of a saint!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_001_001_014
{
<NS>Neuras<NE>
<VOICE "v_f09_001_001_014_c013">
Oh, too modest, m'girl! You went looking on old Neuras's behalf, didn't you?
<WAIT>
}