//--------------------------
#SPEAKER_ID "13"
@MES_f09_002_001_027
{
<NS>Neuras<NE>
<VOICE "v_co_13088_c013">
Pah, not even close, my lass! No, I get the feeling we'll need every last one.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_002_001_051
{
<NS>Neuras<NE>
<VOICE "v_co_13069_c013">
I'll be sure all's shipshape and ready to go. I'm counting on you to search for another relic for me! I'll be waiting, lass!
<WAIT>
}