//--------------------------
#SPEAKER_ID "13"
@MES_f09_004_001_005
{
<NS>Neuras<NE>
<VOICE "v_co_13230_c013">
Eureka...! I'm struck, lass! Thunderstruck! The Neuras of moments ago was a drivelling buffoon compared to the now! It's all thanks to you, <HERO_NAME>!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_004_001_037
{
<NS>Neuras<NE>
<VOICE "v_co_13180_c013">
Hahaha, you're not wrong! These days I get to cruise and ramble as I please, with a seat in the princess's own runner!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_004_001_019
{
<NS>Neuras<NE>
<VOICE "v_co_13050_c013">
No? They're fine things that are quite worth researching... But wielding power beyond one's limits is a fast track to madness. I've seen it happen, old girl.
<WAIT>
}