//--------------------------
#SPEAKER_ID "13"
@f09_FieldTalk_Runk05_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So. What's the matter, lass? Wait—have you come across another potential relic?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@f09_FieldTalk_Runk06_2nd_001
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So lass, that find we discussed... If you still have it on you, might I trouble you to let me see it again?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@f09_FieldTalk_Runk06_NG_008
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Apologies, lass. You hang onto this for now, eh? Show me again once you're done with pressing business. There's a place I'd like to go first.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@f09_FieldTalk_START_003
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13102_c013">
Don't fret, lass. I'll get you to that magla vortex safe and sound. That's what I'm here for.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@f09_FieldTalk_START_002
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13088_c013">
This tension in the air's to be expected, eh? What with the fight against Louis looming before us. But uh, don't get too worked up, my girl.
<WAIT>
}