//--------------------------
#SPEAKER_ID "0"
@MES_f09_FieldTalk_hour_010
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
If you'd like a chat, come find me later, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FThour_Grantrad_01_02_003
{
<NS>Neuras<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_13184_c013">
Gwahahaha! Come now lass, be honest! You'd be hard pressed to find a runner that can cross the sands as swiftly as she!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FThour_Grantrad_02_00_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13367_c013">
Oh? What's the matter, lass? Looking for a chat? Afraid things might get a bit bumpy if I take my eyes off the road...
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FThour_Martira_01_01_001
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13186_c013">
Hm? Well, don't you look intrigued! But you needn't fret, lass, just leave this one to me. This part's the most fun.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FThour_Martira_03_00_001
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<LIPSYNC>
Ah, but you're free to be as loose-lipped as you want, my lass. If you ever need help with life lessons or pursuits of the heart, I'm happy to advise!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f09_FieldTalk_hour_130
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Any troubles with love or life, I'll listen, lass!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f09_FieldTalk_hour_yaei_00
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13368_c013">
We'll camp out here today. Get a fire going for us, would you, lass?
<WAIT>
}