//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank02_000
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40007_c040">
Miss, you're here...! I really, really wanted to talk to you! I've got so much to tell you about!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank04_CARD_000
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40052_c040">
I have something to tell you, Miss...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank04_000
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40007_c040">
Oh, hi Miss...!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank04_CARD_001
{
<NS>Maria<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_40052_c040">
I have something to tell you, Miss... I want to talk to Papa, too...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank04_001_01
{
<NS>Maria<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_40007_c040">
Hey, Miss! I wanted to talk to Papa...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank05_CARD_000
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40051_c040">
I wanted to talk to you too, Miss.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank05_000
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40007_c040">
Miss, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_CARD_000
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40048_c040">
Oh... what do you think, Miss? If I could just show him this, then I'm sure he'll...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_000
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40007_c040">
Oh, Miss...!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_CARD_001
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40048_c040">
Oh... If I could just show this to him, then maybe he'll... Miss! I want to show this to that boy.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_003
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40011_c040">
Miss, um... I want to show that boy something.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_OK_001
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40060_c040">
Y-Yeah... Thank you. If you're here with me, then I'm sure everything will be okay, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_OK_002_00
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40060_c040">
Y-Yeah... Thank you. If you're here with me, then I'm sure everything will be okay, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_OK_006
{
<NS>Maria<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_40092_c040">
Thank you, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank06_OK_008
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40052_c040">
Miss... Do you have some free time right now? I want to talk to the boy I gave bread to.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank07_CARD_000
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40051_c040">
I've been waiting for you, Miss.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@f10_FieldTalk_Rank07_000
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40007_c040">
Miss, you're back! Welcome back!
<WAIT>
}