//--------------------------
#SPEAKER_ID "40"
@MES_f10_003_001_055_06
{
<NS>Maria<NE>
<VOICE "v_co_40123_c040">
When I talk to you, Miss, my stomach doesn't feel like it's all in knots anymore.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_003_001_059
{
<NS>Maria<NE>
<VOICE "v_co_40054_c040">
I should go back before Miss Fabienne gets worried. You too, Miss... Please be careful, okay?
<WAIT>
}