//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_002_010
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40051_c040">
Miss, your new friend said that I was a good girl for helping out at the shop!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_003_010
{
<NS>Maria<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_40048_c040">
Miss, your new friend is really good at singing!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_003_011
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She told me she'd teach me how to sing next time. Let's sing together, Miss.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f10_FLT_normal_003_012
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Miss, let's sing together next time!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_004_000
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40016_c040">
Miss, is it true that your gaunt-let runner can turn into a boat?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_004_010
{
<NS>Maria<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_40007_c040">
Miss! You've made more friends!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_004_011
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I wonder if you're gonna make friends with everyone in the country, Miss? And then everyone would get along!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_005_000
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40154_c040">
Miss, you made a new paripus friend this time, huh? He was kind of scary at first, but then I started talking to him, and he's really nice!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f10_FLT_normal_005_005
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Miss, I'm sure you'll win.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_005_007
{
<NS>Maria<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_40134_c040">
So... See you soon, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f10_FLT_normal_005_008
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Come back soon, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_005_010
{
<NS>Maria<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_40179_c040">
No matter what happens, you're still you to me, Miss. I'm going to keep cheering you on forever!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_006_001
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
They all have a scary look on their face and they fight all the time... Miss, if you become queen, will things go back to normal?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f10_FLT_normal_006_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Will things go back to normal if you're queen, Miss?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_006_010
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40011_c040">
Miss, this is going to be your last fight, right? Miss Fabienne said so...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_007_002
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40012_c040">
I'll be fine, Miss! Finish your important job, and we'll talk when you come home!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f10_FLT_normal_007_003
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Good luck, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_FinalBattle_000
{
<NS>Maria<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_40011_c040">
Miss... Don't you have a big job tomorrow?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_FinalBattle_010
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40011_c040">
Miss... You have a big job to do tomorrow, right?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_MAX_000
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40044_c040">
Miss... I'm strong now, so I won't cry anymore.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_CARD_000
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40007_c040">
Oh, Miss. You're here.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_CARD_OK_010
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40102_c040">
Wow, there are cliffs that are really that tall? Weren't you scared, Miss!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_CARD_OK_013
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40097_c040">
Huh!? Miss, did you really go on top of a cloud!? There was a building in the sky...? Is it in Grand Trad too?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_FLT_normal_CARD_OK_018
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40092_c040">
Thank you, Miss! I'll ask Miss Fabienne if we can hang them up on the inn's walls!
<WAIT>
}