//--------------------------
#SPEAKER_ID "40"
@MES_f10_005_001_012
{
<NS>Maria<NE>
<VOICE "v_co_40039_c040">
Um, Miss...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_005_001_044
{
<NS>Maria<NE>
<VOICE "v_co_40058_c040">
Yeah! You'll be on there too, Miss! 'Cause this is my home!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_005_001_044_01
{
<NS>Maria<NE>
<VOICE "v_co_40124_c040">
'Cause Miss, you're one of my treasures too...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_005_001_047
{
<NS>Maria<NE>
<VOICE "v_co_40087_c040">
Oh, wait... Do you know how to make a sign, Miss? Don't forget, it also has to have pretty pictures on it, or...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_005_001_056
{
<NS>Maria<NE>
<VOICE "v_co_40136_c040">
Okay, come back soon, Miss! I can't wait!
<WAIT>
}