//--------------------------
#SPEAKER_ID "40"
@MES_f10_007_001_019
{
<NS>Maria<NE>
<VOICE "v_co_40123_c040">
Miss here gave it to me! He journeys to all sorts of places.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_007_001_022
{
<NS>Maria<NE>
<VOICE "v_co_40051_c040">
It's so big outside of the capital! Miss says there's all kinds of flowers and trees nobody's seen before, and too many monsters and animals to count!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_007_001_023
{
<NS>Maria<NE>
<LIPSYNC>
When she comes to visit me, I always learn something new, so... Do you want to look at these pictures with me?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_007_001_063
{
<NS>Maria<NE>
<VOICE "v_co_40145_c040">
Miss, I made a new friend!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_007_001_073
{
<NS>Maria<NE>
<VOICE "v_co_40092_c040">
Thank you, Miss! I'm saying that cause I want to make sure I told you how I feel!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_007_001_091
{
<NS>Maria<NE>
<VOICE "v_co_40135_c040">
Thank you, Miss! See you later!
<WAIT>
}