//--------------------------
#SPEAKER_ID "40"
@MES_f10_008_002_006
{
<NS>Maria<NE>
<VOICE "v_f10_008_002_006_c040">
You'll help us serve food again, right Miss?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_008_002_011
{
<NS>Maria<NE>
<VOICE "v_f10_008_002_011_c040">
You know, all of these good things happened 'cause of you, Miss.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f10_008_002_035_02
{
<NS>Maria<NE>
<VOICE "v_f10_008_002_035_02_c040">
When you're queen, will people only cry when they're happy? Because if everybody was kind, there'd be no reason to ever feel sad...
<WAIT>
}