//--------------------------
#SPEAKER_ID "M1536_907"
@MES_f11_004_002_034
{
<NS>Ale-Stunk Man<NE>
<VOICE "v_fm117002_fm117">
Who the hell are ya, anyway? One of Catherina's fan girls? Well, get on outta here, she ain't got time for the likes of you!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1536_907"
@MES_f11_004_002_034_00
{
<NS>Ale-Stunk Man<NE>
<VOICE "v_fm117002_fm117">
Who the hell are ya, anyway? One of Catherina's fan girls? Well, get on outta here, she ain't gonna take your side!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1536_907"
@MES_f11_004_002_034_01
{
<NS>Ale-Stunk Man<NE>
<VOICE "v_fm117002_fm117">
Ahh, it's you. Thinkin' you'll be queen someday, eh? Louis is gonna crush ya under his heel, so good job wastin' all that time! Har har har!
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_004_002_073
{
<NS>Catherina<NE>
<VOICE "v_co_41045_c041">
I think you'd make a helluva better queen than I'd make of a queen, anyway.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_004_002_075_02
{
<NS>Catherina<NE>
<LIPSYNC>
I think you'd make a helluva better queen than I'd make of a queen, anyway.
<WAIT>
}