//--------------------------
#SPEAKER_ID "41"
@MES_f11_008_001_059
{
<NS>Catherina<NE>
<VOICE "v_f11_008_001_059_c041">
Because I mean, you're gonna be queen soon, yeah? Things'll really start lookin' up for us then.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_008_001_063
{
<NS>Catherina<NE>
<VOICE "v_f11_008_001_063_c041">
You'll be fiiine! You'll become queen and the world will be a better place.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_008_001_066
{
<NS>Catherina<NE>
<VOICE "v_f11_008_001_066_c041">
Though, I guess in an ideal world, we wouldn't need ruler.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_008_001_068
{
<NS>Catherina<NE>
<VOICE "v_f11_008_001_068_c041">
One queen can't make the world a better place. It takes everyone to pull that off.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_008_001_076
{
<NS>Catherina<NE>
<VOICE "v_f11_008_001_076_c041">
Queen or not, no matter what lies ahead for you, we're comrades in arms.
<WAIT>
}