//--------------------------
#SPEAKER_ID "41"
@MES_f11_004_000_003
{
<NS>Catherina<NE>
<VOICE "v_co_41192_c041">
Hey you! Yeah you, the rogue making a go at the throne! Be a good woman and leave the kingdom to me, you hear!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f11_004_000_106 SEL 0
{
I am <HERO_NAME>.<COLOR -1>
I shall be queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f11_004_000_109
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_co_1056_c001">
I am, <HERO_NAME>, the one who shall be queen!
<WAIT>
}