//--------------------------
#SPEAKER_ID "41"
@f11_FieldTalk_Rank06_000
{
<NS>Catherina<NE>
<BUSTUP 9 0 0>
<LIPSYNC>
Oh hey, just the girl I wanted to see. I been thinkin' a lot about what happened last time.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_FLT_normal_SayHello_100
{
<NS>Catherina<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_41199_c041">
Oh, well if it ain't the big woman herself! Good timing, mate, I just got back into town myself.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_FLT_normal_005_000
{
<NS>Catherina<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_41101_c041">
Hard to believe the princess's assassin was Sanctifex Forden all along...
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@f11_FieldTalk_Rank06_NG_001
{
<NS>Catherina<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_41013_c041">
Right, you're a busy girl. Don't leave me hangin' though, yeah?
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_FLT_normal_SayHello_109
{
<NS>Catherina<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_41170_c041">
But don't you worry your queen head! I'll have it all whipped up in a report for ya. Do something proper queen with it, yeah!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_FLT_NotMax1_SayHello_200
{
<NS>Catherina<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_41199_c041">
Hey there! Been a hot minute, hasn't it, <HERO_NAME>? Ah, wait, you're the queen now, ain't ya.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_FLT_NotMax1_SayHello_203
{
<NS>Catherina<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Only wish things coulda turned sunnier sooner. But why cry about the past? Good luck bein' a queen, ya rascal.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f11_FLT_NotMax1_SayHello_204
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Good luck with your queen duties!
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f11_FLT_NotMax2_SayHello_300
{
<NS>Catherina<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_41199_c041">
Hey there! Been a hot minute, hasn't it, <HERO_NAME>? Ah, wait, you're the queen now, ain't ya.
<WAIT>
}