//--------------------------
#SPEAKER_ID "43"
@MES_f12_FLT_normal_005_000
{
<NS>Alonzo<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_43046_c043">
To think it was the Sanctifex himself plotting to assassinate the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@f12_FieldTalk_Rank00_1st_006 SEL 0
{
This is worse than you know.<COLOR -1>
What if I lend a hand to your face?<COLOR -1>
Consider it a queen investment. <COLOR 1>[<CHAR_PARAM 65535 1> 2]<COLOR -1>
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@f12_FieldTalk_Rank00_1st_OK_000
{
<NS>Protagonist<NE>
<BUSTUP 0 0 0>
With my overflowing <COLOR 1><CHAR_PARAM 65535 2><COLOR -1>, I pitched some appealing ways one might benefit from having a future queen in their debt...!
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@f12_FieldTalk_Rank00_1st_OK_001
{
<NS>Alonzo<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_43001_c043">
You, the future queen? That's quite a goal. You're either a bad swindler or you suffer from delusions of grandeur.
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f12_FLT_normal_SayHello_104
{
<NS>Alonzo<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_43151_c043">
Haha, how queen an answer! Never missing an opportunity to display how capable you are— Commendable.
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f12_FLT_NotMax1_SayHello_200
{
<NS>Alonzo<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Good to see you again after so long, Your Majesty the Queen. Have you some business with this lowly swindler?
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f12_FLT_NotMax1_SayHello_202
{
<NS>Alonzo<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
You became queen without my help. That alone is proof of my incompetence.
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f12_FLT_NotMax2_SayHello_300
{
<NS>Alonzo<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Why hello there, Your Majesty the Queen! It's been quite a long time, has it not?
<WAIT>
}