//--------------------------
#SPEAKER_ID "43"
@MES_f12_001_001_034
{
<NS>Alonzo<NE>
<LIPSYNC>
I can see it already—you're the real deal, the one truly fated to be our next queen. And I can see, too, that you'll need my <i>winning strategies</i> to do it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f12_001_001_037
{
<NS>Alonzo<NE>
<LIPSYNC>
You're kind. Honest. To a fault, really. And for an upstanding chap like you to become queen, you'll need someone versed in darker, <i>greyer</i> areas. Someone like me.
<WAIT>
}