//--------------------------
#SPEAKER_ID "M0123_001"
@MES_f12_007_001_040
{
<NS>Landowner<NE>
<VOICE "v_fm127024_fm127">
Good people! This brave young woman here, <HERO_NAME>, is the one who saved my family!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0123_001"
@MES_f12_007_001_042
{
<NS>Landowner<NE>
<LIPSYNC>
She pretended to work with Cuculus and saved the victims in her clutches. Furthermore, she captured the wicked cur himself and handed her over to me!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0123_001"
@MES_f12_007_001_043
{
<NS>Landowner<NE>
<VOICE "v_fm127027_fm127">
As you all may know, she is a candidate to become the new queen! She is a true hero, one deserving of the crown!
<WAIT>
}
//--------------------------
#SPEAKER_ID "N1155"
@MES_f12_007_001_046
{
<NS>Inspired Woman<NE>
<VOICE "v_fm199001_fm199">
That girl will become queen...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f12_007_001_048
{
<NS>Alonzo<NE>
<VOICE "v_co_43192_c043">
Well, if it isn't Ms. Hero in the flesh. Look at this right mess you've got me into!
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f12_007_001_053_03
{
<NS>Alonzo<NE>
<LIPSYNC>
I could always tell you didn't want to become queen yourself, but that's not how the wheel turns. You will take the throne.
<WAIT>
}