//--------------------------
#SPEAKER_ID "46"
@MES_f13_008_001_011
{
<NS>Bardon<NE>
<VOICE "v_f13_008_001_011_c046">
Who knows, lassie... This town was everything to me. Maybe I'll just live alone for a bit in the mountains and think on it there...
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f13_008_001_059
{
<NS>Bardon<NE>
<VOICE "v_f13_008_001_059_c046">
<i>She</i> is the hero who saved this town, the one most worthy of the crown! I want us to support her... as the future Queen <HERO_NAME>!
<WAIT>
}