//--------------------------
#SPEAKER_ID "46"
@MES_f13_FLT_normal_006_001
{
<NS>Bardon<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
To think you were the princess! Well, you certainly were born in legendary times...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f13_FLT_normal_006_002
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
To think you were the princess all along...
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@f13_FieldTalk_Rank08_000
{
<NS>Bardon<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...So, ye see... I've another question I want to ask ye. You said before... that you didn't really want to be queen, didn't ye?
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f13_FLT_normal_SayHello_110
{
<NS>Bardon<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_46005_c046">
And choosing a ruler of our own will was all the inspiration we needed for change.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f13_FLT_normal_SayHello_111
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
Choosing a ruler of our own was an inspiration.
<WAIT>
}