//--------------------------
#SPEAKER_ID "46"
@MES_f13_008_002_021
{
<NS>Bardon<NE>
<VOICE "v_f13_008_002_021_c046">
And you truly believe that? Then I must devote myself to the work even more, so as not to disappoint the future queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f13_008_002_026_00
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_f13_008_002_026_00_c001">
Sure. You'll be next in line for the crown after the new queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f13_008_002_026_03
{
<NS>Bardon<NE>
<VOICE "v_f13_008_002_026_03_c046">
In a sense, I'm your senior. And I hope I'd know <i>something</i> of governing by the time you're queen...
<WAIT>
}