//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_normal_SayHello_100
{
<NS>Brigitta<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_44001_c044">
The queen herself, out browsing the shops? Ha, perhaps I need to draft up a royal certificate of appointment. Tell the world we supply goods to the royal family.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_NotMax3_SayHello_003
{
<NS>Brigitta<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_44114_c044">
Now go. A Hero Queen only sullies herself to rollick in squalor.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@f14_FieldTalk_START_001
{
<NS>Brigitta<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_44005_c044">
Well, the world looks a far cry from how it used to. But somehow, that light in your eyes is still the same... You're a funny one, girl.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_normal_SayHello_107_03
{
<NS>Brigitta<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_44133_c044">
...I know that. I only rose to this position once you became queen and shed light on what lurked in the shadows of this country.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_normal_SayHello_108
{
<NS>Brigitta<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Our new queen has changed this country for the better. However, as a former arms dealer, it would be naive to think all weapons can ever disappear from this world.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_NotMax1_SayHello_000
{
<NS>Brigitta<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_44001_c044">
It's you. I'd have thought Your Majesty the Queen would be busier, but it seems you've leisure enough to go window shopping.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_NotMax1_SayHello_003
{
<NS>Brigitta<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_44114_c044">
The next time we meet, it shall be as queen and merchant... Complete strangers.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_NotMax3_SayHello_000
{
<NS>Brigitta<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_44001_c044">
It's you. I'd have thought Your Majesty the Queen would be busier, but it seems you've leisure enough to go window shopping.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f14_FLT_NotMax3_SayHello_004
{
<NS>(Overhead Display)<NE>
<BUSTUP 0 0 0>
This is no place for a queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_NotMax2_SayHello_000
{
<NS>Brigitta<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_44001_c044">
It's you. I'd have thought Your Majesty the Queen would be busier, but it seems you've leisure enough to go window shopping.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_NotMax2_SayHello_002
{
<NS>Brigitta<NE>
<BUSTUP 8 0 0>
<LIPSYNC>
Plans that the Sanctist Church all too happily stamped into the ground, as you'd expect. If only you'd become queen a little sooner.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_FLT_normal_004_011
{
<NS>Brigitta<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
With bargaining power like that, I daresay your talents would be wasted on becoming queen. Ever considered starting up your own business?
<WAIT>
}