//--------------------------
#SPEAKER_ID "44"
@MES_f14_001_001_000_04
{
<NS>Brigitta<NE>
<VOICE "v_f14_001_001_000_04_c044">
I knew an outsider would be perfect for slipping through the cracks... Clearly you were the right woman for the job.
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_f14_001_001_009
{
<NS>Brigitta<NE>
<VOICE "v_f14_001_001_009_c044">
If you're really trying to become the next queen, I don't think it's a bad deal for you.
<WAIT>
}