//--------------------------
#SPEAKER_ID "51"
@MES_f17_008_001_017
{
<NS>More<NE>
<VOICE "v_f17_008_001_017_c051">
You have already mastered the legendary power of the Princess. Beyond that, aloft the highest treetops, is a boundary that only you can see.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_f17_008_001_047_00
{
<NS>More<NE>
<VOICE "v_f17_008_001_047_00_c051">
I truly look forward to the day where you master the power of all Archetypes, and become a Hero King: a great unifier of heroic spirits.
<WAIT>
}