//--------------------------
#SPEAKER_ID "11"
@MES_f17_003_001_001
{
<NS>Gallica<NE>
<VOICE "v_co_11165_c011">
Well? She's pretty good, isn't she?
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_f17_003_001_002
{
<NS>More<NE>
<VOICE "v_co_51072_c051">
So she is. Thanks to her, my thoughts are finally in order. While researching, I looked into where this place might truly be...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_f17_003_001_002_00
{
<NS>More<NE>
<VOICE "v_co_51072_c051">
Indeed, thanks to her, my thoughts have found order. While researching, I thought I'd look into where this place may be...
<WAIT>
}