//--------------------------
#SPEAKER_ID "3"
@MES_f50_003_001_012
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I was openly mocked when I stated I was searching for Her Highness. A particularly rude cur yelped, "Do you think that corpse took the royal yacht across the sea?"
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f50_003_001_014
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
"Maybe the princess has truly died", and "The fault lies with me, for failing to repel such an attack"...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f50_003_001_016
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_3052_c003">
Searching for Her Highness was my stated goal, but thinking on it now, perhaps I was simply looking for an appropriate place to die.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f50_003_001_017 SEL 0
{
You have allies now.<COLOR -1>
The princess is alive.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f50_003_001_020
{
<NS>Hulkenberg<NE>
<BUSTUP 2 0 0>
<LIPSYNC>
Hope is with me now. Alongside a multitude of comrades, who will fight beside me for Her Highness's sake.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f50_003_001_021
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_1094_c001">
But the princess is still alive.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f50_003_001_022
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_3081_c003">
Yes, I am thankful to learn that my despair was misplaced. She may yet still be saved— No, Her Highness will be saved, I'm sure of it.
<WAIT>
}