//--------------------------
#SPEAKER_ID "13"
@MES_f60_007_001_015
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13080_c013">
Oh, don't fuss! You're young, lass, learn to take a bit of bally gratitude.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f60_007_001_024
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13128_c013">
Frankly, lass, if the gods of the world aren't boiling mad at me yet, then this is a drop in the bucket.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f60_007_001_026
{
<NS>Neuras<NE>
<BUSTUP 11 0 0>
<VOICE "v_co_13150_c013">
W-Well, yes... A young lass like you, barely off her bottle, making a wish like that? And me, wrapped up in my own fancies. Seems a bit backward to me.
<WAIT>
}