//--------------------------
#SPEAKER_ID "5"
@MES_f60_005_001_029
{
<NS>Junah<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Being Rella's little sister, becoming a songstress, helping the princess, meeting you, and standing here now...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_f60_005_001_039
{
<NS>Junah<NE>
<BUSTUP 3 0 3>
<VOICE "v_co_5162_c005">
If you keep up this pace, who knows? Maybe one day you'll be a woman strong enough to be worthy of me. Don't keep me waiting, hm?
<WAIT>
}