//--------------------------
#SPEAKER_ID "0"
@MES_f60_003_001_023 SEL 0
{
The safety of the princess?<COLOR -1>
Everyone's safety?<COLOR -1>
More food?
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f60_003_001_024
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1089_c001">
I would assume... you wished for the safety of the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f60_003_001_028
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
At first, I considered wishing solely for Her Highness's safety, but I thought that it would be appropriate to ask for more...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f60_003_001_031
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
At first, I considered wishing solely for Her Highness's safety, but I thought that it would be appropriate to ask for more...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f60_003_001_032
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_3053_c003">
I wished not only for the princess's safety, but for you and all of our comrades. What I wished for is... <i>victory</i>.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f60_003_001_034
{
<NS>Hulkenberg<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_3174_c003">
I'd thought myself a mere knight protecting the princess, yet now I find myself under your aegis instead. To return that protection tenfold gives me new strength every day.
<WAIT>
}