//--------------------------
#SPEAKER_ID "41"
@MES_f70_010_002_019
{
<NS>Catherina<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_41056_c041">
I bet someone in charge could use some intel from far-away lands. I could get that for ya! A queen gonna need all the help she can get.
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_f70_010_002_018
{
<NS>Catherina<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Got a couple of thoughts runnin' loose in my noggin, actually. If you become queen, I think I'll journey abroad!
<WAIT>
}