//--------------------------
#SPEAKER_ID "43"
@MES_f70_011_002_008
{
<NS>Alonzo<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_43099_c043">
I'm currently planning what to do next after you're queen. I'm certain it'll be quite chaotic in this country for some time.
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_f70_011_002_025
{
<NS>Alonzo<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_43041_c043">
...I'm glad to have met you. Before we part, I have but one word of advice for my future queen.
<WAIT>
}