//--------------------------
#SPEAKER_ID "2"
@MES_f70_002_002_013
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Ahh, almost correct, Maria. We're going to fight <i>and win</i>. Then this girl here will become queen and make this a good country.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_f70_002_002_021_00
{
<NS>Strohl<NE>
<BUSTUP 4 0 0>
<LIPSYNC>
But we know that's not the case. She desires a country where the weak and helpless are culled. Everyone would know and see that, yet do nothing.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f70_002_002_009
{
<NS>Maria<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_40024_c040">
What!? Already, you ate <i>all</i> that meat!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_f70_002_002_022
{
<NS>Strohl<NE>
<BUSTUP 9 0 0>
<VOICE "v_co_2165_c002">
Still. Speaking the words is easy, but acting on them is another thing entirely. Even for a queen.
<WAIT>
}