//--------------------------
#SPEAKER_ID "5"
@MES_f70_005_002_024
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_5078_c005">
So I'll ask you when this is truly all over. After the Day of Hero, and you become queen. Then you can answer me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_f70_005_002_030
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
This flower used to represent fear and humiliation to me... But once you become queen, I hope it comes to mean "liberty".
<WAIT>
}