//--------------------------
#SPEAKER_ID "11"
@MES_f70_001_001_005
{
<NS>Gallica<NE>
<BUSTUP 11 0 0>
<VOICE "v_co_11147_c011">
...Yeah, perhaps due to being a princess, you do have a kind of nobility that just... shines through?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_f70_001_001_015
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_11569_c011">
Someone who's always fighting for the wishes and ideals of others, not her own.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_f70_001_001_017
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_11569_c011">
I think a real queen is someone who's always fighting for the wishes and ideals of others, not her own.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_f70_001_001_012
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_11081_c011">
Maybe that's what a real queen needs.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f70_001_001_013 SEL 0
{
A real queen?<COLOR -1>
What do you mean?
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f70_001_001_014
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_1003_c001">
What do you mean "a real queen"...?
<WAIT>
}