//--------------------------
#SPEAKER_ID "40"
@MES_f70_009_002_000
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40039_c040">
Um, are you sure I'm not bothering you, Miss? I know you're real busy and all...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f70_009_002_016
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40015_c040">
Right... Then you have my support, too, miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f70_009_002_017_01
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But Miss, you said you'd make a country without all that, where it'll be peaceful and kind, and nobody cries.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f70_009_002_021
{
<NS>Maria<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_40123_c040">
I want to do my best for everyone, just like Papa and Miss.
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_f70_009_002_022
{
<NS>Fabienne<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_67008_c067">
Well, you're looking very happy, Maria... Anyway, don't forget about that thing you wanted to give her, okay?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f70_009_002_024
{
<NS>Maria<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_40129_c040">
Here you go! For you, Miss!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_f70_009_002_009
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
But I know better! Once you become queen, everyone'll be happy again.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_f70_009_002_026 SEL 0
{
I'll return as the queen.<COLOR -1>
I won't lose.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f70_009_002_027
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_1125_c001">
Thank you. The next time you see me, I'll be queen.
<WAIT>
}