//--------------------------
#SPEAKER_ID "3"
@MES_f70_003_002_027
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_3035_c003">
Our time together brought about an epiphany: I do not seek a one-sided fealty, but as a knight, I wish to serve under a ruler who supports me, as I do them.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_f70_003_002_029
{
<NS>Hulkenberg<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_3115_c003">
Haha... you have my thanks. Beginning tomorrow, I shall support you... as a true knight of the queen.
<WAIT>
}