//--------------------------
#SPEAKER_ID "51"
@MES_f70_014_002_004
{
<NS>More<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_51072_c051">
Good. Spoken like a queen. In striving toward the apex of all Archetypes, you've surely marked yourself as worthy of rule.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_f70_014_002_010
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 14 0 0>
<VOICE "v_co_1164_c001">
But any other possible ruler could free you just as easily, right?
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_f70_014_002_011
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51101_c051">
Even if they could, any other ruler might only condemn me as the past king did. I, and those who believe such ideals, could be easily imprisoned once more.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_f70_014_002_022
{
<NS>More<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
I wish I could travel at your side. If the chance existed, no matter how slim, I'd take it. Though I suppose that's a dangerously insolent proposal for a queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_f70_014_002_023
{
<NS>More<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_51082_c051">
Still. Once you are queen, if ever you decide to tour the country or return to the road, please. Allow me to join you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_f70_014_002_025
{
<NS>More<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_51116_c051">
Thank you. To walk a country born anew, together with its new queen... It is like a dream. My heart bursts with anticipation.
<WAIT>
}