//--------------------------
#SPEAKER_ID "6"
@MES_f70_006_002_010
{
<NS>Eupha<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_6211_c006">
You worry too much, brother. <HERO_NAME> has us with her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_f70_006_002_011
{
<NS>Eupha<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
No matter how thorny the path she walks becomes, we are all determined to walk it beside her!
<WAIT>
}
//--------------------------
#SPEAKER_ID "50"
@MES_f70_006_002_024
{
<NS>Edeni<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Indeed. We were talking about the swarms of vicious man-eating sharks that teem in the night sea. I was telling her that if someone were to be thrown in, they'd die instantly.
<WAIT>
}
//--------------------------
#SPEAKER_ID "50"
@MES_f70_006_002_027
{
<NS>Edeni<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
Haha... Well, didn't you say you have something to give her?
<WAIT>
}