//--------------------------
#SPEAKER_ID "46"
@MES_f70_012_002_023
{
<NS>Bardon<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_46056_c046">
Here's what I think. A single queen cannot possibly listen to each and every one of her subjects.
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f70_012_002_016
{
<NS>Bardon<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_46102_c046">
A queen chosen by the people will be different from any other ruler we've ever had. Every citizen'll expect something from ye, and you'll feel a duty to live up to that expectation.
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f70_012_002_018
{
<NS>Bardon<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_46012_c046">
And you'll be queen of all this. How do ye think you're gonna possibly hear all the people's opinions?
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f70_012_002_024
{
<NS>Bardon<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
And I can govern this town according to whatever your queen wishes may be. And I can collect my people's opinions and transmit them to you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f70_012_002_025
{
<NS>Bardon<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_46004_c046">
So that way, the queen and the people can have a direct connection to each other. We just need other leaders to follow suit!
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_f70_012_002_027
{
<NS>Bardon<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_46141_c046">
I believe you'll be a righteous queen, and many others behind you do too.
<WAIT>
}