//--------------------------
#SPEAKER_ID "13"
@MES_f70_008_002_018
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13186_c013">
This world is full of inconveniences and irrationalities, what? Well, my lass, that's what I intend to change—one invention at a time!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f70_008_002_028_00
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13070_c013">
You hear me, lass? Don't you falter now.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_f70_008_002_024
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
But soon enough, you'll be crowned queen, and that'll be that! But you do know the road ahead is only going to be bumpier, don't you?
<WAIT>
}