//--------------------------
#SPEAKER_ID "2"
@MES_Follower_General_Invitation_STROLL_03
{
<NS>Strohl<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_2152_c002">
Perhaps I should discuss this with her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_Follower_General_Invitation_STROLL_04
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_2152_c002">
I'm sure she would listen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_Follower_General_Invitation_STROLL_05
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_2152_c002">
Maybe I should ask her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_Follower_General_Invitation_STROLL_06
{
<NS>Strohl<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_2124_c002">
I rely on her too much... I'm just...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_Follower_General_Invitation_STROLL_07
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_2106_c002">
I wonder if she'd come with me...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_Follower_General_Invitation_STROLL_FinalBattle
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Stroll_stress_01_c002">
And with this, my journey with her will come to an end...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_Follower_General_Invitation_STROLL_SayHello
{
<NS>Strohl<NE>
<BUSTUP 10 0 0>
<VOICE "v_co_2157_c002">
She is truly something...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_Follower_General_Invitation_HULKENBERG_02
{
<NS>Hulkenberg<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_Dpv_PC_Hulkenberg_thought_01_c003">
Perhaps I should discuss this with her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_Follower_General_Invitation_HULKENBERG_08
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_3157_c003">
I should let her know...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_Follower_General_Invitation_HAIZAME_03
{
<NS>Heismay<NE>
<BUSTUP 9 0 0>
<VOICE "v_co_4146_c004">
Perhaps the captain would lend me her strength...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_Follower_General_Invitation_HAIZAME_FinalBattle
{
<NS>Heismay<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_4280_c004">
Perhaps I should invite her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_Follower_General_Invitation_JUNUS_02
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_5162_c005">
I wonder if she'd join me for a little break?
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_Follower_General_Invitation_JUNUS_03
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_5111_c005">
I wonder if she'd listen to what I have to say...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_Follower_General_Invitation_JUNUS_04
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_5162_c005">
She <i>would</i> make a good escort...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_Follower_General_Invitation_JUNUS_08
{
<NS>Junah<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_5162_c005">
I wonder if she remembers our promise...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_Follower_General_Invitation_JUNUS_FinalBattle
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_5223_c005">
It's foolish, but I wonder if she'd hear my last request...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_Follower_General_Invitation_JUNUS_SayHello
{
<NS>Junah<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_5212_c005">
I'm sure she hasn't changed a bit...
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_Follower_General_Invitation_EUPHA_03
{
<NS>Eupha<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_6202_c006">
I'd like to go again with her if I could...
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_Follower_General_Invitation_EUPHA_07
{
<NS>Eupha<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_6218_c006">
I should discuss things with her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_Follower_General_Invitation_EUPHA_08
{
<NS>Eupha<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_6156_c006">
I have something I want to ask her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_Follower_General_Invitation_BASILIO_03
{
<NS>Basilio<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_8169_c008">
I do kinda owe her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_Follower_General_Invitation_BASILIO_04
{
<NS>Basilio<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_8152_c008">
I'm worried 'bout her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_Follower_General_Invitation_BASILIO_05
{
<NS>Basilio<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_8043_c008">
Maybe she wouldn't mind lendin' me a hand...
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_Follower_General_Invitation_BASILIO_07
{
<NS>Basilio<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_Dpv_PC_Basilio_gripe_01_c008">
If we do this, then she...
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_Follower_General_Invitation_NEUEIRUS_03
{
<NS>Neuras<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_13123_c013">
I told her to give it a bash if she had the chance, but how's that working out for her?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_Follower_General_Invitation_NEUEIRUS_04
{
<NS>Neuras<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_13031_c013">
...Don't tell me she's forgotten?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_Follower_General_Invitation_MARIA_02
{
<NS>Maria<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_40011_c040">
I wonder how Miss is doing... But I can't ask Miss Fabienne...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_Follower_General_Invitation_MARIA_03
{
<NS>Maria<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_40011_c040">
I wonder if Miss will come visit again...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_Follower_General_Invitation_MARIA_05
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40115_c040">
I wanna talk with Miss. I miss her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_Follower_General_Invitation_MARIA_06
{
<NS>Maria<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_40012_c040">
I wonder if Miss would help me...
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_Follower_General_Invitation_MARIA_08
{
<NS>Maria<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_40007_c040">
Miss'll be so surprised!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_Follower_General_Invitation_MARIA_FinalBattle
{
<NS>Maria<NE>
<BUSTUP 9 0 0>
<VOICE "v_co_40011_c040">
It'll all be okay... right, Miss...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_Follower_General_Invitation_CATHELINA_07
{
<NS>Catherina<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_41104_c041">
I wonder if she could give me some advice...
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_Follower_General_Invitation_CATHELINA_FinalBattle
{
<NS>Catherina<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_41099_c041">
That girl... She's keepin' her chin up, ain't she?
<WAIT>
}
//--------------------------
#SPEAKER_ID "41"
@MES_Follower_General_Invitation_CATHELINA_SayHello
{
<NS>Catherina<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_41200_c041">
I wonder if that guy—er, I guess she's the queen now—is doing all right...
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_Follower_General_Invitation_ARONZO_02
{
<NS>Alonzo<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_43005_c043">
I'd like to know more about her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_Follower_General_Invitation_ARONZO_06
{
<NS>Alonzo<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_43146_c043">
Once she arrives, I will set the cogs in motion...
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_Follower_General_Invitation_ARONZO_07
{
<NS>Alonzo<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_43151_c043">
I've made up my mind. All that's left is for her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_Follower_General_Invitation_ARONZO_FinalBattle
{
<NS>Alonzo<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_43145_c043">
Ah, I knew I was right to have faith in her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "43"
@MES_Follower_General_Invitation_ARONZO_SayHello
{
<NS>Alonzo<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_43145_c043">
She's the one who deceived me most...
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_Follower_General_Invitation_BARDON_03
{
<NS>Bardon<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_46137_c046">
There's something I wish to speak with her about.
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_Follower_General_Invitation_BARDON_04
{
<NS>Bardon<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_46142_c046">
There's something I'd like her to look at...
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_Follower_General_Invitation_BERGITTA_02
{
<NS>Brigitta<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_44001_c044">
She seemed promising, but...
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_Follower_General_Invitation_BERGITTA_03
{
<NS>Brigitta<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_44132_c044">
I wonder if she'll come again... If she does...
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_Follower_General_Invitation_BERGITTA_04
{
<NS>Brigitta<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_44114_c044">
I doubt I'll ever see her again...
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_Follower_General_Invitation_BERGITTA_05
{
<NS>Brigitta<NE>
<BUSTUP 8 0 0>
<VOICE "v_co_44114_c044">
She doesn't need to come here any longer... And yet...
<WAIT>
}
//--------------------------
#SPEAKER_ID "44"
@MES_Follower_General_Invitation_BERGITTA_07
{
<NS>Brigitta<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_44051_c044">
I need to tell her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Follower_General_Invitation_MOR_02
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51002_c051">
Hmm, I wonder if she's made any progress on the task I've asked of her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Follower_General_Invitation_MOR_05
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51268_c051">
I wonder if she'll visit again...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Follower_General_Invitation_MOR_08
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51130_c051">
As her growth nears its conclusion, so too will the mystery which surrounds me...
<WAIT>
}