//--------------------------
#SPEAKER_ID "51"
@Daily_Message_04_1
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51311_c051">
Time marches on, and the age of a new ruler draws nearer...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@Daily_Message_05
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51310_c051">
The Day of the Hero draws near, which shall see the crowning of a new ruler... <LIMIT_TO_HADES><MULTI> days remain</MULTI><SINGLE> day remains</SINGLE>.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@Daily_Message_06
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51224_c051">
Finally, today, the new ruler shall be decided...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@Daily_Message_07
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51234_c051">
Quietude descended once again upon the Royal Capital, and the day of the new queen coronation arrived...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@Daily_Message_08
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_51235_c051">
One year has passed since the arrival of the new queen...
<WAIT>
}