//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Dep_Gra_Grand_00
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar023_c051">
The gauntlet runner departs for the Royal Capital Grand Trad,
largest city in all the kingdom, and the fateful place where her journey began.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Arr_AltToGra_01
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar095_c051">
She does not return within the hush of teleportation magic as a mere wanderer,
but with the fanfare required of one who would claim to be princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Arr_AltToGra_02
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar096_c051">
She is a girl no more. She stands now on equal footing with Louis,
and her triumphant descent over the capital will finally make that known.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Arr_AltToGra_03
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar097_c051">
...Whether or not her gambit is only a means to an end.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Dep_Gra_oukyu_01
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar112_c051">
They must fight to stave off the disaster Louis calls forth.
What does the stone-faced king think now of his own daughter's resolute determination?
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Arr_Gra_oukyu_00_02
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar115_c051">
The gauntlet runner arrives at the entrance, at last marking
the princess's fateful return to the place she was once forced to abandon.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Arr_Gra_oukyu_01_01
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar117_c051">
The princess and her allies advance through the magla-tinted sky
and arrive at the royal palace. They set foot into a nightmare made manifest.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_Narration_Dep_Gra_Fort_00
{
<NS>More<NE>
<BUSTUP 0 0 0>
<VOICE "v_tr_nar028_c051">
The girl, having successfully infiltrated the royal army as a soldier,
now proceeds by carriage north towards a fortress tower.
<WAIT>
}