//--------------------------
#SPEAKER_ID "0"
@MES_d02_002_000_001_001
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The fact she's young doesn't matter as long as she's powerful, like Louis. So how 'bout it? You match up?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_002_000_001_006
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Sure, maybe she's strong. But if we're talking strength, Louis and his lot are still a sight stronger.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_002_000_001_008
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1379004_m1379">
Bold words, girl. Then again, she's got her own gauntlet runner she's racin' around in... Not bad for her age.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_002_000_001_009
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Young as she is, she's pretty good. Like the Hero King from the tales.
<WAIT>
}