//--------------------------
#SPEAKER_ID "0"
@MES_d02_003_000_002_006
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
How is favouring a minor tribe like the elda going to change anything? Hardly a solution, is it? The girl's all talk.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_003_000_002_009
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She's playing for the criers a bit, but I've heard the Hero Kings of old were of various tribes. Perhaps it's not as bad as it sounds.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_003_000_002_012
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Oh, please. On sheer capability, Louis is head and shoulders above this girl and the others.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_003_000_002_000
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1370005_m1370">
An elda queen? There's no way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_003_000_002_001
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To represent a country of mostly clemar, the ruler should also be clemar, don't you think?
<WAIT>
}