//--------------------------
#SPEAKER_ID "0"
@MES_d02_102_000_002_012
{
<NS>Flabbergasted Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Huh? Isn't Lina agreeing with her argument?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_102_000_002_018
{
<NS>Flabbergasted Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Lina's got some damn good confidence. That girl on the other hand, she comes off as weak...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_102_000_002_023
{
<NS>Sceptical Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Right? <HERO_NAME> lacks vision. Makes me think twice about supporting her...
<WAIT>
}