//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_000_009
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
No, no, no, she's spouting platitudes to win our favour. The rest of the country would have her head...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_000_011
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1317011_m1317">
Sounds nice and all, but how would she accomplish it? Not that I'm against the idea...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_000_000
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1357002_m1357">
Deciding a new ruler, eh? Honestly, I don't care what happens outside our village.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_000_001
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Right. What good does you becoming queen do for us? What can you do?
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_d02_004_000_000_007
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 12 0 0>
<VOICE "v_co_1154_c001">
When I become queen, the Dragon God will become the deity of the state religion!
<WAIT>
}