//--------------------------
#SPEAKER_ID "85"
@MES_d02_102_000_000_001
{
<NS>Loveless<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Hey, wait! I know you! You're that chump who says she'll "help anyone in need" aren't ya!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_102_000_000_023
{
<NS>Flabbergasted Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She's just making things up on the spot for publicity. At least Loveless has original ideas...
<WAIT>
}