//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_004_000
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1391001_m1391">
Ever since your <i>true</i> form got revealed, there's been more humans outside the city, riots inside, and a trail of death in your wake, you bloody false princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_004_012
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Still, surprised she hasn't thrown in the towel yet. Thought her "help anyone in need" line was rubbish, but s'pose not...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_d02_001_000_004_010
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 12 0 0>
<VOICE "v_co_1378_c001">
Listen, I want to become queen so that I can fulfil my duty and save everyone! I don't want any more innocents to die!
<WAIT>
}