//--------------------------
#SPEAKER_ID "0"
@MES_d02_103_000_003_013
{
<NS>Flabbergasted Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
<HERO_NAME> seems like she has nothing to say to counter that... Did she just come here to promote Louis, or what?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_103_000_003_018
{
<NS>Flabbergasted Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
<HERO_NAME> is just showing us how weak her ideas are...
<WAIT>
}