//--------------------------
#SPEAKER_ID "0"
@MES_d02_005_000_000_005
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1362003_m1362">
I knew it, she intends to oppress Sanctists... If she takes the crown, what can we believe in?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_005_000_000_001
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Do you intend to suppress Sanctism as queen!? You're not going to protect the pagan faith, are you?
<WAIT>
}