//--------------------------
#SPEAKER_ID "0"
@MES_d02_104_000_013
{
<NS>Glum Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I was rooting for <HERO_NAME> because she's got quite a reputation, but it seems this ishkia fellow has got her beat in terms of intellect.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_104_000_017
{
<NS>Nodding Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
True. I want a ruler who's not just good for me, but can ensure that my kids will be taken care of as well.
<WAIT>
}