//--------------------------
#SPEAKER_ID "0"
@MES_d02_102_000_001_013
{
<NS>Nodding Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Roger knows what it's like to earn a living. That <i>child</i> needs to grow up if she wants my support.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_102_000_001_018
{
<NS>Nodding Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
The girl's made a good point, but Roger is talking in circles around her...
<WAIT>
}