//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_000_005
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1320003_m1320">
Oh come off it. Is such a thing even possible? She's just saying what she thinks we want to hear!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_000_012
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Awfully vague. Is that the best idea she's got?
<WAIT>
}