//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_002_009
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Easy igniter access is a pipe dream... Makes you wonder if she put any thought at all into the idea.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_002_012
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She said "as weapons", you dolt! S'pose that means she'd loosen restrictions on daily use?
<WAIT>
}