//--------------------------
#SPEAKER_ID "0"
@MES_d02_003_000_000_012
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
She's just saying what we want to hear. Can't trust someone who says any mad idea that pops into her head...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_003_000_000_001
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If you're made ruler, what'll you do about this kingdom alliance system? If you're in favour of it, we need to hear why!
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_d02_003_000_000_010
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 12 0 0>
<VOICE "v_co_Dpv_PC_HERO_reply_01_c001">
When I'm queen, I'll return independence to the vassal states!
<WAIT>
}