//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_003_000
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1339014_m1339">
You got some nerve, showin' your face again! Rotten bastard, only thing you're the princess of are the humans! I'm sick and tired of your lies!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_003_006
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
To be honest, I wanted to believe the rumours about her being the princess were true. Looks like she's still no match for Count Louis, though.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_001_000_003_009
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Here I thought that sham of a princess was all talk... Might be worth considering some of this.
<WAIT>
}