//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_001_006
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
So any hope of change gets dashed because old folks like things how they are now? Nothing will change even if this girl becomes queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_001_000
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<VOICE "v_en_1382005_m1382">
You can be queen of whatever you like, but we like the island just the way it is.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_001_001
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
We're not looking to change things. As queen, would you leave us in peace?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_004_000_001_009
{
<NS>Audience<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'm interested in the other regional cultures. I'd be happy if the ruler became the bridge that connects the islands to the outside world!
<WAIT>
}