//--------------------------
#SPEAKER_ID "0"
@MES_d02_103_000_000_018
{
<NS>Flabbergasted Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
<HERO_NAME>'s right, but Rudolf's still managing to corner her in this argument. How is he doing that?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_103_000_000_023
{
<NS>Shrugging Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
People are free to dream as they please, but I find the girl's dreams more appealing than Rudolf's.
<WAIT>
}