//--------------------------
#SPEAKER_ID "97"
@MES_d02_103_000_002_001
{
<NS>Jin<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
...She may have briefly had the spotlight, but a child is nothing in the end.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_103_000_002_013
{
<NS>Flabbergasted Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I want to say, "don't fall for it" when it comes to Jin, but isn't <HERO_NAME> pushing the same rhetoric with her daft "help anyone in need" mantra?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_d02_103_000_002_018
{
<NS>Nodding Spectator<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
<HERO_NAME>'s rather wet behind the ears, but it makes me want to support her. If anyone's a swindler here, it's Jin.
<WAIT>
}
//--------------------------
#SPEAKER_ID "97"
@MES_d02_103_000_002_021
{
<NS>Jin<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_97010_c097">
You doubt me because I am a nidia, good lady? See this, everyone? This is the exact type of prejudice I vow to combat!
<WAIT>
}