//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_001_002_004
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13108_c013">
No lass, because I designed it to purr, not roar. Is there nothing else catching your attention?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_001_002_006
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13031_c013">
Oh, did those come out of the runner? Why yes, that would put us in quite a predicament! Good eye, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_001_002_008
{
<NS>Neuras<NE>
<BUSTUP 10 0 0>
<VOICE "v_co_13367_c013">
That's not fire, lass. It's just the mouse repellent. Anything else you can observe?
<WAIT>
}