//--------------------------
#SPEAKER_ID "0"
@MES_d08_008_003_005_002 SEL 0
{
Just trying to do good.<COLOR -1>
I'm a woman of my word.<COLOR -1>
Lots of people need help.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_d08_008_003_005_004
{
<NS>Protagonist (Normal)<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_1163_c001">
I want to be a woman who keeps her word.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_d08_008_003_005_006
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I've been thinking about it for some time... about the country we'll build once the princess wakes up.
<WAIT>
}