//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_027_001
{
<NS>Neuras<NE>
<BUSTUP 8 0 0>
<LIPSYNC>
But imagine my surprise when the door wasn't locked and there was no one inside! Tell me I'm not losing my mind, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_027_003_00
{
<NS>Neuras<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_13037_c013">
...Fired!? Listen lass, I know I haven't been... Er, "tired" you say? O-Oh, yes, all that driving... Perhaps I really am.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_027_005_00
{
<NS>Neuras<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_13150_c013">
If so, you might have spared me the thought, lass! I shouldn't need to fear for my life just to relieve myself!
<WAIT>
}