//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_001_001_001
{
<NS>Neuras<NE>
<BUSTUP 1 0 5>
<LIPSYNC>
So today, we're on cleaning duty until it shines, lass! That should breathe some life back into the reactor.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_001_001_006
{
<NS>Neuras<NE>
<BUSTUP 10 0 0>
<VOICE "v_co_13031_c013">
Whoa, whoa, whoa! Are you trying to rust her before her time!? No no no, this is not wet work, lass. Try a dry cloth.
<WAIT>
}