//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_002_028_005_00
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13182_c013">
Words I've heard countless times before, yes lady, yet I'm afraid I still bear no candle to you. After all, you're the one who has convened this grand congress of misfits around us!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_002_028_001
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Our newest ally is a former member of the Shadowguard turned fugitive... and a eugief at that. Y'know, my girl, you really are a strange one.
<WAIT>
}