//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_026_000
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13200_c013">
How's it, lass? The runner comfortable enough for your liking? Half the time spent travelling will be in here, you know. Interior's not too shabby?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_026_001
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
You might say it's modest for a runner designed to cart Her Highness about, but I assure you, the budget went into <i>speed</i>.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_026_003_00
{
<NS>Neuras<NE>
<BUSTUP 6 0 0>
<VOICE "v_co_13150_c013">
B-B-But the princess wasn't there to say otherwise, and... Well, if no one's paying attention, what choice did I have but to make a few... calls?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_026_004_00
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_13050_c013">
Deck the thing out with fancy gidgets and gizmos and you'd be sick of them in three days, lass! No, here we ride on our dreams, and isn't that grand?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_008_000_026_006
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
With the princess missing, you could say the purse strings loosened in more ways than one, and I could give her the attention she deserved.
<WAIT>
}