//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_000_008
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13088_c013">
I should say not! I'm counting on you to do it right, lass. After all, if something breaks, we're all scuppered!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_000_021
{
<NS>Neuras<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_13250_c013">
No sense being a miser about it, lass. I couldn't keep it secret if I tried! Isn't it always better for your work to make the world a little more interesting?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_000_030
{
<NS>Neuras<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_13097_c013">
Of course! That would certainly be ideal! But I'm glad that if anyone can do it, it's you, lass.
<WAIT>
}