//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_001_000_004
{
<NS>Neuras<NE>
<BUSTUP 10 0 0>
<VOICE "v_co_13031_c013">
Come on, lass... Is that all the oil you can spare? Don't skimp, now, or they'll be fussy again before you know it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d08_010_001_000_008
{
<NS>Neuras<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_13004_c013">
That's the ticket, lass! Perfectly dolloped. Heh, that's the kind of work that'll get you in the machinery's good books.
<WAIT>
}