//--------------------------
#SPEAKER_ID "3"
@MES_d10_001_000_000_003
{
<NS>Hulkenberg<NE>
<BUSTUP 5 0 0>
<VOICE "v_co_Dpv_PC_Hulkenberg_talk_02_c003">
Indeed. We mustn't allow him to damage Her Highness's runner. Let's go!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d10_001_000_000_010
{
<NS>Neuras<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_13375_c013">
Oho! Bally good work out there, lass! No one's getting their hands on this ship under your watch, eh!
<WAIT>
}