//--------------------------
#SPEAKER_ID "13"
@MES_d12_000_000_034
{
<NS>Neuras<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_13220_c013">
Perfect, I've just finished my drawing! Take it, lass. I trust that you will deliver it into appreciative hands. Alright then, last one back to the runner gets saddled with kitchen patrol!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_d12_000_000_005
{
<NS>Neuras<NE>
<BUSTUP 3 0 0>
<LIPSYNC>
Really use those eyes of yours, my girl! See how each grain is clear as air? That means it's glass!
<WAIT>
}