//--------------------------
#SPEAKER_ID "11"
@dinner_plan_03_00_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11531_c011">
Right. The princess's fate is riding on us. We should make sure that our Archetypes are ready for anything.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@dinner_plan_03_01_004
{
<NS>Hulkenberg<NE>
<BUSTUP 7 0 0>
<VOICE "v_co_3396_c003">
It is our only means to save Her Highness... We <i>must</i> succeed! Let us make certain that our Archetypes are prepared for the task.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@dinner_plan_03_04_002
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
This plan is a real tightrope act, but we all knew that saving the princess would be a dangerous task. Let's be sure that our Archetypes are ready for whatever Louis throws at them.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@dinner_plan_04_02_002
{
<NS>Junah<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It's not just our lives on the line, but the princess's as well! We've got to get that lance!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@dinner_plan_06_04_001
{
<NS>Hulkenberg<NE>
<BUSTUP 4 0 0>
<VOICE "v_co_3420_c003">
The Day of the Hero is finally upon us. One way or another, the new ruler will be chosen, at long last...
<WAIT>
}