//--------------------------
#SPEAKER_ID "4"
@dinner_archetype_00_31_003
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
With all the time <HERO_NAME> has spent with the Commander Lineage, the entire country is now but a chess board before her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@dinner_archetype_00_42_001
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11066_c011">
Oh, right! <HERO_NAME>, looks like your Princess rank has improved.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@dinner_archetype_00_42_002
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Heroic Embodiments of the Princess not only excel at both magic and swordplay, but allow you to utilise a wide variety of equipment.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@dinner_archetype_00_43_002
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
That's the ultimate level of Heroic Embodiments of the Princess... Your level of mastery proves that you're a real queen among kings.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@dinner_archetype_00_43_003
{
<NS>Gallica<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_11145_c011">
A mere seeker, with nothing to her name, overcomes numerous trials to become queen... Mark my words: in ages to come, historians and poets alike will all retell your story.
<WAIT>
}