//--------------------------
#SPEAKER_ID "3"
@dinner_status_02_02_004
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_3043_c003">
Regardless of what obstacles they throw our way, I am certain we <i>will</i> reach Louis's quarters. The formula for the curse bedevilling Her Highness must be found.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@dinner_status_04_02_005
{
<NS>Basilio<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_Dpv_PC_Basilio_talk_18_c008">
'Ey, since you're the princess and all, you wouldn't happen to remember the most direct route to the other King's Servants, would ya?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@dinner_status_04_02_006
{
<NS>Hulkenberg<NE>
<BUSTUP 8 0 0>
<LIPSYNC>
Even if she did possess such a convenient memory, 'twould do us little good now. The palace has changed from the one I knew.
<WAIT>
}