//--------------------------
#SPEAKER_ID "5"
@dinner_quest_00_100_002
{
<NS>Junah<NE>
<BUSTUP 11 0 0>
<LIPSYNC>
Obvious or not, it's an understatement. Far as I'm concerned, only a fool would deny her qualifications for the job now.
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@dinner_quest_00_100_003
{
<NS>Eupha<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
She possesses not only martial might, but strength of heart. Those are the qualities that make her a most impressive leader.
<WAIT>
}