//--------------------------
#SPEAKER_ID "3"
@morning_status_02_00_002
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
We must reclaim the formula without raising suspicion... then at long last, we will finally have the means to break the princess's curse.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@morning_status_02_00_003
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11531_c011">
The princess's fate is in our hands. This plan is risky, but we have to see it through.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@morning_status_02_01_002
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Indeed, we cannot put this task off any longer... The princess's life will be forfeit if we fail to steal the curse's formula.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@morning_status_02_01_003
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
I'm not just going to sit back and watch as the princess dies and Louis usurps the throne. No chance. We need to do something.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@morning_status_02_02_002
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If we miss this opportunity, there's no telling when we'll get another chance. I worry that the princess may not be able to hold out that long...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@morning_status_02_02_003
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
All that we have accomplished so far will be for nought if we miss our deadline! Saving Her Highness is our ultimate objective, and our success hinges on acquiring that formula!
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@morning_status_02_60_004
{
<NS>Strohl<NE>
<BUSTUP 10 0 0>
<VOICE "v_co_2105_c002">
All we can do now is hope that the operation goes off without a hitch. This one will be a real tightrope act, but if we can't pull this off, then we have no hope of ever saving the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@morning_Journey_02_53_005
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11629_c011">
<DAY_LIMIT><MULTI> days</MULTI><SINGLE> day</SINGLE> left until the soiree. We're this close to getting our hands on a way to break the princess's curse...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@morning_status_03_01_002
{
<NS>Gallica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Getting killed wouldn't even be the worst of it. We need to hurry so that we can save the princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@morning_status_03_05_002
{
<NS>Junah<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
It's not just our lives on the line, but the princess's as well! We can't dawdle any longer!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@morning_status_04_05_002
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
This is where all will be settled. Let us leave no intention unrealised—the princess would want it that way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@morning_status_longtrip_06_002
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
If we're laying out our long-term plans, then we should also work to raise the profile of our illustrious captain, and bring down more of the competing candidates who stand in her way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@morning_status_05_01_002
{
<NS>Hulkenberg<NE>
<BUSTUP 9 0 0>
<LIPSYNC>
Indeed... but if we go as we are now, Louis will undoubtedly become the next king. Allowing that to pass is tantamount to declaring a death sentence for the entire nation...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@morning_status_05_60_002
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Tomorrow, we take on Louis, and the next day, the new ruler will be decided. The world Louis wants must never come to be... That much is certain.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@morning_status_05_60_004
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_4192_c004">
Let us live well on this final day, so that no matter how the new ruler is decided, we may greet the dawn with a smile in our hearts.
<WAIT>
}