//--------------------------
#SPEAKER_ID "11"
@Dpv_PC_Gallica_palsy_01
{
<NS>Gallica<NE>
<VOICE "v_du_Dpv_PC_Gallica_palsy_01_c011">
<REPORT 0 7 0 0 0>
You've gone numb! Someone help her!
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@Dpv_PC_Haizame_plhp75_02
{
<NS>Heismay<NE>
<VOICE "v_du_Dpv_PC_Haizame_plhp75_02_c004">
<REPORT 0 0 0 0 0>
Look to yourself, lass. We'll hold the line.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@Dpv_PC_Haizame_callplhp25_01
{
<NS>Heismay<NE>
<VOICE "v_du_Dpv_PC_Haizame_callplhp25_01_c004">
<REPORT 0 7 0 0 0>
Heal up, lass! We can't have you dying on us!
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@Dpv_PC_Haizame_calltreasure_02
{
<NS>Heismay<NE>
<VOICE "v_du_Dpv_PC_Haizame_calltreasure_02_c004">
<REPORT 0 0 0 0 0>
Do you like treasure, lass? I think you're in luck.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@Dpv_PC_Mooselk_frost_03
{
<NS>Grius<NE>
<VOICE "v_du_Dpv_PC_Mooselk_frost_03_c010">
<REPORT 0 4 0 0 0>
Frostbite... Don't let this be my end, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@Dpv_PC_Mooselk_plhp75_03
{
<NS>Grius<NE>
<VOICE "v_du_Dpv_PC_Mooselk_plhp75_03_c010">
<REPORT 0 5 0 0 0>
Watch your health, lass! 
Can't have you dropping.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@Dpv_PC_Mooselk_callplhp25_01
{
<NS>Grius<NE>
<VOICE "v_du_Dpv_PC_Mooselk_callplhp25_01_c010">
<REPORT 0 7 0 0 0>
Don't push your limits, lass. Heal.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@Dpv_PC_Mooselk_hp75_02
{
<NS>Grius<NE>
<VOICE "v_du_Dpv_PC_Mooselk_hp75_02_c010">
<REPORT 0 8 0 0 0>
Keep an eye on your allies' health, lass.
<WAIT>
}