//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0003_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0003_001_c011">
<REPORT 1 5 0 0 1>
The Captain's on her last legs! Someone get her healed up!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0004_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0004_001_c011">
<REPORT 1 5 0 0 1>
Strohl can't take any more! Someone heal her!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0006_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0006_001_c011">
<REPORT 1 5 0 0 1>
Heismay's in real danger! She needs healing, now!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0051_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0051_001_c011">
<REPORT 1 8 0 0 1>
The Captain's sickened! Her abilities are down and healing magic can't help her!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0067_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0067_001_c011">
<REPORT 1 8 0 0 1>
The Captain's paralysed!? We're in trouble if she can't move...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0083_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0083_001_c011">
<REPORT 1 8 0 0 1>
The Captain's been hit with a hex! If she attacks, she's getting hurt too!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0115_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0115_001_c011">
<REPORT 1 8 0 0 1>
The Captain's frozen! Her attacks are gonna be a lot weaker!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0131_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0131_001_c011">
<REPORT 1 8 0 0 1>
The Captain's been charmed! She can't tell who's friend and who's foe!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0147_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0147_001_c011">
<REPORT 1 8 0 0 1>
The Captain's dazed! She's gonna have a hard time landing hits!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0163_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0163_001_c011">
<REPORT 1 8 0 0 1>
The Captain's lost her memory! She can't use any skills!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL002_0211_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL002_0211_001_c011">
<REPORT 1 8 0 0 1>
The Captain's anxiety is overwhelming her! We can't let her get hit!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL005_0003_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL005_0003_001_c011">
<REPORT 1 8 0 0 1>
The Captain's down!? Someone, help her back up!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL005_0020_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL005_0020_001_c011">
<REPORT 1 5 0 0 1>
The Captain's hurt bad! Let's get her some healing!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_SUP01_BTL005_0036_001
{
<NS>Gallica<NE>
<VOICE "v_br_SUP01_BTL005_0036_001_c011">
<REPORT 1 8 0 0 1>
The Captain's fighting her anxiety, and they're targeting her!
<WAIT>
}