//--------------------------
#SPEAKER_ID "M2136_002"
@MES_e01_007_001_008
{
<NS>Gossipy Lady<NE>
<VOICE "v_e01_007_001_008_m028">
But it's just like the princess, isn't it? They say he was attacked in the dead of night! A war of succession is coming, I tell you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1036_001"
@MES_e01_007_001_017
{
<NS>Resting Soldier<NE>
<VOICE "v_e01_007_001_017_m030">
We'd not have to ask, if the princess was still alive.
<WAIT>
}