//--------------------------
#SPEAKER_ID "0"
@MES_e01_002_001_019
{
<NS>Bandit Leader<NE>
What have we got here? She's an elda!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e01_002_001_020
{
<NS>Warrior Escort<NE>
So she is. No horns, no knife-ears...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e01_002_001_022
{
<NS>Bandit Leader<NE>
Oho, what's this?
Looks like you been holding out on us, girl!
<WAIT>
}