//--------------------------
#SPEAKER_ID "81"
@MES_e01_008_001_000
{
<NS>Russell<NE>
<VOICE "v_e01_008_001_000_c081">
The king, dead. His daughter, stricken. Are there none left to bear the weight of the crown?
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e01_008_001_003
{
<NS>Russell<NE>
<VOICE "v_e01_008_001_003_c081">
Over ten years she has languished under this curse. How much longer can her body hold out?
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e01_008_001_004
{
<NS>Russell<NE>
<VOICE "v_e01_008_001_004_c081">
No doubt Her Highness would protest... but since she cannot, we have no choice.
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e01_008_001_005
{
<NS>Russell<NE>
<VOICE "v_e01_008_001_005_c081">
For the man who cursed Her Highness, and murdered our king... There can be no mercy!
<WAIT>
}