//--------------------------
#SPEAKER_ID "0"
@MES_e01_001_001_009
{
<NS>Aged Lord<NE>
Her Majesty, killed in her own bed...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e01_001_001_010
{
<NS>Middle-Aged Lady<NE>
The blooms upon the princess's grave had yet to wilt.
Without an heiress to wear the crown, what will become of the royal magic?
<WAIT>
}
//--------------------------
#SPEAKER_ID "66"
@MES_e01_001_001_019
{
<NS>Forden<NE>
Shadows stir in the castle,
just as they did with the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e01_001_001_022
{
<NS>Louis<NE>
A shame, to die with no heirs.
The princess was taken too soon.
<WAIT>
}