//--------------------------
#SPEAKER_ID "11"
@MES_e02_001_001m_000_00
{
<NS>Gallica<NE>
<VOICE "v_e02_001_001m_000_00_c011">
Well, I guess I can't blame you for feeling nostalgic. You and the princess were pretty close.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e02_001_001m_003
{
<NS>Gallica<NE>
<VOICE "v_e02_001_001m_003_c011">
Remember, nobody here knows who we are. Nobody here knows the princess might still have a claim to the throne.
<WAIT>
}