//--------------------------
#SPEAKER_ID "11"
@MES_e02_006_001_001
{
<NS>Gallica<NE>
<VOICE "v_e02_006_001_001_c011">
So it's a fantasy world made up by the author. The princess loved those kinds of stories.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e02_006_001_002_00
{
<NS>Gallica<NE>
<VOICE "v_e02_006_001_002_00_c011">
Okay, let's see... It says the young traveller was amazed by the world she saw.
<WAIT>
}