//--------------------------
#SPEAKER_ID "79"
@MES_e02_003_001_028_01
{
<NS>Captain Klinger<NE>
<VOICE "v_e02_003_001_028_01_c079">
Look, girl, your dreams are your business, but a soldier can't have her head in the clouds. Battle is the only art you'll have use of.
<WAIT>
}
//--------------------------
#SPEAKER_ID "79"
@MES_e02_003_001_035
{
<NS>Captain Klinger<NE>
<VOICE "v_e02_003_001_035_c079">
I'm sure you heard about the monster sightings, so stay sharp out there. We're short-handed as it is, so be a good lass and try not to get killed on your first deployment.
<WAIT>
}
//--------------------------
#SPEAKER_ID "79"
@MES_e02_003_001_025_03
{
<NS>Captain Klinger<NE>
<VOICE "v_e02_003_001_025_03_c079">
Hmph. I asked for your skills, girl.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e02_003_001_027 SEL 0
{
With an adventurer king spirit.<COLOR -1>
With a mage king versatility.<COLOR -1>
With a war king courage.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e02_003_001_027_00
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e02_003_001_027_00_c001">
...With a king spirit of adventure, maybe?
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e02_003_001_028_00
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e02_003_001_028_00_c001">
...With a king mastery of magic, maybe?
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e02_003_001_029_00
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e02_003_001_029_00_c001">
...With a king courage in war, maybe?
<WAIT>
}