//--------------------------
#SPEAKER_ID "11"
@MES_e02_005_001_010_15
{
<NS>Gallica<NE>
<VOICE "v_e02_005_001_010_15_c011">
The princess was kind to take you in. She cared more about who you were than what you were. I can see why you'd want to repay her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e02_005_001_011
{
<NS>Gallica<NE>
<VOICE "v_e02_005_001_011_c011">
Oh, speaking of—she's the one who gave you that book, right? Can I see it?
<WAIT>
}