//--------------------------
#SPEAKER_ID "11"
@MES_e03_007_001_009
{
<NS>Gallica<NE>
<VOICE "v_e03_007_001_009_c011">
Wait, there's more... The princess is getting worse. We're running out of time. Here, look...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e03_007_001_010
{
<NS>Gallica<NE>
<VOICE "v_e03_007_001_010_c011">
I brought a treasure from the village—they called it a Farsight Mirror. You need to see the princess's condition for yourself...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e03_007_001_010_00
{
<NS>Protagonist<NE>
Through the mirror lies the princess, deep in slumber in the hidden village...
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_007_001_011
{
<NS>Grius<NE>
<VOICE "v_e03_007_001_011_c010">
...Her Highness won't last much longer. Those thorns are thick enough to claim her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_007_001_003
{
<NS>Grius<NE>
<VOICE "v_e03_007_001_003_c010">
So this is our newcomer, eh? How'd this girl manage to command power like that?
<WAIT>
}