//--------------------------
#SPEAKER_ID "11"
@MES_e03_016_009_018
{
<NS>Gallica<NE>
<VOICE "v_e03_016_009_018_c011">
Hey, hold on a second! Who even are you? How much do you know? I'm warning you, if you mess with her, you're gonna have to go through me!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e03_016_009_023
{
<NS>Gallica<NE>
<VOICE "v_e03_016_009_023_c011">
We trust each other. I've got her back, and she's got mine. And that's all there is to it.
<WAIT>
}