//--------------------------
#SPEAKER_ID "3"
@MES_e03_018_001_002
{
<NS>Hulkenberg<NE>
My lady! Are you hurt!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e03_018_001_009
{
<NS>Hulkenberg<NE>
I pledged my life to the princess...
and I'll not lose it to you!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e03_018_001_016
{
<NS>Hulkenberg<NE>
They dare harm her!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e03_018_001_017
{
<NS>Hulkenberg<NE>
...I failed her... again...
<WAIT>
}