//--------------------------
#SPEAKER_ID "11"
@MES_e03_007_003_002
{
<NS>Gallica<NE>
<VOICE "v_e03_007_003_002_c011">
Until he attacked the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_007_003_003
{
<NS>Grius<NE>
<VOICE "v_e03_007_003_003_c010">
That night, when the princess's quarters were breached... it was no ordinary mage who cast that fatal curse. It was Louis Guiabern himself.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_007_003_004
{
<NS>Grius<NE>
<VOICE "v_e03_007_003_004_c010">
But the daughter's death wasn't enough for him. Now he's got the father's blood on his hands. And if that kingslaying fiend ends up on the throne, we're all doomed.
<WAIT>
}