//--------------------------
#SPEAKER_ID "10"
@MES_e03_017_001_022_01
{
<NS>Grius<NE>
<VOICE "v_e03_017_001_022_01_c010">
Well, we used it to identify the messenger from our faction, but it originally belonged to Her Highness. A kingly gift from her father.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_017_001_022_02
{
<NS>Grius<NE>
<VOICE "v_e03_017_001_022_02_c010">
To better suit Her Highness and her keen aptitude for magic, that blade was specially forged, with raw magla folded into the metal.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_017_001_022_03
{
<NS>Grius<NE>
<VOICE "v_e03_017_001_022_03_c010">
Of course, when swordplay bored her, she'd amuse herself by levitating it, or standing atop it to glide about... A royal rascal, that one.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e03_017_001_024
{
<NS>Strohl<NE>
<VOICE "v_e03_017_001_024_c002">
I've heard. The princess was attacked, right?
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_017_001_025
{
<NS>Grius<NE>
<VOICE "v_e03_017_001_025_c010">
It was a plot on her life. One I wish I'd rooted out sooner.
<WAIT>
}