//--------------------------
#SPEAKER_ID "10"
@MES_e03_020_001_000
{
<NS>Grius<NE>
<VOICE "v_e03_020_001_000_c010">
Her Highness survived the attack, but... the curse hanging over her was powerful and complex.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_020_001_001
{
<NS>Grius<NE>
<VOICE "v_e03_020_001_001_c010">
Of all the mage healers in the capital, not one could wake her. And she grew weaker with each passing day.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_020_001_006
{
<NS>Grius<NE>
<VOICE "v_e03_020_001_006_c010">
And now, after spilling the royal blood of father and daughter both... the people call him not traitor, but saviour.
<WAIT>
}
//--------------------------
#SPEAKER_ID "10"
@MES_e03_020_001_007
{
<NS>Grius<NE>
<VOICE "v_e03_020_001_007_c010">
For Her Highness, for the king, and for the very future of this country, he must be dealt with.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e03_020_001_009
{
<NS>Strohl<NE>
<VOICE "v_e03_020_001_009_c002">
I see. So as he did with the princess, he would make of my city a stepping-stone to further heights. A tool to spread the infamy of the humans.
<WAIT>
}