//--------------------------
#SPEAKER_ID "11"
@MES_e04_024_001_008
{
<NS>Gallica<NE>
<VOICE "v_e04_024_001_008_c011">
Killing Louis, to lift the princess's curse. We've lost a lot already, but we can't afford to give up after one failure.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_024_001_018
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_024_001_018_c003">
Allow me to lend my blade. Even if we can put the man down, if we can't save the heiress to the throne, it would be all for nought.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_024_001_018_00
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_024_001_018_00_c003">
Until the day Her Highness the Princess's life is saved, I will fight through all obstacles.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e04_024_001_032
{
<NS>Gallica<NE>
<VOICE "v_e04_024_001_032_c011">
Here, this is the princess. She's been asleep for a long, long time.
<WAIT>
}