//--------------------------
#SPEAKER_ID "3"
@MES_e04_018_001_005_02
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_018_001_005_02_c003">
Arvid Alces. He'd been engaged as a tutor to Her Royal Highness, teaching her swordsmanship at the king's behest.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_018_001_005_06
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_018_001_005_06_c003">
Yes, well, it was back when I myself was serving as one of Her Highness's personal guards.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_018_001_005_07
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_018_001_005_07_c003">
At the time, I myself was serving as one of Her Highness's personal guards. That is when our paths crossed.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_018_001_005_08
{
<NS>Strohl<NE>
<VOICE "v_e04_018_001_005_08_c002">
You're a personal guard for the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_018_001_005_09
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_018_001_005_09_c003">
I was. Now, she is lost to me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_018_001_005_16
{
<NS>Strohl<NE>
<VOICE "v_e04_018_001_005_16_c002">
The assassination is for Her Highness. To avenge her death.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_018_001_005_18
{
<NS>Strohl<NE>
<VOICE "v_e04_018_001_005_18_c002">
Not just for the princess. Louis killed the king as well.
<WAIT>
}