//--------------------------
#SPEAKER_ID "3"
@MES_e04_022_001_027_00
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_022_001_027_00_c003">
The princess...
For having lost her, you too would abandon me?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_022_001_029
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_022_001_029_c003">
Why did you leave me alone in the dark
when you escaped with Her Highness?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_022_001_029_00
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_022_001_029_00_c003">
I have sought her for so many years to no avail...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_022_001_031
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_022_001_031_c003">
Of course...
'Tis only just that you be the one to send me to her now.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_022_001_042
{
<NS>Strohl<NE>
<VOICE "v_e04_022_001_042_c002">
She's right. We do hunt Louis, but not for revenge!
We mean to lift the princess's curse!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_022_001_044
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_022_001_044_c003">
Is that true? Her Highness is... still...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e04_022_001_045
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e04_022_001_045_c001">
Yes, she lives! So you have to keep fighting!
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e04_022_001_048_01
{
<NS>Mysterious Voice<NE>
<VOICE "v_e04_022_001_048_01_c068">
Henceforth, thy fears and insecurities become thy light.
Thou art the brilliant star that shall illuminate the queen road. Now...
<WAIT>
}