//--------------------------
#SPEAKER_ID "3"
@MES_e04_020_001_002
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_020_001_002_c003">
Arvid Alces. He'd been engaged as a tutor to Her Royal Highness, teaching her swordsmanship at the king's behest.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_020_001_002_03
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_020_001_002_03_c003">
Yes, well, it was back when I myself was serving as one of Her Highness's personal guards.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_020_001_003
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_020_001_003_c003">
At the time, I myself was serving as one of Her Highness's personal guards. That is when our paths crossed.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_020_001_004
{
<NS>Strohl<NE>
<VOICE "v_e04_020_001_004_c002">
You're a personal guard for the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_020_001_005
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_020_001_005_c003">
I was. Now, she is lost to me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_020_001_012
{
<NS>Strohl<NE>
<VOICE "v_e04_020_001_012_c002">
The assassination is for Her Highness. To avenge her death.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_020_001_014
{
<NS>Strohl<NE>
<VOICE "v_e04_020_001_014_c002">
Not just for the princess. Louis killed the king as well.
<WAIT>
}