//--------------------------
#SPEAKER_ID "1"
@MES_e04_024_003m_002_00
{
<NS>Protagonist<NE>
<VOICE "v_co_1061_c001">
We can't let a tragedy that would rob this country of its future come to pass... Not only for the princess, but for Grius as well.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_024_003m_005
{
<NS>Strohl<NE>
<VOICE "v_co_2085_c002">
No objections here. She's certainly gotten me out of plenty of nasty situations.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e04_024_003m_014
{
<NS>Gallica<NE>
<VOICE "v_co_Dpv_PC_Gallica_gripe_01_c011">
I guess, but... it sounds so formal. I dunno if I could get used to calling her that!
<WAIT>
}