//--------------------------
#SPEAKER_ID "3"
@MES_e04_023_003m_000
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_023_003m_000_c003">
Rest now, Alces. We will protect Maria and Her Royal Highness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e04_023_003m_005
{
<NS>Strohl<NE>
<VOICE "v_e04_023_003m_005_c002">
You said you were a royal knight, didn't you? Were you there on the night the princess was attacked?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_023_003m_007
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_023_003m_007_c003">
We saw Her Highness afflicted with a horrific curse. But soon after, she mysteriously vanished.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e04_023_003m_008
{
<NS>Hulkenberg<NE>
<VOICE "v_e04_023_003m_008_c003">
Alces was one of Her Highness's closest confidants when she disappeared. I'd wondered if they were both lost to us...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e04_023_003m_009
{
<NS>Gallica<NE>
<VOICE "v_e04_023_003m_009_c011">
But I could see it when we told you the truth. You believed the princess was alive, didn't you?
<WAIT>
}