//--------------------------
#SPEAKER_ID "3"
@MES_e05_004_001_011
{
<NS>Hulkenberg<NE>
<VOICE "v_e05_004_001_011_c003">
But we've more troubles ahead. How now do we resolve this curse upon Her Highness?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e05_004_001_013
{
<NS>Gallica<NE>
<VOICE "v_e05_004_001_013_c011">
I wish I could report back, but... the princess is still asleep, and we're losing time. I don't think going back to the village is an option.
<WAIT>
}