//--------------------------
#SPEAKER_ID "3"
@MES_e05_002_001_002
{
<NS>Hulkenberg<NE>
<VOICE "v_e05_002_001_002_c003">
Had they rushed a coronation for His Eminence Forden, it would have dashed any hope of reinstating Her Highness. A small comfort.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e05_002_001_011
{
<NS>Strohl<NE>
<VOICE "v_e05_002_001_011_c002">
What the hell was the king thinking!? Grius was trying to save his daughter—he died for it!
<WAIT>
}