//--------------------------
#SPEAKER_ID "40"
@MES_e05_003_001_016
{
<NS>Maria<NE>
<VOICE "v_e05_003_001_016_c040">
Mum was sick... The king and princess are gone... and now Papa? Why does everyone always leave?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e05_003_001_019
{
<NS>Gallica<NE>
<VOICE "v_e05_003_001_019_c011">
She's right, Maria. It's not your fault at all!
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e05_003_001_029_00
{
<NS>Protagonist<NE>
<VOICE "v_co_1061_c001">
"In my ideal world, people can believe in their future. Their birth doesn't matter." The princess told me that once.
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_e05_003_001_029
{
<NS>Maria<NE>
<VOICE "v_e05_003_001_029_c040">
I hope the next ruler is as nice as you. Then maybe things won't always be so sad...
<WAIT>
}