//--------------------------
#SPEAKER_ID "2"
@MES_e06_007_001_017
{
<NS>Strohl<NE>
<VOICE "v_e06_007_001_017_c002">
Besides, this is apparently a knight-turned-kidnapper. The man can't be allowed to go on. What would Her Royal Highness do in our place?
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_e06_007_001_000
{
<NS>Bardon<NE>
<VOICE "v_e06_007_001_000_c046">
Your pardon, folks. I'm Bardon, a guard captain for Martira, a town to the south. The bounty on Heismay is up at my behest.
<WAIT>
}