//--------------------------
#SPEAKER_ID "3"
@MES_e06_010_001_007
{
<NS>Hulkenberg<NE>
<VOICE "v_e06_010_001_007_c003">
Had our lands embraced such accountability, perhaps Her Royal Highness would not have suffered such a fate...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e06_010_001_010_01
{
<NS>Hulkenberg<NE>
<VOICE "v_e06_010_001_010_01_c003">
My dearest dream... 'Tis to save Her Highness, even at the cost of my life. Nothing more.
<WAIT>
}