//--------------------------
#SPEAKER_ID "3"
@MES_e06_009_001_022
{
<NS>Hulkenberg<NE>
<VOICE "v_e06_009_001_022_c003">
It pains me to see. When I think of how this may yet save Her Highness, I lose sight of all else... Such disregard ill becomes me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e06_009_001_023 SEL 0
{
Don't worry about it.<COLOR -1>
That's putting it mildly.<COLOR -1>
You truly are devoted to her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e06_009_001_025_00
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e06_009_001_025_00_c001">
You truly are devoted to her, aren't you?
<WAIT>
}