//--------------------------
#SPEAKER_ID "M1024_001"
@MES_e06_003_001_002
{
<NS>Unfriendly Official<NE>
<VOICE "v_e06_003_001_002_m262">
Eh? Bit young, ain't you? And who's the kid? She with you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e06_003_001_010
{
<NS>Strohl<NE>
<VOICE "v_e06_003_001_010_c002">
Could you just do your job, please? Can she register or not?
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e06_003_001_014
{
<NS>Strohl<NE>
<VOICE "v_e06_003_001_014_c002">
No, they said she'd just drag the company down, so they left her at the capital. She, erm, got on the captain's bad side.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1024_001"
@MES_e06_003_001_009
{
<NS>Unfriendly Official<NE>
<VOICE "v_e06_003_001_009_m262">
...Well! I'd not have thought it, but you're an elda, ain't you? And you wanna be ruler? Well, the novelty of it might win you some looks!
<WAIT>
}