//--------------------------
#SPEAKER_ID "40"
@MES_e06_002_001_009
{
<NS>Maria<NE>
<VOICE "v_e06_002_001_009_c040">
So you're going to try and become queen? Wow! Then I'll cheer for you as loud as I can!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_e06_002_001_022
{
<NS>Maria<NE>
<VOICE "v_e06_002_001_022_c040">
But I'll be cheering for you! I hope you win the race! You'd be a good queen!
<WAIT>
}