//--------------------------
#SPEAKER_ID "3"
@MES_e06_001_001_014
{
<NS>Hulkenberg<NE>
<VOICE "v_e06_001_001_014_c003">
That bodes ill... Those with existing support could easily solidify their claim. Even should Her Highness wake, she may lose the throne.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e06_001_001_024
{
<NS>Gallica<NE>
<VOICE "v_e06_001_001_024_c011">
Besides, the princess isn't exactly in a position to take part in...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e06_001_001_025
{
<NS>Strohl<NE>
<VOICE "v_e06_001_001_025_c002">
Wait, it sounds crazy, but I think she might be on to something there!
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e06_001_001_038_00
{
<NS>Protagonist<NE>
<VOICE "v_co_1090_c001">
<NOLIPSYNC>I'm reminded of the words the princess spoke to me in our youth...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e06_001_001_038_02
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e06_001_001_038_02_c001">
No matter who someone is, they deserve a fair country. If it's to help achieve that, I will stand for the princess as a candidate for the throne.
<WAIT>
}