//--------------------------
#SPEAKER_ID "11"
@MES_e06_002_002m_002
{
<NS>Gallica<NE>
<VOICE "v_co_11031_c011">
So, I was thinking... You've got Her Highness's sword, right? Maybe you can do something cool with it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e06_002_002m_004
{
<NS>Gallica<NE>
<VOICE "v_co_Dpv_PC_Gallica_talk_33_c011">
That's what the princess used to do, remember? So let's give it a try. Picture levitating, then see if you can stand on it.
<WAIT>
}