//--------------------------
#SPEAKER_ID "2"
@MES_e07_008_001_017
{
<NS>Strohl<NE>
<VOICE "v_e07_008_001_017_c002">
...She's also a candidate, though her name doesn't carry any weight.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e07_008_001_021
{
<NS>Strohl<NE>
<VOICE "v_e07_008_001_021_c002">
...She's just another no-name candidate.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e07_008_001_025 SEL 0
{
To become queen.<COLOR -1>
To help save the princess.<COLOR -1>
To help you, Count Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e07_008_001_029
{
<NS>Protagonist<NE>
We're bound to complete secrecy when it comes to the princess... Should I really share that?
<WAIT>
}