//--------------------------
#SPEAKER_ID "13"
@MES_e07_001_001_012
{
<NS>Neuras<NE>
<VOICE "v_e07_001_001_012_c013">
You've a good head on your shoulders, girl! Yes, I can tell you're a sharp one!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e07_001_001_016
{
<NS>Neuras<NE>
<VOICE "v_e07_001_001_016_c013">
Oh, but my girl, you've only seen the test run! We'll have you gobsmacked in a couple acres' time, yes we will!
<WAIT>
}