//--------------------------
#SPEAKER_ID "46"
@MES_e07_010_001_011
{
<NS>Bardon<NE>
<VOICE "v_e07_010_001_011_c046">
Ye fairly eat with gusto, young woman! Passion worthy of a royal candidate!
<WAIT>
}
//--------------------------
#SPEAKER_ID "46"
@MES_e07_010_001_040
{
<NS>Bardon<NE>
<VOICE "v_e07_010_001_040_c046">
Inspiring words, young woman! Now, I hope you're not full yet—we've a whole spread of other dishes for ye!
<WAIT>
}