//--------------------------
#SPEAKER_ID "11"
@MES_e07_003_001_014
{
<NS>Gallica<NE>
<VOICE "v_e07_003_001_014_c011">
Either way, he knows the princess is alive, so we can't just leave him to his own devices. We're all in the same boat... Or runner, I guess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e07_003_001_030
{
<NS>Strohl<NE>
<VOICE "v_e07_003_001_030_c002">
Good enough for me. A captain's got to trust her crew, after all.
<WAIT>
}