//--------------------------
#SPEAKER_ID "4"
@MES_e07_034_001_008
{
<NS>Heismay<NE>
<VOICE "v_e07_034_001_008_c004">
Young woman... I have a request.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e07_034_001_032
{
<NS>Protagonist<NE>
We told Heismay everything, from the princess's survival to our plot for Louis's favour...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e07_034_001_034
{
<NS>Heismay<NE>
<VOICE "v_e07_034_001_034_c004">
So Her Royal Highness lives! I see now why you all fought so desperately.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e07_034_001_044
{
<NS>Heismay<NE>
<VOICE "v_e07_034_001_044_c004">
If I'm to choose a lady out of loyalty instead of dependence... Then there's absolutely no shame in that.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e07_034_001_045 SEL 0
{
Not a lady. A friend.<COLOR -1>
I hope you're ready.<COLOR -1>
I expect great things.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e07_034_001_046
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e07_034_001_046_c001">
Not a lady. A friend.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e07_034_001_048
{
<NS>Strohl<NE>
<VOICE "v_e07_034_001_048_c002">
More a friend than a lady, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e07_034_001_049_00
{
<NS>Heismay<NE>
<VOICE "v_e07_034_001_049_00_c004">
Yes, in my lady's name. And as a friend.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e07_034_001_048_00
{
<NS>Heismay<NE>
<VOICE "v_e07_034_001_048_00_c004">
To the girl, I suppose there's no difference. Either way, I'll follow my heart from now on.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e07_034_001_024
{
<NS>Heismay<NE>
<VOICE "v_e07_034_001_024_c004">
Mm. You're in this race to become queen, are you?
<WAIT>
}