//--------------------------
#SPEAKER_ID "3"
@MES_e07_002_001_000_05
{
<NS>Hulkenberg<NE>
<VOICE "v_e07_002_001_000_05_c003">
It is not a new one I require. Before Her Highness disappeared, did you not accept a contract to build her a custom carriage?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e07_002_001_000_12
{
<NS>Hulkenberg<NE>
<VOICE "v_e07_002_001_000_12_c003">
'Twas specially made for Her Highness, yes? Not a work you'd have sold off. Where lies it now?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e07_002_001_001
{
<NS>Hulkenberg<NE>
<VOICE "v_e07_002_001_001_c003">
The very craft commissioned for Her Highness the Princess!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e07_002_001_003
{
<NS>Hulkenberg<NE>
<VOICE "v_e07_002_001_003_c003">
Even knowing Her Highness was gone... still you toiled away! Oh, Neuras, you are an inspiration! Such nobility of purpose!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e07_002_001_009
{
<NS>Neuras<NE>
<VOICE "v_e07_002_001_009_c013">
Well, at first, certainly! I followed the blueprints exactly! But then Her Highness died, and, ah, well, I couldn't just let the old girl waste away.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e07_002_001_014
{
<NS>Hulkenberg<NE>
<VOICE "v_e07_002_001_014_c003">
A lowly, brazen court engineer, butchering Her Highness's inheritance for a hobby!? For this... mania, you embezzled the royal treasury and disrespected her legacy!? Treason!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e07_002_001_019
{
<NS>Hulkenberg<NE>
<VOICE "v_e07_002_001_019_c003">
'Tis no scheme! I would use it for Her Highness's sake!
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e07_002_001_020
{
<NS>Neuras<NE>
<VOICE "v_e07_002_001_020_c013">
For Her Highness, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e07_002_001_021
{
<NS>Neuras<NE>
<VOICE "v_e07_002_001_021_c013">
Hold a tick. Haven't you been looking for her? Wandering across God-knows-where, last I heard. So if you're back now, and...
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e07_002_001_022
{
<NS>Neuras<NE>
<VOICE "v_e07_002_001_022_c013">
And now you want a gauntlet runner for Her Highness...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e07_002_001_023
{
<NS>Neuras<NE>
<VOICE "v_e07_002_001_023_c013">
Is... Is Her Highness still alive?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e07_002_001_025
{
<NS>Hulkenberg<NE>
<VOICE "v_e07_002_001_025_c003">
'Twas Her Highness who gave you refuge while you were only a heretical scholar condemned by the Sanctists. The time has come to repay her mercy.
<WAIT>
}