//--------------------------
#SPEAKER_ID "51"
@MES_e07_038_001_002
{
<NS>More<NE>
<VOICE "v_e07_038_001_002_c051">
With Louis's gaze forever beyond them, the formula to the princess's curse likewise would never be theirs. They had failed.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e07_038_001_005
{
<NS>Gallica<NE>
<VOICE "v_e07_038_001_005_c011">
The princess is... dead?
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_e07_038_001_007
{
<NS>More<NE>
<VOICE "v_e07_038_001_007_c051">
And as for that curious little novel describing a utopia of "happily ever after"... One wonders whether the girl still carries it as close to hand or heart.
<WAIT>
}