//--------------------------
#SPEAKER_ID "13"
@MES_e07_016_001_003
{
<NS>Neuras<NE>
<VOICE "v_e07_016_001_003_c013">
It's not powerful by virtue of being connected to the king or to the lass. <i>Maybe</i> it's that <i>all</i> magic is supposed to have potential of this magnitude.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e07_016_001_018
{
<NS>Neuras<NE>
<VOICE "v_e07_016_001_018_c013">
Well, thank you very much. Almost had me out of a job there, lass.
<WAIT>
}