//--------------------------
#SPEAKER_ID "5"
@MES_e08_030_001_007
{
<NS>Junah<NE>
<VOICE "v_e08_030_001_007_c005">
But I understand the objective well enough. The curse on Her Highness the Princess can't be lifted by conventional methods, so we either kill the caster or get the formula.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e08_030_001_028
{
<NS>Junah<NE>
<VOICE "v_e08_030_001_028_c005">
I knew you were the sort of woman who knows what to say. Glad to meet you as a proper comrade, <HERO_NAME>!
<WAIT>
}