//--------------------------
#SPEAKER_ID "5"
@MES_e08_026_001_000_00
{
<NS>Junah<NE>
<VOICE "v_e08_026_001_000_00_c005">
She has no pets here. So what's the matter,
are you too scared to fight her alone?
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e08_026_001_018_00
{
<NS>Mysterious Voice<NE>
<VOICE "v_e08_026_001_018_00_c068">
Henceforth, thy fears and insecurities become thy light.
Thou art the brilliant star that shall illuminate the queen road. Now...
<WAIT>
}