//--------------------------
#SPEAKER_ID "13"
@MES_e08_033_002m_014
{
<NS>Neuras<NE>
<VOICE "v_e08_033_002m_014_c013">
You and the rest of our merry band are risking your very lives for the princess. And here I sit moping, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e08_033_002m_012
{
<NS>Neuras<NE>
<VOICE "v_e08_033_002m_012_c013">
Between us, old girl... my flight theory's complete. Principles are sound and tested. All that's left are the practicals, eh? Incorporating it into the gauntlet runner.
<WAIT>
}