//--------------------------
#SPEAKER_ID "5"
@MES_e08_055_001_009
{
<NS>Junah<NE>
<VOICE "v_e08_055_001_009_c005">
She did a fine enough job saving your life out at sea.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e08_055_001_011
{
<NS>Junah<NE>
<VOICE "v_e08_055_001_011_c005">
She's one of us now. Lord Louis gave her direct personal orders. And you'd still leave her to die?
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e08_055_001_012
{
<NS>Junah<NE>
<VOICE "v_e08_055_001_012_c005">
I promised Lord Louis I'd keep an eye on her, too. If you get her killed, I'm the one who's failed.
<WAIT>
}