//--------------------------
#SPEAKER_ID "11"
@MES_e08_022_001_007
{
<NS>Gallica<NE>
<VOICE "v_e08_022_001_007_c011">
Yesss, magic formulas! But which one has the princess's curse? Ugh, forget it! We'll just take the whole box...!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e08_022_001_023
{
<NS>Gallica<NE>
<VOICE "v_e08_022_001_023_c011">
Hey, get away from her!
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e08_022_001_027
{
<NS>Junah<NE>
<VOICE "v_e08_022_001_027_c005">
Hehe... I do love a smart woman.
<WAIT>
}