//--------------------------
#SPEAKER_ID "3"
@MES_e08_101_002_000
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_101_002_000_c003">
Her Highness still suffers under the curse. But Louis is dead. I cannot fathom it...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e08_101_002_013
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_101_002_013_c003">
That night... Her Highness the Princess was already fleeing when I arrived at the scene...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e08_101_002_014
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_101_002_014_c003">
I encountered the assailant as I sought to protect Her Highness. I pursued, and slashed across their back...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e08_101_002_027
{
<NS>Heismay<NE>
<VOICE "v_e08_101_002_027_c004">
Nay, but that does not make it impossible. It wasn't long after the princess's "passing" that His Majesty named Sanctism the state religion.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e08_101_002_029
{
<NS>Strohl<NE>
<VOICE "v_e08_101_002_029_c002">
Sounds like motive enough to want the princess gone.
<WAIT>
}