//--------------------------
#SPEAKER_ID "4"
@MES_e08_014_001_014
{
<NS>Heismay<NE>
<VOICE "v_e08_014_001_014_c004">
It means she's even willing to save someone like me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "7"
@MES_e08_014_001_010
{
<NS>Fidelio<NE>
<VOICE "v_e08_014_001_010_c007">
What kind of queen are you sellin' yourself to be, exactly? Go on, let's have the pitch.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e08_014_001_011 SEL 0
{
I'd help anyone in need.<COLOR -1>
I'd treat all tribes equally.<COLOR -1>
I don't want to be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e08_014_001_018
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e08_014_001_018_c001">
To be honest, I don't really want to be queen.
<WAIT>
}