//--------------------------
#SPEAKER_ID "15"
@MES_e08_020_001_027
{
<NS>Louis<NE>
<VOICE "v_e08_020_001_027_c015">
Doubtless you've heard of the young candidate who brought great shame to Sanctifex Forden. Before you stands the young woman herself.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e08_020_001_028
{
<NS>Louis<NE>
<VOICE "v_e08_020_001_028_c015">
Indeed, I was much surprised to learn she brought that sanctoress forward with the intent of winning my regard. Commendably bold.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M0154_001"
@MES_e08_020_001_032
{
<NS>Bewitching Minstrel<NE>
<VOICE "v_e08_020_001_032_m436">
It's your life on the line now, girl!
<WAIT>
}
//--------------------------
#SPEAKER_ID "77"
@MES_e08_020_001_044
{
<NS>Glodell<NE>
<VOICE "v_e08_020_001_044_c077">
Hey, new girl, slow down. Wouldn't be wise to snub a ranking officer, now would it?
<WAIT>
}