//--------------------------
#SPEAKER_ID "3"
@MES_e08_032_001_015
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_032_001_015_c003">
Pardon the late introduction. I am Hulkenberg, a knight of the crown. As you may have guessed, that is the formula to the curse that slew Her Royal Highness the Princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e08_032_001_017
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_032_001_017_c003">
The death of Her Highness was a tragedy. One I would see repaid in full. As her royal guard, 'tis my duty to punish the treasonous snake responsible.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e08_032_001_031
{
<NS>Rella<NE>
<VOICE "v_e08_032_001_031_c014">
But... I'm afraid even if Her Highness still lived, I don't think anyone could have broken the curse using this.
<WAIT>
}