//--------------------------
#SPEAKER_ID "3"
@MES_e08_011_001_006
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_011_001_006_c003">
We have finally taken the first step in saving Her Highness the Princess. If we can get the formula, then we yet have a chance of lifting the curse.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e08_011_001_007
{
<NS>Heismay<NE>
<VOICE "v_e08_011_001_007_c004">
How fares Her Highness, anyway? She still fights?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e08_011_001_008
{
<NS>Gallica<NE>
<VOICE "v_e08_011_001_008_c011">
I took a look in the Farsight Mirror a while ago. She's still asleep, but... nothing's changed about her condition.
<WAIT>
}