//--------------------------
#SPEAKER_ID "66"
@MES_e08_049_001_002
{
<NS>Forden<NE>
<VOICE "v_e08_049_001_002_c066">
Hmph. So she stands with Louis, then. No doubt she seeks Drakodios.
<WAIT>
}
//--------------------------
#SPEAKER_ID "76"
@MES_e08_049_001_008
{
<NS>Gideaux<NE>
<VOICE "v_e08_049_001_008_c076">
Let her chase the lance. It changes nothing. With the dawn of Saint's Day, Your Eminence's authority will be unshakeable as the mountains.
<WAIT>
}
//--------------------------
#SPEAKER_ID "76"
@MES_e08_049_001_001
{
<NS>Gideaux<NE>
<VOICE "v_e08_049_001_001_c076">
As reported by a crier. It's the elda girl who brought Joanna to the judging.
<WAIT>
}