//--------------------------
#SPEAKER_ID "2"
@MES_e08_021_001_004
{
<NS>Strohl<NE>
<VOICE "v_e08_021_001_004_c002">
I stand with a candidate who's proven she has power and potential.
<WAIT>
}
//--------------------------
#SPEAKER_ID "77"
@MES_e08_021_001_028
{
<NS>Glodell<NE>
<VOICE "v_e08_021_001_028_c077">
That brat's nowhere to be seen... Where'd she slip off to?
<WAIT>
}
//--------------------------
#SPEAKER_ID "77"
@MES_e08_021_001_029
{
<NS>Glodell<NE>
<VOICE "v_e08_021_001_029_c077">
She couldn't have...
<WAIT>
}