//--------------------------
#SPEAKER_ID "2"
@MES_e08_071_001_006
{
<NS>Strohl<NE>
<VOICE "v_e08_071_001_006_c002">
Oh, it's a fantasy novel. She's never without it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e08_071_001_015
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_071_001_015_c003">
'Tis a world where all people are equal, and no conflict exists. Much like the world Her Highness once dreamt of.
<WAIT>
}