//--------------------------
#SPEAKER_ID "47"
@MES_e08_037_001_010
{
<NS>Batlin<NE>
<VOICE "v_e08_037_001_010_c047">
The lass responsible for exposing the sins of the sanctoress Joanna! Valiant human-slayer! Yes, it's the young elda, <HERO_NAME>!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1036_002"
@MES_e08_037_001_011
{
<NS>Lightly-Dressed Tourist<NE>
<VOICE "v_e08_037_001_011_m476">
Right, wasn't expecting that one. Nameless to famous in a single night! Just like that, she's in the top twenty.
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e08_037_001_015
{
<NS>Batlin<NE>
<VOICE "v_e08_037_001_015_c047">
But the girl candidate isn't the only one in the spotlight. We've a rising star by the name of Catherina!
<WAIT>
}