//--------------------------
#SPEAKER_ID "3"
@MES_e08_100_001_011
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_100_001_011_c003">
We have sought to save the rightful heiress to the throne... to break the curse afflicting Her Highness the Princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e08_100_001_012
{
<NS>Basilio<NE>
<VOICE "v_e08_100_001_012_c008">
What's that? The princess? She's dead, mate. Wait, she is <i>dead</i>, isn't she!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "7"
@MES_e08_100_001_013
{
<NS>Fidelio<NE>
<VOICE "v_e08_100_001_013_c007">
She's dead all right. You lot will need a better story than that if you don't wanna get cut open where you stand.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e08_100_001_014
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_100_001_014_c003">
She had to be declared dead in order to protect her. Though she lives... she is bed-ridden, cursed by magic.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e08_100_001_016
{
<NS>Junah<NE>
<VOICE "v_e08_100_001_016_c005">
Those of us who wanted the princess restored formed a secret faction. And I was a spy in its service, trying to find out if we had any option beyond murder.
<WAIT>
}
//--------------------------
#SPEAKER_ID "7"
@MES_e08_100_001_019
{
<NS>Fidelio<NE>
<VOICE "v_e08_100_001_019_c007">
You did this for the princess!? Her father the king was a coward, a puppet of Forden! It was because of him that this country rotted from the inside!
<WAIT>
}
//--------------------------
#SPEAKER_ID "7"
@MES_e08_100_001_020
{
<NS>Fidelio<NE>
<VOICE "v_e08_100_001_020_c007">
And for his daughter... For his bloody, useless corpse of a daughter— What made you think her life was worth more than Count Louis!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e08_100_001_022
{
<NS>Eupha<NE>
<VOICE "v_e08_100_001_022_c006">
I myself have never met Her Highness. Nor do I know what sort of person she is. But I want to see the future these people believe in.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e08_100_001_041
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_100_001_041_c003">
Ah, <HERO_NAME>! Let us tarry no more—we must check Her Highness's condition!
<WAIT>
}