//--------------------------
#SPEAKER_ID "15"
@MES_e08_104_001_005
{
<NS>Louis<NE>
<VOICE "v_e08_104_001_005_c015">
Good people, you have heard the truth with your own ears. Forden was the vile mastermind behind the princess's assassination.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e08_104_001_035
{
<NS>Louis<NE>
<VOICE "v_e08_104_001_035_c015">
...So. Her Venerable Highness the Princess survived.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e08_104_001_036
{
<NS>Louis<NE>
<VOICE "v_e08_104_001_036_c015">
Where is she? Speak or die.
<WAIT>
}