//--------------------------
#SPEAKER_ID "2"
@MES_e08_102_001_028
{
<NS>Strohl<NE>
<VOICE "v_e08_102_001_028_c002">
That night... You were the one behind the attack on Her Royal Highness. You framed Louis for your crime, and banished him from the palace. Do you deny it!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e08_102_001_037
{
<NS>Basilio<NE>
<VOICE "v_e08_102_001_037_c008">
Del, what the hell's goin' on? I thought the princess's curse was s'posed to be off!
<WAIT>
}
//--------------------------
#SPEAKER_ID "7"
@MES_e08_102_001_038
{
<NS>Fidelio<NE>
<VOICE "v_e08_102_001_038_c007">
It's clearly not. The princess's assassination, the whole lot—it was all the Sanctists... It was all that bastard pullin' the strings from the start.
<WAIT>
}