//--------------------------
#SPEAKER_ID "6"
@MES_e08_070_002m_000
{
<NS>Eupha<NE>
<VOICE "v_e08_070_002m_000_c006">
So the princess is alive.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e08_070_002m_001
{
<NS>Hulkenberg<NE>
<VOICE "v_e08_070_002m_001_c003">
I know Her Highness can guide us to a brighter future. Laugh at my hopes if you wish, yet...
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e08_070_002m_002
{
<NS>Eupha<NE>
<VOICE "v_e08_070_002m_002_c006">
I do not know or love this princess as you do. But I can tell by your faith she is not one to cast others aside.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e08_070_002m_003
{
<NS>Strohl<NE>
<VOICE "v_e08_070_002m_003_c002">
For now, we need to figure out when and where to ambush Louis—the treasonous bastard who cursed her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e08_070_002m_009
{
<NS>Gallica<NE>
<VOICE "v_e08_070_002m_009_c011">
Not just the lance, but now we've got Eupha herself. Things are looking up... Maybe you just draw people to you, like the princess did.
<WAIT>
}