//--------------------------
#SPEAKER_ID "75"
@MES_e08_009_002_017
{
<NS>Joanna<NE>
<VOICE "v_e08_009_002_017_c075">
Thus, here I stand. My head is her to offer.
<WAIT>
}
//--------------------------
#SPEAKER_ID "75"
@MES_e08_009_002_030
{
<NS>Joanna<NE>
<VOICE "v_e08_009_002_030_c075">
O new Queen, it is my hope that you will rid the world of its twisted prejudices and common cruelties...
<WAIT>
}