//--------------------------
#SPEAKER_ID "4"
@MES_e08_007_001_032
{
<NS>Heismay<NE>
<VOICE "v_e08_007_001_032_c004">
She's not looking for honesty, lass. She's giving you her faith and well-wishes, and deserves the same back.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e08_007_001_033
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e08_007_001_033_c001">
I'd really rather not be queen, if it were up to me.
<WAIT>
}