//--------------------------
#SPEAKER_ID "7"
@MES_e08_028_001_002
{
<NS>Fidelio<NE>
<VOICE "v_e08_028_001_002_c007">
The two of them were the only ones who'd left the soiree early. Sounds like Glodell overstepped, and Lady Junah and the new lass had to fight him down...
<WAIT>
}
//--------------------------
#SPEAKER_ID "7"
@MES_e08_028_001_007
{
<NS>Fidelio<NE>
<VOICE "v_e08_028_001_007_c007">
The girl'd have to have the standing for it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e08_028_001_023
{
<NS>Junah<NE>
<VOICE "v_e08_028_001_023_c005">
Oh, and with Glodell out with the rubbish, might I promote <i>her</i> to the role of my chauffeur?
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e08_028_001_025
{
<NS>Junah<NE>
<VOICE "v_e08_028_001_025_c005">
Is it so strange? She does have her own gauntlet runner. In fact, I'd better go make sure it's up to my standards.
<WAIT>
}