//--------------------------
#SPEAKER_ID "M1722_908"
@MES_e08_005_004m_000
{
<NS>Junior Spokesperson<NE>
<VOICE "v_e08_005_004m_000_m377">
Rumour has it that young candidate hasn't brought a head. Wonder what she's playing at?
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1032_910"
@MES_e08_005_004m_001
{
<NS>Drunk Spokesperson<NE>
<VOICE "v_e08_005_004m_001_m378">
Whatever it is, she's about to get a sharp lesson in the ways of the world, poor lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e08_005_004m_002
{
<NS>Batlin<NE>
<VOICE "v_e08_005_004m_002_c047">
I think she's worth keeping an eye on.
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e08_005_004m_003
{
<NS>Batlin<NE>
<VOICE "v_e08_005_004m_003_c047">
Keep it under your hats, chums, but her power may rival Count Louis. I think she's just the ingredient we need to, ah... <i>spice</i> this race up a bit.
<WAIT>
}