//--------------------------
#SPEAKER_ID "M1526_002"
@MES_e08_048_001_002_00
{
<NS>Worrywart Man<NE>
<VOICE "v_e08_048_001_002_00_m490">
Is she all right? They say the waters are clear of monsters now, but...
<WAIT>
}
//--------------------------
#SPEAKER_ID "M2336_901"
@MES_e08_048_001_003_00
{
<NS>Excited Woman<NE>
<VOICE "v_e08_048_001_003_00_m491">
If she made it, that means my husband can go out fishing again, doesn't it?
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1526_002"
@MES_e08_048_001_005
{
<NS>Worrywart Man<NE>
<VOICE "v_e08_048_001_005_m490">
That's the same lass who exposed that lady from Martira, isn't it? She's not bad...
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e08_048_001_001_00
{
<NS>Batlin<NE>
<VOICE "v_e08_048_001_001_00_c047">
The elda girl candidate seems to have crossed the channel to the island! On a gauntlet runner, too!
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e08_048_001_004
{
<NS>Batlin<NE>
<VOICE "v_e08_048_001_004_c047">
Heh, I have to say, I expected at least one daredevil to try ploughing straight through the inner sea, but I never thought it'd be that girl.
<WAIT>
}