//--------------------------
#SPEAKER_ID "2"
@MES_e08_099_001_017
{
<NS>Strohl<NE>
<VOICE "v_e08_099_001_017_c002">
Years ago, Louis ordered my hometown destroyed. Hulkenberg, our ally before you, was herself a royal guard in service to her late Highness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "66"
@MES_e08_099_001_027
{
<NS>Forden<NE>
<VOICE "v_e08_099_001_027_c066">
I understand... It all makes sense now. I had wondered why a member of the princess's own guard would fall in with Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "66"
@MES_e08_099_001_028
{
<NS>Forden<NE>
<VOICE "v_e08_099_001_028_c066">
You have done well to execute the rebel. I am sure that his late Majesty and Her Highness must be pleased.
<WAIT>
}
//--------------------------
#SPEAKER_ID "66"
@MES_e08_099_001_031
{
<NS>Forden<NE>
<VOICE "v_e08_099_001_031_c066">
You must be the lady Hulkenberg. The day Her Highness was attacked... I heard you fought harder than any other.
<WAIT>
}
//--------------------------
#SPEAKER_ID "66"
@MES_e08_099_001_032
{
<NS>Forden<NE>
<VOICE "v_e08_099_001_032_c066">
Your blade even struck the back of the blackguard who did it. Of all her defenders, you came closest to avenging the princess.
<WAIT>
}