//--------------------------
#SPEAKER_ID "8"
@MES_e09_003_002m_002
{
<NS>Basilio<NE>
<VOICE "v_co_8012_c008">
Just tell me this. You doin' all this to save the poor princess? Or you doin' it to save the country?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e09_003_002m_003 SEL 0
{
I want to save the princess.<COLOR -1>
I want to save the country.<COLOR -1>
It's the same thing.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e09_003_002m_004
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_co_1032_c001">
I want to save the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e09_003_002m_005
{
<NS>Basilio<NE>
<VOICE "v_co_8023_c008">
That all, though? Don't care what happens long as you save her life? You know that ain't the end of it. Can't be.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e09_003_002m_009
{
<NS>Basilio<NE>
<VOICE "v_co_8184_c008">
If you wanna save the country, you're playin' a longer game. Got to actually win this race. So if we can't save the princess, you take her place. For good.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e09_003_002m_011
{
<NS>Basilio<NE>
<VOICE "v_co_8146_c008">
I'm just sayin'. You declare yourself princess tomorrow, and everythin' changes for you, forever. You know what you're signin' up for?
<WAIT>
}