//--------------------------
#SPEAKER_ID "13"
@MES_e09_031_002m_001
{
<NS>Neuras<NE>
<VOICE "v_e09_031_002m_001_c013">
Glad to hear Her Highness is all right. Hardly feels real, after all the muck we've waded through. But I s'pose the fates take as much as they give.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e09_031_002m_006
{
<NS>Neuras<NE>
<VOICE "v_e09_031_002m_006_c013">
Right... Understood. For now, tempting as it might be, best not to drop everything and make a dash for Her Highness.
<WAIT>
}