//--------------------------
#SPEAKER_ID "3"
@MES_e09_022_001_002
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_022_001_002_c003">
Little more needs to be said. We are here to save Her Highness. And to do that...
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_022_001_051
{
<NS>Rella<NE>
<VOICE "v_e09_022_001_051_c014">
To be queen is to wield strength, even to save the foolish and the abandoned. Whoever you really are, until I know you can be a true queen, I refuse to die!
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_022_001_054
{
<NS>Rella<NE>
<VOICE "v_e09_022_001_054_c014">
Dragons are manifested avatars of mortal fear. Fear of nature, fear of the untamed. That is the source of their power. If you would be queen, show me you can conquer it.
<WAIT>
}