//--------------------------
#SPEAKER_ID "3"
@MES_e09_031_003m_004
{
<NS>Hulkenberg<NE>
<VOICE "v_co_3077_c003">
Saint Rella placed her trust in us. She would see us protect all those in this country, including the Sanctist faithful, who are still the princess's royal subjects.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e09_031_003m_005
{
<NS>Strohl<NE>
<VOICE "v_co_2074_c002">
Besides, a coward who flees the city to save her own hide would hardly be worthy of support.
<WAIT>
}