//--------------------------
#SPEAKER_ID "15"
@MES_e09_009_001_007
{
<NS>Louis<NE>
<VOICE "v_e09_009_001_007_c015">
You know it was not I who laid the princess low. Which means that if you oppose me still, it is for the throne, and nothing more.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_009_001_017_00
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_009_001_017_00_c003">
The rightful heiress stands before you!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_009_001_018
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_009_001_018_c003">
Look upon our candidate and know her true claim. She is the legitimate daughter of His late Majesty King Hythlodaeus V...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_009_001_019
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_009_001_019_c003">
Last heiress to the throne of Euchronia! Her Highness, the Princess herself, has risen to vanquish evil! For her people, she defies the pain and suffering of the curse she endured!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e09_009_001_020
{
<NS>Alarmed Sanctist<NE>
<VOICE "v_e09_009_001_020_m676">
Her Highness the Princess? What? That's a lie!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e09_009_001_021
{
<NS>Elderly Sanctist<NE>
<VOICE "v_e09_009_001_021_m671">
Her Highness... She has already passed!
<WAIT>
}
//--------------------------
#SPEAKER_ID "76"
@MES_e09_009_001_022
{
<NS>Gideaux<NE>
<VOICE "v_e09_009_001_022_c076">
Her Highness the Princess!? Ha... They're mad, the lot of them. That girl's an elda!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_009_001_023
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_009_001_023_c003">
Indeed she is. 'Tis the very proof you seek. Anyone who truly knows Her Highness herself will see what this means!
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_009_001_027
{
<NS>Rella<NE>
<VOICE "v_e09_009_001_027_c014">
I saw for myself when I personally treated Her Highness. They'd warned me against revealing it to the public, but... the time for discretion is past.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_009_001_028
{
<NS>Rella<NE>
<VOICE "v_e09_009_001_028_c014">
Her Highness the Princess has eldan blood coursing through his veins. His Majesty told me that the girl's birth mother was an elda woman.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e09_009_001_029
{
<NS>Alarmed Sanctist<NE>
<VOICE "v_e09_009_001_029_m676">
The princess was... an elda!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e09_009_001_031
{
<NS>Louis<NE>
<VOICE "v_e09_009_001_031_c015">
Hahaha, hahahaha! You!? The princess!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e09_009_001_032
{
<NS>Louis<NE>
<VOICE "v_e09_009_001_032_c015">
A bold gambit, to reveal yourself before both Rella and I! Indeed, I have no retort. After all, she has been "dead" so long, nobody could say otherwise!
<WAIT>
}