//--------------------------
#SPEAKER_ID "4"
@MES_e09_032_002m_000_03
{
<NS>Heismay<NE>
<VOICE "v_co_4063_c004">
I mean to say, if you strike down a man who is not your true enemy, will you truly be able to call yourself a righteous princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e09_032_002m_008
{
<NS>Gallica<NE>
<VOICE "v_co_11033_c011">
And now that you've declared yourself the princess, it's not like you can afford to fall on your face in front of everyone anyway. Heh.
<WAIT>
}