//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_005
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_005_c014">
We witnessed a girl candidate who claimed to be the princess... To ascertain the truth of her words, I faced her in mutual, voluntary battle.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_006
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_006_c014">
I now see with eyes unclouded. Good people, she is, without a doubt, Her Highness the Princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_007
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_007_c014">
Now, there is something further you all must know. The truth of Her Highness's reported death... and the truth of the attempt on her life.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_008
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_008_c014">
Sanctifex Forden was indeed behind the plot to assassinate Her Highness. By this <i>barbaric</i> act, he sought to elevate the Church, and put the throne within his own grasp.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_009
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_009_c014">
These revelations are only mine to give... because I was Forden's assassin. It was I who cast the curse upon Her Highness.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_010
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_010_c014">
Yet all was not lost. Through all these long years, Her Highness has endured the pain, and now walks among her people once more.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_016
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_016_c014">
Yet know this, dear faithful: you need not let your anxieties rule you. I have faced Her Highness the Princess myself, and known her heart.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_017
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_017_c014">
Her Highness will accept us. With her strength, she will shelter the lost and weak, and stand against Louis in our names.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_027_001_018
{
<NS>Rella<NE>
<VOICE "v_e09_027_001_018_c014">
If all of you would believe, our country could be a place where all would thrive under a just queen. I pray with all my heart that it will be so.
<WAIT>
}