//--------------------------
#SPEAKER_ID "14"
@MES_e09_025_001_000
{
<NS>Rella<NE>
<VOICE "v_e09_025_001_000_c014">
K-Kill Her Highness!? I can't! Have you gone mad?
<WAIT>
}
//--------------------------
#SPEAKER_ID "66"
@MES_e09_025_001_004
{
<NS>Forden<NE>
<VOICE "v_e09_025_001_004_c066">
The king has sired an illegitimate mongrel of a girl, and now he's brought her to the castle. If we do not act now, one day we will be bending the knee to an eldan queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "66"
@MES_e09_025_001_007
{
<NS>Forden<NE>
<VOICE "v_e09_025_001_007_c066">
As the matter stands, we have but one way to deal with both in a single stroke. Dispose of the mongrel princess, and place the blame on Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_025_001_012
{
<NS>Rella<NE>
<VOICE "v_e09_025_001_012_c014">
Yes, but even so... Her Highness the Princess is guilty of nothing. To murder someone innocent... It is an unforgivable atrocity...
<WAIT>
}