//--------------------------
#SPEAKER_ID "13"
@MES_e09_001_002m_015
{
<NS>Neuras<NE>
<VOICE "v_e09_001_002m_015_c013">
We've more pressing problems at hand, don't we? Now Louis knows the princess is alive. Surely that's far from ideal.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e09_001_002m_016
{
<NS>Gallica<NE>
<VOICE "v_e09_001_002m_016_c011">
The village is deep in the forest. It's not an easy place to find even if you're looking. Going to the princess's side could be dangerous, so let's not get ahead of ourselves.
<WAIT>
}