//--------------------------
#SPEAKER_ID "3"
@MES_e09_006_001_004
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_006_001_004_c003">
Once we stand for Her Royal Highness the Princess, that will surely change. We have to believe that.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e09_006_001_024
{
<NS>Doubtful Man<NE>
<VOICE "v_e09_006_001_024_m633">
And they say Sanctifex Forden killed the princess, too. If that's true, then I don't know if I'd trust his closest vassal with the throne...
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1126_021"
@MES_e09_006_001_000
{
<NS>Onlooker<NE>
<VOICE "v_e09_006_001_000_m641">
Look, it's that girl candidate. The one who betrayed Louis, or killed him, or something...
<WAIT>
}