//--------------------------
#SPEAKER_ID "14"
@MES_e09_010_001_022
{
<NS>Rella<NE>
<VOICE "v_e09_010_001_022_c014">
Besides, what makes you any more fit to speak of "rightness"? Ha! You claim <i>she</i> is the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_010_001_023
{
<NS>Rella<NE>
<VOICE "v_e09_010_001_023_c014">
The real princess is surely at death's door, isn't she? After all, your efforts did nothing to lift the curse.
<WAIT>
}
//--------------------------
#SPEAKER_ID "14"
@MES_e09_010_001_025
{
<NS>Rella<NE>
<VOICE "v_e09_010_001_025_c014">
I've told you before. The princess's curse was crafted to perpetually draw upon the caster's magic... I know she suffers... because <i>I</i> yet live.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_010_001_027
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_010_001_027_c003">
No, you healed Her Highness... It was only by virtue of your presence that she survived that night...
<WAIT>
}