//--------------------------
#SPEAKER_ID "13"
@MES_e09_014_001_011
{
<NS>Neuras<NE>
<VOICE "v_e09_014_001_011_c013">
Hah, don't go poking the bear fairy, my lass! Really, I'd never have done this without you giving me the push I needed. Thank you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_014_001_013
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_014_001_013_c003">
We must pursue Saint—pursue Rella as soon as possible. Her Highness is running out of time...
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e09_014_001_025
{
<NS>Junah<NE>
<VOICE "v_e09_014_001_025_c005">
That's not her. I thought she wasn't like that... Now she's saying she was part of this conspiracy? She attacked the princess? No! It doesn't make any sense!
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e09_014_001_027
{
<NS>Heismay<NE>
<VOICE "v_e09_014_001_027_c004">
That would be prudent, yes. But, <HERO_NAME>, a reeve for your thoughts, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e09_014_001_006
{
<NS>Neuras<NE>
<VOICE "v_e09_014_001_006_c013">
Only because you're as bold and pig-headed as I am, what? Really, old girl, I'd not be here without you to give me the push I needed. Thank you.
<WAIT>
}