//--------------------------
#SPEAKER_ID "14"
@MES_e09_026_001_017
{
<NS>Rella<NE>
<VOICE "v_e09_026_001_017_c014">
After the assault on Her Highness, I was made to investigate Louis as a suspect. I touched his hand, and read deeply into the flow of his magla.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e09_026_001_022
{
<NS>Strohl<NE>
<VOICE "v_e09_026_001_022_c002">
So that's how it is. If you let yourself be killed for the princess's sake, you couldn't guarantee the survivors could stop Louis.
<WAIT>
}