//--------------------------
#SPEAKER_ID "M1023_001"
@MES_e09_030_001_000
{
<NS>Young Monk<NE>
<VOICE "v_e09_030_001_000_m736">
Saint Rella was the one who cursed the princess? And to take her own life in the name of atonement...
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1527_001"
@MES_e09_030_001_001
{
<NS>Shabby Beggar<NE>
<VOICE "v_e09_030_001_001_m737">
But didn't you hear the rest!? That elda girl's the true princess! She survived!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1527_001"
@MES_e09_030_001_001_00
{
<NS>Shabby Beggar<NE>
<VOICE "v_e09_030_001_001_00_m737">
The king's trueborn daughter's risen to take down Louis! It's like a proper myth! I've got to stand with her!
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e09_030_001_005
{
<NS>Dignified Crier<NE>
<VOICE "v_e09_030_001_005_m739">
"If this message is being read, it means that Rella is dead, and the girl who claims herself the princess has won."
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e09_030_001_005_00
{
<NS>Louis<NE>
<VOICE "v_e09_030_001_005_00_c015">
"If this message is being read, it means that Rella is dead, and the girl who claims herself the princess has won."
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1023_001"
@MES_e09_030_001_016
{
<NS>Young Monk<NE>
<VOICE "v_e09_030_001_016_m736">
If Louis emerges the victor, we are surely doomed... I stand with the princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e09_030_001_017
{
<NS>Louis-Loyal City Girl<NE>
<VOICE "v_e09_030_001_017_m742">
Nobody can beat Count Louis! It's high past time he tore that so-called princess limb from limb!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_e09_030_001_018
{
<NS>Maria<NE>
<VOICE "v_e09_030_001_018_c040">
If she beats this Louis person, will she become queen?
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e09_030_001_019
{
<NS>Fabienne<NE>
<VOICE "v_e09_030_001_019_c067">
Will she indeed...
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e09_030_001_006_00
{
<NS>Louis<NE>
<VOICE "v_e09_030_001_006_00_c015">
"Now, only two aspirants remain with any real chance at the throne: the girl, and myself."
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e09_030_001_007_02
{
<NS>Louis<NE>
<VOICE "v_e09_030_001_007_02_c015">
"The girl, or myself. Only one shall wear the crown."
<WAIT>
}