//--------------------------
#SPEAKER_ID "2"
@MES_e09_003_001_010
{
<NS>Strohl<NE>
<VOICE "v_e09_003_001_010_c002">
After all, just lifting the curse isn't going to be enough to restore the princess to the throne...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e09_003_001_012
{
<NS>Heismay<NE>
<VOICE "v_e09_003_001_012_c004">
Her Highness herself will have to win this battle on the faith of the people, or her claim to the crown will never be acknowledged.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_003_001_013
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_003_001_013_c003">
Besides which, Louis now knows that Her Highness lives. Her whereabouts have not been discovered... but the kingslayer will take up the hunt.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e09_003_001_014_00
{
<NS>Protagonist<NE>
<VOICE "v_co_1174_c001">
We have to keep trying to break the curse, but we also need to get people to support the princess's claim to the throne...
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e09_003_001_016
{
<NS>Basilio<NE>
<VOICE "v_e09_003_001_016_c008">
We use a body double. <HERO_NAME>, you're s'posed to be a dead ringer for the princess, yeah?
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e09_003_001_017
{
<NS>Junah<NE>
<VOICE "v_e09_003_001_017_c005">
You mean she pretends to be the princess!? That's absurd! You realise it's a capital offence to impersonate royalty!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e09_003_001_025
{
<NS>Basilio<NE>
<VOICE "v_e09_003_001_025_c008">
Our Del was right about you bein' mental! I think we could pull it off, though. The princess has been gone ages. Nobody's in a position to point out differences.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e09_003_001_026
{
<NS>Strohl<NE>
<VOICE "v_e09_003_001_026_c002">
Wait, just think about this. She's elda. The royal family's clemar, and have been for generations. Her appearance would be the least of our worries.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_003_001_028
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_003_001_028_c003">
Her Highness the Princess lacks the clemar horns. Some rumours suggested 'twas not some miraculous feature of the princess alone... but a mark of eldan blood.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e09_003_001_030
{
<NS>Heismay<NE>
<VOICE "v_e09_003_001_030_c004">
In other words, with an elda claiming the princess's name and a known royal knight to vouchsafe her, we'd have enough plausibility to shake the nobles to their core.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e09_003_001_031
{
<NS>Hulkenberg<NE>
<VOICE "v_e09_003_001_031_c003">
Of course, all this means little, unless our double herself is willing... What say you, <HERO_NAME>?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e09_003_001_032 SEL 0
{
I can't back down now.<COLOR -1>
I am the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e09_003_001_035
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e09_003_001_035_c001">
I am the princess... Was that believable?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e09_003_001_039
{
<NS>Neuras<NE>
<VOICE "v_e09_003_001_039_c013">
Right then. Looks like I'll have to give the old girl a polish worthy of a princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e09_003_001_041
{
<NS>Neuras<NE>
<VOICE "v_e09_003_001_041_c013">
My cue as well. From here on, it's nose to the grindstone until my magnum opus is finished... Can't let the lass be the only one with her life on the line...
<WAIT>
}