//--------------------------
#SPEAKER_ID "69"
@MES_e10_001_001_000
{
<NS>Zorba<NE>
<VOICE "v_e10_001_001_000_c069">
At long last, milord, our investigations have borne fruit... We know where the true princess lies.
<WAIT>
}
//--------------------------
#SPEAKER_ID "69"
@MES_e10_001_001_001
{
<NS>Zorba<NE>
<VOICE "v_e10_001_001_001_c069">
Those loyalists who disappeared with the princess led us right to her. We found traces of their coming and going.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e10_001_001_002
{
<NS>Louis<NE>
<VOICE "v_e10_001_001_002_c015">
Where was she hiding?
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e10_001_001_008
{
<NS>Louis<NE>
<VOICE "v_e10_001_001_008_c015">
The princess was born there, you know. An illegitimate daughter, after the past king's heart was drawn to a woman of the village in his youthful years of debauchery.
<WAIT>
}
//--------------------------
#SPEAKER_ID "69"
@MES_e10_001_001_009
{
<NS>Zorba<NE>
<VOICE "v_e10_001_001_009_c069">
What? Then the princess really does bear elda blood!
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e10_001_001_010
{
<NS>Louis<NE>
<VOICE "v_e10_001_001_010_c015">
Forden did not raze the village for any defiance of his scriptures. He thought only to eliminate an inconvenient heiress, a threat to his power, before her birth was known.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e10_001_001_011
{
<NS>Louis<NE>
<VOICE "v_e10_001_001_011_c015">
The princess's survival, her complete disappearance... This was the missing piece.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e10_001_001_015
{
<NS>Louis<NE>
<VOICE "v_e10_001_001_015_c015">
If you call yourself the princess, then I will give you a princess's end... and I have just the spell to do it.
<WAIT>
}