//--------------------------
#SPEAKER_ID "2"
@MES_e11_008_001_003
{
<NS>Strohl<NE>
<VOICE "v_e11_008_001_003_c002">
Because she's elda, you would call her a monster!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e11_008_001_013
{
<NS>Hulkenberg<NE>
<VOICE "v_e11_008_001_013_c003">
Louis, you dog... Your lies will soil Her Highness's name no longer!
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_008_001_016
{
<NS>Louis<NE>
<VOICE "v_e11_008_001_016_c015">
Hear me! Her appearance as a girl is mere trickery!
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_008_001_017
{
<NS>Louis<NE>
<VOICE "v_e11_008_001_017_c015">
In truth, she is humankind! She is kin to the feral monstrosities that roam this land, leaving carnage in their wake!
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_008_001_020
{
<NS>Louis<NE>
<VOICE "v_e11_008_001_020_c015">
You, girl, who call yourself the princess... you will be the cornerstone upon which my utopia is built.
<WAIT>
}