//--------------------------
#SPEAKER_ID "M1136_021"
@MES_e11_001_001_000
{
<NS>Broad Gravedigger<NE>
<VOICE "v_e11_001_001_000_m754">
It's Her Royal Highness the Princess! We've been waiting for you! Go and teach that damned Louis a lesson!
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e11_001_001_002
{
<NS>Junah<NE>
<VOICE "v_e11_001_001_002_c005">
Sounds like they're more excited about the spectacle than about the princess being alive. Still, suppose it makes sense.
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e11_001_001_003
{
<NS>Eupha<NE>
<VOICE "v_e11_001_001_003_c006">
But by the faces in the sky and upon the rock, we are squarely set in second place. Even with the gap between us and Louis, the princess has faithful supporters.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e11_001_001_004
{
<NS>Hulkenberg<NE>
<VOICE "v_e11_001_001_004_c003">
Though 'tis not truly Her Highness's face wrought in stone, but <HERO_NAME>'s... After all this time, I cannot help but feel conflicted.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M2046_021"
@MES_e11_001_001_005
{
<NS>Shaky Elder<NE>
<VOICE "v_e11_001_001_005_m757">
Louis spares nothing for an old woman like me. Saint Rella spoke truth. We need the help of Her Royal Highness the Princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1023_001"
@MES_e11_001_001_006
{
<NS>Stern Interrogator<NE>
<VOICE "v_e11_001_001_006_m756">
She's the girl with a saint's blessing... She's got to be genuine. If the Sanctist Church's power is waning, should I take Her Highness's side over Louis?
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1026_002"
@MES_e11_001_001_018
{
<NS>Skilful Scribe<NE>
<VOICE "v_e11_001_001_018_m759">
Over there! Her Royal Highness the Princess has arrived!
<WAIT>
}