//--------------------------
#SPEAKER_ID "3"
@MES_e11_002_001_013
{
<NS>Hulkenberg<NE>
<VOICE "v_e11_002_001_013_c003">
Victory is in our grasp. We once thought it impossible to save Her Highness the Princess, after all, and she now lives.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e11_002_001_028
{
<NS>Gallica<NE>
<VOICE "v_e11_002_001_028_c011">
Wow, listen to you, sounding like a proper hero. I suppose the princess thing is rubbing off on you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e11_002_001_029
{
<NS>Gallica<NE>
<VOICE "v_e11_002_001_029_c011">
But it takes me back. If the princess could see you now, she'd be pretty proud of you, don't you think?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e11_002_001_030
{
<NS>Gallica<NE>
<VOICE "v_e11_002_001_030_c011">
I mean, you and she were best friends.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e11_002_001_034
{
<NS>Gallica<NE>
<VOICE "v_e11_002_001_034_c011">
Anyway, we'll make sure this is the end for Louis. Gotta report our victory to Her Highness personally, right?
<WAIT>
}