//--------------------------
#SPEAKER_ID "47"
@MES_e11_005_001_005
{
<NS>Batlin<NE>
<VOICE "v_e11_005_001_005_c047">
The day of judgement is here! The final fight between Louis, military paragon and one-man army, and the girl who claims to be the fallen princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e11_005_001_006
{
<NS>Batlin<NE>
<VOICE "v_e11_005_001_006_c047">
The entire continent's eyes are on this battle, folks, and only one of them's walking away! Let's see a show of true strength worthy of our new ruler!
<WAIT>
}