//--------------------------
#SPEAKER_ID "6"
@MES_e11_011_001_007
{
<NS>Eupha<NE>
<VOICE "v_e11_011_001_007_c006">
She may be back with us, but without rest she will surely succumb to the spell. I don't know if she can withstand the same magic a second time...
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_011_001_015
{
<NS>Louis<NE>
<VOICE "v_e11_011_001_015_c015">
Hahaha! Unfortunately, the princess is finished either way. Both this impostor, and the true princess at death's door deep in the woods.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e11_011_001_016
{
<NS>Hulkenberg<NE>
<VOICE "v_e11_011_001_016_c003">
The true princess? You bastard, what have you done!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e11_011_001_023
{
<NS>Hulkenberg<NE>
<VOICE "v_e11_011_001_023_c003">
We retreat to our gauntlet runner! We must find her safe haven to rest!
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e11_011_001_025
{
<NS>Junah<NE>
<VOICE "v_e11_011_001_025_c005">
Gallica, we've only got one option now! I'm worried about the princess, too.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e11_011_001_026
{
<NS>Gallica<NE>
<VOICE "v_e11_011_001_026_c011">
I know. We'll head to my home and the princess's refuge: the <COLOR 0>Eldan Sanctum<COLOR -1>!
<WAIT>
}