//--------------------------
#SPEAKER_ID "47"
@MES_e11_006_001_003
{
<NS>Batlin<NE>
<VOICE "v_e11_006_001_003_c047">
Suspected of attacking Her Highness, he was denounced and cast down, but his name has since been cleared. And now here he stands, closest to the throne!
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e11_006_001_004
{
<NS>Batlin<NE>
<VOICE "v_e11_006_001_004_c047">
Then, we have the eldan candidate, <HERO_NAME>, who claims to be none other than Her Highness the Princess!
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e11_006_001_005
{
<NS>Batlin<NE>
<VOICE "v_e11_006_001_005_c047">
Though her identity is uncertain, her strength is undeniable. Through her campaign, we've seen her team flourish, counting even the songstress Junah among them!
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e11_006_001_006
{
<NS>Batlin<NE>
<VOICE "v_e11_006_001_006_c047">
The time has come to demonstrate her power! Will it be enough for this youth to take the throne!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_006_001_007
{
<NS>Louis<NE>
<VOICE "v_e11_006_001_007_c015">
I have to commend you. A lesser woman would have run.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_006_001_009
{
<NS>Louis<NE>
<VOICE "v_e11_006_001_009_c015">
You who claim to be the princess. What do you believe the people seek in their ruler?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e11_006_001_018
{
<NS>Beautiful Florist<NE>
<VOICE "v_e11_006_001_018_m777">
Power! Milord Louis, kill her now! Only the strong can rule!
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e11_006_001_015_00
{
<NS>Protagonist<NE>
<VOICE "v_co_1061_c001">
It is a ruler duty to shoulder the burden of the people's prosperity. Such thinking may seem a fantasy to some, but Louis's alternative is no alternative at all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_006_001_017
{
<NS>Louis<NE>
<VOICE "v_e11_006_001_017_c015">
Now let me ask you, my gathered people! What is it that makes a ruler!?
<WAIT>
}