//--------------------------
#SPEAKER_ID "4"
@MES_e11_009_001_003
{
<NS>Heismay<NE>
What ails her!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_009_001_004_00
{
<NS>Louis<NE>
Good people... You would know the identity of
your would-be princess? Here she is!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e11_009_001_005
{
<NS>Monk Trainee<NE>
Aaaargh! She's a monster!
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e11_009_001_010
{
<NS>Louis<NE>
She is no royalty! No girl...
but a ruthless fiend intent on your throne!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1526_021"
@MES_e11_009_001_012
{
<NS>Boisterous Hunter<NE>
What illusion!? That's no princess...
It's a monster!
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e11_009_001_014
{
<NS>Heismay<NE>
What has... become of her?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e11_009_001_018
{
<NS>Gallica<NE>
She's <i>not</i>!
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e11_009_001_019
{
<NS>Strohl<NE>
She's a... a human...?
<WAIT>
}