//--------------------------
#SPEAKER_ID "68"
@MES_e12_010_001_001
{
<NS>Mysterious Voice<NE>
Thou wert born apart from the princess's flesh,
born of her desire to change the world...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_010_001_002
{
<NS>Mysterious Voice<NE>
In her stead didst thou travel the world...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_010_001_002_00
{
<NS>Mysterious Voice<NE>
Thou did support her heart...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_010_001_002_01
{
<NS>Mysterious Voice<NE>
...And became her living fantasy.
That is thy true self.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_010_001_003
{
<NS>Mysterious Voice<NE>
Thou art everything the princess sought to be. Her ideal.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_010_001_007
{
<NS>Mysterious Voice<NE>
No more the princess's dream of utopia
thou wouldst chase... Nay, but thine own.
<WAIT>
}