//--------------------------
#SPEAKER_ID "3"
@MES_e12_004_001_002
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_004_001_002_c003">
You were Her Highness's tutor...!
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e12_004_001_004
{
<NS>Gallica<NE>
<VOICE "v_e12_004_001_004_c011">
She's been helping us. Everyone here's a trusted ally—they've all fought to save the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e12_004_001_006
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_004_001_006_c003">
Russell, where is Her Highness!? What happened? Is Her Highness safe!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_004_001_009
{
<NS>Russell<NE>
<VOICE "v_e12_004_001_009_c081">
Her Highness had only just regained consciousness since the curse's lifting. Yet, to protect us... she threw herself upon the assassin's blade...
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_004_001_010
{
<NS>Russell<NE>
<VOICE "v_e12_004_001_010_c081">
We were horror-struck. Her Highness lay pierced through the heart... and we saw her breathe her last...
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_004_001_014_00
{
<NS>Russell<NE>
<VOICE "v_e12_004_001_014_00_c081">
From the moment he appeared, I believe his sole purpose was to kill Her Highness. As soon as the life light left the princess's eyes, the stranger left, with only a smile...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e12_004_001_014_01
{
<NS>Heismay<NE>
<VOICE "v_e12_004_001_014_01_c004">
An innocent girl... twice tormented in the clutches of assassins... all because of the family she was born into...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e12_004_001_016
{
<NS>Gallica<NE>
<VOICE "v_e12_004_001_016_c011">
Please, Russell... Where is the princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_004_001_017
{
<NS>Russell<NE>
<VOICE "v_e12_004_001_017_c081">
We've laid her in the prayer room for now, at the end of the cave. She rests just this way.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_004_001_022
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_004_001_022_c001">
I must go to her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e12_004_001_025
{
<NS>Gallica<NE>
<VOICE "v_e12_004_001_025_c011">
I won't be able to believe it until I see her for myself...
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_004_001_026
{
<NS>Russell<NE>
<VOICE "v_e12_004_001_026_c081">
Ah... I'd heard a rumour that there was a girl candidate who claimed to be Her Highness... So that was you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_004_001_026_00
{
<NS>Russell<NE>
<VOICE "v_e12_004_001_026_00_c081">
'Tis just as Saint Rella said... You're no scoundrel. Indeed, you risked life and livelihood to see Her Highness restored.
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_004_001_026_01
{
<NS>Russell<NE>
<VOICE "v_e12_004_001_026_01_c081">
Strange... Something in you reminds me of Her Highness...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_004_001_028_01
{
<NS>Protagonist<NE>
Before I go to the princess, I think I'll help Russell lay this body to rest...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e12_004_001_030
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_004_001_030_c003">
No. I must bear witness myself. As... As her knight, I must.
<WAIT>
}