//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_001
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_001_c068">
Know this: her life is not yet ended.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_005
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_005_c068">
It all started on that ill-fated day, when the usurper thought to extinguish her light...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_006
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_006_c068">
Before she fades away, recount all thou hast seen and felt... All thou hast gained in thy journey's course...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e12_006_001_009 SEL 0
{
In the princess's name.<COLOR -1>
It came to nothing.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_006_001_010
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_006_001_010_c001">
In the princess's name.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_012
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_012_c068">
Though thy plan was reckless, thou didst win the trust of the people by the support of peers and subjects alike. Thus, thou didst declare thyself the princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_016
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_016_c068">
After overcoming many obstacles, thou didst finally lift the princess's curse... yet by the cruel machinations of another, the young princess...
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_006_001_018
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_006_001_018_c001">
She is no longer with us.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_006_001_019
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_006_001_019_c001">
She lies dead before me.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_020
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_020_c068">
Thy sole mission was to save the princess. Bereft of her, thou hast no further reason to live...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_028
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_028_c068">
If the princess is dead, wert thy efforts all for nought?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e12_006_001_029 SEL 0
{
She's not dead.<COLOR -1>
Her will lives on.<COLOR -1>
It's over.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_006_001_034
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_006_001_034_c001">
She's not dead.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_006_001_035
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_006_001_035_c001">
Her will lives on.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_037
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_037_c068">
She was consumed by the curse, and was taken by a deep, abiding slumber. Yet her soul remained alive.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_038
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_038_c068">
So from her earthly form, I extracted her soul, that she might travel the land in odyssey. And thus her stilled sands began to flow once more.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e12_006_001_040 SEL 0
{
I am just a traveller.<COLOR -1>
I am the princess's friend.<COLOR -1>
I am no one.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_006_001_043
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_006_001_043_c001">
I'm the princess's friend.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_049
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_049_c068">
Yes. Thy memories begin the moment thou befriended the princess... Dost thou suspect the reason?
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_056_01
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_056_01_c068">
All thou hadst—all that had been bestowed—was a memory. Thy mission to save the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_056_02
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_056_02_c068">
Thy memories of youth in the princess's company, and the void enshrouding all else in thy past... All signs of thy conjured existence.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_057_00
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_057_00_c068">
Nay... The words of the princess in thy memory are unmistakably of her true heart.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e12_006_001_065 SEL 0
{
I am the princess.<COLOR -1>
I refuse to know.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e12_006_001_066
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e12_006_001_066_c001">
I am... the princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_006_001_008
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_006_001_008_c068">
Gallica and thee sought to take the head of Louis, but thy efforts came to nought. So, ye moved instead to join a tournament to decide the land's ruler...
<WAIT>
}