//--------------------------
#SPEAKER_ID "6"
@MES_e12_001_001m_001
{
<NS>Eupha<NE>
<VOICE "v_e12_001_001m_001_c006">
That's a relief. Seems like the rest on the ride here did her some good.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e12_001_001m_005
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_001_001m_005_c003">
Gallica, how fares Her Highness? Does the Farsight Mirror yield any news?
<WAIT>
}