//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_002
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_002_c068">
Thou hast done well to guide her this far.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_005
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_005_c068">
She was never a member of the Resistance.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_006
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_006_c068">
The mission, the departure, was thine alone... and thereafter didst thou encounter her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_009
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_009_c068">
In those long ago days, she had just been born into this land... Newborn in form, if not in appearance.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_010
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_010_c068">
The girl needed a guide. Thus I decided: her memories would be thine. Thou wouldst share past and purpose.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_010_00
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_010_00_c068">
A memory so crafted to suit thee... "My journey to the capital would not be made alone, but alongside her."
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e12_011_001_011
{
<NS>Gallica<NE>
<VOICE "v_e12_011_001_011_c011">
No, that can't be! She was there when we got our orders...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_016
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_016_c068">
By this choice, she might be saved. By these gentle, necessary lies, we could live to see this day, when our dearest wish is fulfilled.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_017
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_017_c068">
As she travelled alongside thee, she gained both strength and wisdom.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_018
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_018_c068">
It is only by thy efforts that my voice reached her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e12_011_001_019
{
<NS>Mysterious Voice<NE>
<VOICE "v_e12_011_001_019_c068">
She has now been saved, and so the journey ends here. Thou hast fulfilled thy mission admirably.
<WAIT>
}