//--------------------------
#SPEAKER_ID "81"
@MES_e12_005_001_012
{
<NS>Russell<NE>
<VOICE "v_e12_005_001_012_c081">
She was kind enough to shelter the entire organisation when Her Highness fled to these woods.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e12_005_001_013
{
<NS>Basilio<NE>
<VOICE "v_e12_005_001_013_c008">
I can't believe she's gone. I'm just some paripus orphan from the slums, I was never supposed to outlive any princess... Was she killed here?
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e12_005_001_014
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e12_005_001_014_c080">
No, it all happened in the bunk room in the back. We moved her here to the altar once all was quiet.
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e12_005_001_015
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e12_005_001_015_c080">
I don't know if you'd believe me, but... I received a revelation: should the princess die, her body should be kept safe and still here until the rightful day comes.
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e12_005_001_015_00
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e12_005_001_015_00_c080">
Even if the girl is but a bastard sired by that despicable man, she is still Her Majesty's daughter...
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e12_005_001_017_00
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e12_005_001_017_00_c080">
The girl was not brought across borders to us. She was born here, in the ancient sanctum. Her mother was our past chieftess... the queen of our elda tribe.
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e12_005_001_017_04
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e12_005_001_017_04_c080">
But you see... this girl, Her Highness the Princess, looks so much like Her Majesty. And so...
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e12_005_001_019
{
<NS>Russell<NE>
<VOICE "v_e12_005_001_019_c081">
Is something amiss, Milady Gruidae? She is one of Gallica's allies. Her loyalty stands with Her Highness, and she has risked much in the princess's name.
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e12_005_001_017_03
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e12_005_001_017_03_c080">
The village was only set ablaze because the girl was in the way of the Sanctist Church's designs on the throne. And that insipid "king" could do nothing to stop them.
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e12_005_001_018
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e12_005_001_018_c080">
Hm...? Y-You there, girl, are you perhaps—no, it can't be... And yet...
<WAIT>
}