//--------------------------
#SPEAKER_ID "6"
@MES_e12_012_001_005
{
<NS>Eupha<NE>
<VOICE "v_e12_012_001_005_c006">
There seems to be no doubt. She is still herself. But I also sense Her Highness within her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e12_012_001_007_00
{
<NS>Heismay<NE>
<VOICE "v_e12_012_001_007_00_c004">
You're saying it's not a matter of our captain and Her Highness joining together, but that the former was... this disembodied entity sprung from the latter?
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e12_012_001_008
{
<NS>Basilio<NE>
<VOICE "v_e12_012_001_008_c008">
Then... that's why she had no memories? 'Cause she didn't even exist!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e12_012_001_010
{
<NS>Eupha<NE>
<VOICE "v_e12_012_001_010_c006">
What shaped you, so to speak, was the princess's will itself...
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e12_012_001_011
{
<NS>Eupha<NE>
<VOICE "v_e12_012_001_011_c006">
A part of her consciousness... yes, the princess's very heart. She was her soul given flesh.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e12_012_001_013
{
<NS>Junah<NE>
<VOICE "v_e12_012_001_013_c005">
A mass of magla with a will... Forget the Dragon God. She may as well have been a dragon herself.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e12_012_001_013_00
{
<NS>Junah<NE>
<VOICE "v_e12_012_001_013_00_c005">
Small wonder she awakened to an Archetype before anyone else. It was no great aptitude for magic, she herself was composed of pure magla.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e12_012_001_015
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_012_001_015_c003">
Y-You mean to say that... 'twas not merely pretence to claim the princess's name? She truly was Her Highness all along?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e12_012_001_017
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_012_001_017_c003">
But I... I failed to protect Her Highness...
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e12_012_001_018
{
<NS>Eupha<NE>
<VOICE "v_e12_012_001_018_c006">
No. I am sure the strength of your devotion had a hand in saving her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e12_012_001_019
{
<NS>Neuras<NE>
<VOICE "v_e12_012_001_019_c013">
While all and sundry believed the lass had shuffled off, you alone kept the faith, milady. And in the end, that faith was rewarded.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e12_012_001_021
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_012_001_021_c003">
Are you really... Her Royal Highness the Princess?
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e12_012_001_028
{
<NS>Strohl<NE>
<VOICE "v_e12_012_001_028_c002">
She's right, you know. If we'd not met you, we'd certainly never have made it this far.
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e12_012_001_033
{
<NS>Basilio<NE>
<VOICE "v_e12_012_001_033_c008">
By the way, what're we s'posed to call you now? I mean... how do you prefer to be addressed, m'lady?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e12_012_001_038
{
<NS>Neuras<NE>
<VOICE "v_e12_012_001_038_c013">
Bah, this is no time to be thickheaded, m'girl! She's the one who gets to decide what we bally call her, so we'll listen to her, eh what?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e12_012_001_039
{
<NS>Hulkenberg<NE>
<VOICE "v_e12_012_001_039_c003">
You, "sir", should be begging Her Highness for forgiveness on bended knee! You mangled the royal runner to your own whimsy, you lout!
<WAIT>
}