//--------------------------
#SPEAKER_ID "80"
@MES_e13_001_001_001
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e13_001_001_001_c080">
After so long in the curse's thrall, she could not even open her eyes. She may as well have been a corpse. But all this time, she had been on her own journey.
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e13_001_001_002
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e13_001_001_002_c080">
It was the girl's dearest wish. She spoke of a fantasy of travelling the world, meeting its people, seeing its truths... and without her even knowing, magic made it real.
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e13_001_001_003
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e13_001_001_003_c080">
She is a child of eldan blood and eldan legacy. All these years she spent in the village, she has rested near the secret of true magic... Perhaps this is how it came to be.
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e13_001_001_005
{
<NS>Eupha<NE>
<VOICE "v_e13_001_001_005_c006">
Her was a fantasy surpassing fantasy. It became more than a dream, but a self-possessed force, acting of its own volition... and now, reunited, princess and fantasy live anew.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e13_001_001_008
{
<NS>Neuras<NE>
<VOICE "v_e13_001_001_008_c013">
No wonder she set off the custom igniter in the royal gauntlet runner—she was the crown princess herself.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e13_001_001_012
{
<NS>Gallica<NE>
<VOICE "v_e13_001_001_012_c011">
That's right... I remember I heard a voice. "Guide her," it said.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e13_001_001_018
{
<NS>Gallica<NE>
<VOICE "v_e13_001_001_018_c011">
I thought we both received the order to save the princess, too. Ever since the moment I heard that weird voice guiding me...
<WAIT>
}