//--------------------------
#SPEAKER_ID "69"
@MES_e13_010_001_002
{
<NS>Zorba<NE>
<VOICE "v_e13_010_001_002_c069">
I killed the princess in the eldan village. I confirmed her death. Yet... It appears the girl candidate has merged with her corpse. It seems the princess is now resurrected...
<WAIT>
}
//--------------------------
#SPEAKER_ID "69"
@MES_e13_010_001_005
{
<NS>Zorba<NE>
<VOICE "v_e13_010_001_005_c069">
The girl candidate was the actual princess after all. Something about her soul having travelled independently, and then returning to her corporeal body...
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e13_010_001_006
{
<NS>Louis<NE>
<VOICE "v_e13_010_001_006_c015">
I see. So her ideal form was spun from magla.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e13_010_001_007
{
<NS>Louis<NE>
<VOICE "v_e13_010_001_007_c015">
Whatever the case, this means the land's true princess has reawakened in her sanctum.
<WAIT>
}