//--------------------------
#SPEAKER_ID "1"
@MES_e13_002_001_011
{
<NS>Protagonist<NE>
<VOICE "v_co_1055_c001">
That means the princess... that is to say, I am a scion of both the Old World and the new...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e13_002_001_021
{
<NS>Hulkenberg<NE>
<VOICE "v_e13_002_001_021_c003">
His Majesty only hid his daughter's ancestry to protect her. Yet in the end, that meant Forden could attack the village under any pretext he liked, his motives concealed...
<WAIT>
}
//--------------------------
#SPEAKER_ID "80"
@MES_e13_002_001_023
{
<NS>Old Hermitess Gruidae<NE>
<VOICE "v_e13_002_001_023_c080">
As you are now, you may walk the path of the rightful queen. The path of a modern world, where the tribes walk as individuals, yet with mutual respect and cooperation.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e13_002_001_024
{
<NS>Mysterious Voice<NE>
<VOICE "v_e13_002_001_024_c068">
The sovereign's power... Thou queen, entrusted with the will of the people. To bear their hopes is to be their rock in the storm, and to face anxiety in their names.
<WAIT>
}