//--------------------------
#SPEAKER_ID "2"
@MES_e13_006_001_013
{
<NS>Strohl<NE>
<VOICE "v_e13_006_001_013_c002">
But don't worry. At long last, the princess is safe, in a manner of speaking. Everything's going according to plan.
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e13_006_001_015
{
<NS>Russell<NE>
<VOICE "v_e13_006_001_015_c081">
...Alces once said that Her Highness the Princess was a soul born into adversity.
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e13_006_001_016
{
<NS>Russell<NE>
<VOICE "v_e13_006_001_016_c081">
She is royalty and elda both. Heiress to the legacies of heaven and earth, she is water and fire in condemned conflux.
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e13_006_001_017
{
<NS>Russell<NE>
<VOICE "v_e13_006_001_017_c081">
When the day comes that Her Highness may be revered as the good ruler she can be, then the world will truly be free of prejudice. And that, he said, is why we fight.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e13_006_001_035
{
<NS>Hulkenberg<NE>
<VOICE "v_e13_006_001_035_c003">
Yet before all else, Her Highness has only just awoken. Let us rest in the gauntlet runner for today, and advance to the Royal Capital tomorrow.
<WAIT>
}