//--------------------------
#SPEAKER_ID "3"
@MES_e13_009_002m_012
{
<NS>Hulkenberg<NE>
<VOICE "v_e13_009_002m_012_c003">
Yet if she suddenly spoke with the eloquence of a philosopher king, 'twould bemuse more than it would spur.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e13_009_002m_014
{
<NS>Gallica<NE>
<VOICE "v_e13_009_002m_014_c011">
About the new stuff you've felt and learned since becoming the princess... Can I ask you one more thing?
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e13_009_002m_020
{
<NS>Hulkenberg<NE>
<VOICE "v_e13_009_002m_020_c003">
Even having become Your Highness the Princess... 'Tis strange to say, but you have not changed a bit.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e13_009_002m_015
{
<NS>Gallica<NE>
<VOICE "v_e13_009_002m_015_c011">
Why is it that you want to be queen? It's not about honour or power, is it?
<WAIT>
}