//--------------------------
#SPEAKER_ID "69"
@MES_e13_005_002_002
{
<NS>Zorba<NE>
<VOICE "v_e13_005_002_002_c069">
Indeed it was. I killed the princess, though she died all too easily... And the odd thing was, her aura felt awfully similar to yours.
<WAIT>
}
//--------------------------
#SPEAKER_ID "69"
@MES_e13_005_002_004
{
<NS>Zorba<NE>
<VOICE "v_e13_005_002_004_c069">
Who are you? Are you the princess or not? Whatever your answer, I must report back to Lord Louis.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e13_005_002_011
{
<NS>Hulkenberg<NE>
<VOICE "v_e13_005_002_011_c003">
She is no impostor, fiend. Her Highness has finally taken her first steps on the road to victory.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e13_005_002_012
{
<NS>Hulkenberg<NE>
<VOICE "v_e13_005_002_012_c003">
Here, at her journey's end, after enduring these countless hardships, she has become a true successor... A true ruler! Because she knows the people's suffering first-hand!
<WAIT>
}
//--------------------------
#SPEAKER_ID "69"
@MES_e13_005_002_013
{
<NS>Zorba<NE>
<VOICE "v_e13_005_002_013_c069">
Hmph. Well, impostor or not, it's all the same if she's a corpse.
<WAIT>
}
//--------------------------
#SPEAKER_ID "69"
@MES_e13_005_002_014
{
<NS>Zorba<NE>
<VOICE "v_e13_005_002_014_c069">
And so I shall return the princess and her dying legacy to the underworld where they belong!
<WAIT>
}