//--------------------------
#SPEAKER_ID "2"
@MES_e13_004_001_012_00
{
<NS>Strohl<NE>
<VOICE "v_e13_004_001_012_00_c002">
He said <HERO_NAME> became a monster because she's elda, but that wasn't the complete story. If what you say is true...
<WAIT>
}
//--------------------------
#SPEAKER_ID "81"
@MES_e13_004_001_035
{
<NS>Russell<NE>
<VOICE "v_e13_004_001_035_c081">
That's him! The malformed assassin who struck at the princess! He's bound for the woods!
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e13_004_001_000
{
<NS>Heismay<NE>
<VOICE "v_e13_004_001_000_c004">
Well, we're past the worst of it, but the problem remains: Louis's dark magic. We've seen it turn the girl into a monster, and no doubt he can do it again.
<WAIT>
}