//--------------------------
#SPEAKER_ID "51"
@MES_e13_009_001_003
{
<NS>More<NE>
<VOICE "v_e13_009_001_003_c051">
Yet by some strange tangle of destiny, you were given a choice that the very act of existence denies most people. By your own will, you were born again as a princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e13_009_001_007
{
<NS>Mysterious Voice<NE>
<VOICE "v_e13_009_001_007_c068">
Indeed... 'Tis her hands that bear our fate.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_e13_009_001_011
{
<NS>More<NE>
<VOICE "v_e13_009_001_011_c051">
Who are you? You, with this voice that moves hearts, speak... Who are you? Why have you awakened this girl to her power!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_e13_009_001_006
{
<NS>More<NE>
<VOICE "v_e13_009_001_006_c051">
Haha... What glorious coincidence indeed. That I, as a scholar of Archetypes, might cross paths with such a remarkably fated girl, and witness your rise...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_e13_009_001_006_00
{
<NS>More<NE>
<VOICE "v_e13_009_001_006_00_c051">
Haha... What glorious coincidence indeed. That I, as a scholar of Archetypes, might cross paths with and witness such a remarkably fated girl. It almost bespeaks...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e13_009_001_015
{
<NS>Mysterious Voice<NE>
<VOICE "v_e13_009_001_015_c068">
Move onward to thy final ordeal... Take thy place at the final proving of the ascension of king!
<WAIT>
}