//--------------------------
#SPEAKER_ID "11"
@MES_e13_008_001_010
{
<NS>Gallica<NE>
<VOICE "v_e13_008_001_010_c011">
But little by little, the pains of reality crushed his hope. And he even lost his daughter... In the end, his will was broken. He didn't lift a finger to stop the Church's rise to power.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e13_008_001_008
{
<NS>Gallica<NE>
<VOICE "v_e13_008_001_008_c011">
So even the author of this book struggled with these questions. And if you become queen, you'll have plenty of tough questions and struggles to face yourself.
<WAIT>
}