//--------------------------
#SPEAKER_ID "47"
@MES_e14_011_001_006
{
<NS>Batlin<NE>
<VOICE "v_e14_011_001_006_c047">
I told you, didn't I? It's just like what happened to the princess. Louis is behind the whole thing!
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1746_001"
@MES_e14_011_001_008
{
<NS>Cautious Elder<NE>
<VOICE "v_e14_011_001_008_m924">
S-So, then, all that about the fake princess being a monster—that was a lie? She's truly Her Highness?
<WAIT>
}