//--------------------------
#SPEAKER_ID "47"
@MES_e14_032_001_005
{
<NS>Batlin<NE>
<VOICE "v_e14_032_001_005_c047">
Look! It's her! Yeeeaaahhh!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_e14_032_001_006
{
<NS>Maria<NE>
<VOICE "v_e14_032_001_006_c040">
Yay! Look, look! That's her, isn't it!? She won!
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e14_032_001_007
{
<NS>Fabienne<NE>
<VOICE "v_e14_032_001_007_c067">
She certainly did, love. She really did.
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e14_032_001_009
{
<NS>Fabienne<NE>
<VOICE "v_e14_032_001_009_c067">
Her Majesty, the new queen... Haha.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_032_001_011
{
<NS>Louis Fanatic Girl<NE>
<VOICE "v_e14_032_001_011_m955">
He can't just crown his daughter after all! That's cheating, that is! Rise up, people! Riot!
<WAIT>
}
//--------------------------
#SPEAKER_ID "76"
@MES_e14_032_001_014
{
<NS>Gideaux<NE>
<VOICE "v_e14_032_001_014_c076">
Our new queen has been decided, and the Royal Capital falls under Her Majesty's rule. Threaten it, and you shall face the wrath of the Crown Theocracy's warrior monks!
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e14_032_001_008
{
<NS>Fabienne<NE>
<VOICE "v_e14_032_001_008_c067">
*sigh*... I still can't believe it. That girl pulled it off.
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e14_032_001_001
{
<NS>Batlin<NE>
<VOICE "v_e14_032_001_001_c047">
He speaks! With the announcement of our new ruler, everything finally ends...
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_032_001_004
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_032_001_004_c065">
Behold... your new queen of your kingdom united!
<WAIT>
}