//--------------------------
#SPEAKER_ID "5"
@MES_e14_009_001_001
{
<NS>Junah<NE>
<VOICE "v_e14_009_001_001_c005">
Is this where Her Highness was attacked...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e14_009_001_003
{
<NS>Gallica<NE>
<VOICE "v_e14_009_001_003_c011">
Now we know Forden manipulated Rella to attack the princess, then tried to shift the blame to Louis to get him pushed out of his station.
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e14_009_001_006
{
<NS>Eupha<NE>
<VOICE "v_e14_009_001_006_c006">
But <HERO_NAME>'s made it back. She's come this far to do what must be done.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e14_009_001_012
{
<NS>Heismay<NE>
<VOICE "v_e14_009_001_012_c004">
Indeed. This battle shall decide the future ruler. Hmph... Wasn't expecting anything so profound from you.
<WAIT>
}