//--------------------------
#SPEAKER_ID "51"
@MES_e14_031_001_000
{
<NS>More<NE>
<VOICE "v_e14_031_001_000_c051">
That must be... the lady that governs utopia and all worthy champions. The hero's Archetype: the Queen...
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_031_001_002
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_031_001_002_c065">
The people hath chosen my daughter. With that, my tremendous gamble hath borne fruit...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e14_031_001_008
{
<NS>Mysterious Voice<NE>
<VOICE "v_e14_031_001_008_c068">
I had to, so I might provide guidance to the child on her most perilous path.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e14_031_001_013
{
<NS>Mysterious Voice<NE>
<VOICE "v_e14_031_001_013_c068">
Now, that girl has grasped the courage of a warrior. All dragons who still roamed the continent have fallen by her hand...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e14_031_001_014
{
<NS>Mysterious Voice<NE>
<VOICE "v_e14_031_001_014_c068">
For what greater embodiment of the impossible is there than a dragon? And she now possesses the power and will to quell those forces.
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_031_001_015
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_031_001_015_c065">
I see... Then she is not so weak a child that I must hold her hand.
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_031_001_017
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_031_001_017_c065">
I lost all the power I once knew. I saw the sanctum burn. And you... I lost you. Once they took our child from me, all my remaining hope went with her...
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_031_001_018
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_031_001_018_c065">
And so I placed my faith in the royal magic. I believed that if this world would choose her, there would still be hope...
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_e14_031_001_019
{
<NS>Mysterious Voice<NE>
<VOICE "v_e14_031_001_019_c068">
This shall do. That girl's fight... and ours... is finally over.
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_031_001_027
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_031_001_027_c065">
It has indeed. But for our daughter... a new journey now begins.
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_031_001_025
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_031_001_025_c065">
However... if I may truly end my life with pride in my girl, and my love at my side... I've no regrets.
<WAIT>
}
//--------------------------
#SPEAKER_ID "65"
@MES_e14_031_001_024
{
<NS>Hythlodaeus V<NE>
<VOICE "v_e14_031_001_024_c065">
The day is dawning on a new queen reign. And with it, my true passing.
<WAIT>
}