//--------------------------
#SPEAKER_ID "3"
@MES_e14_015_001_024
{
<NS>Hulkenberg<NE>
<VOICE "v_e14_015_001_024_c003">
Haha, but I see her point. One might search all their life for absolute virtue, but devoid of compromise, they would never find it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_015_001_011 SEL 0
{
We'll see you soon.<COLOR -1>
I'll come back as queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e14_015_001_014
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e14_015_001_014_c001">
I'll come back as queen.
<WAIT>
}