//--------------------------
#SPEAKER_ID "5"
@MES_e14_034_001_003
{
<NS>Junah<NE>
All right, a warm welcome please!
Her Majesty, the new queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e14_034_001_006
{
<NS>Hulkenberg<NE>
My queen. Your subjects would hear
how you intend to lead them.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e14_034_001_015
{
<NS>Protagonist (Normal)<NE>
Even should you oppose your queen,
you can always believe in your own future. I will make sure of it!
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e14_034_001_019
{
<NS>Junah<NE>
There you go. If you can pull that off,
you'll be the finest queen we've known.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e14_034_001_021
{
<NS>Hulkenberg<NE>
No lord remains for you to kneel before.
Please take the crown with your own hands, my queen.
<WAIT>
}