//--------------------------
#SPEAKER_ID "67"
@MES_e14_005_001_005
{
<NS>Fabienne<NE>
<VOICE "v_e14_005_001_005_c067">
I had thought all this business with declaring yourself the princess was a well-meaning bluff...
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e14_005_001_006
{
<NS>Fabienne<NE>
<VOICE "v_e14_005_001_006_c067">
But under the deception, you were, in fact, the actual princess. Is that right?
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e14_005_001_028
{
<NS>Batlin<NE>
<VOICE "v_e14_005_001_028_c047">
And we'll fight in the ways we can, too. We'll make sure the whole kingdom hears that the real princess is back, after all the strife she's been through!
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_e14_005_001_031
{
<NS>Maria<NE>
<VOICE "v_e14_005_001_031_c040">
I'll always believe in you! We'll all do our best, so you can be a good queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_005_001_032
{
<NS>Strohl<NE>
<VOICE "v_e14_005_001_032_c002">
Indeed... If we win, I suppose you really will be queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e14_005_001_033
{
<NS>Batlin<NE>
<VOICE "v_e14_005_001_033_c047">
We're counting on you, O Queen!
<WAIT>
}