//--------------------------
#SPEAKER_ID "0"
@MES_e14_034_002_001
{
<NS>Past King's Voice<NE>
<VOICE "v_e14_034_002_001_c051">
This journey has reached its end. She came to know the goodness of a hero's heart
and became the queen her people had always hoped for.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_034_002_004
{
<NS>Past King's Voice<NE>
<VOICE "v_e14_034_002_004_c051">
I'd like you to watch over her on her path for a little longer yet...
<WAIT>
}