//--------------------------
#SPEAKER_ID "95"
@MES_e14_014_005m_007
{
<NS>Roger<NE>
<VOICE "v_co_95014_c095">
I'm just trying to be realistic. What else should I believe? You're not saying you think that "princess" should best Count Louis?
<WAIT>
}
//--------------------------
#SPEAKER_ID "96"
@MES_e14_014_005m_008
{
<NS>Lina<NE>
<VOICE "v_co_96011_c096">
...I'm sure prayin' she can. Personally, I think ol' Mr. Goddard's got a point.
<WAIT>
}
//--------------------------
#SPEAKER_ID "96"
@MES_e14_014_005m_010
{
<NS>Lina<NE>
<VOICE "v_co_96039_c096">
I don't want a ruler who breaks everything... I want a ruler who builds for a new future! Like that runner they built to flap its wings across the sky!
<WAIT>
}