//--------------------------
#SPEAKER_ID "0"
@MES_e14_004_001_001
{
<NS>Scribe<NE>
<VOICE "v_e14_004_001_001_m884">
Isn't that— Oi, that monster girl's come back!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_004_001_002
{
<NS>Tall Soldier<NE>
<VOICE "v_e14_004_001_002_m885">
Ah... that's why the sky's grown so hellish! The half-dead bastard returns with her head held high!
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_004_001_006
{
<NS>Strohl<NE>
<VOICE "v_e14_004_001_006_c002">
Her Royal Highness the Princess returns!
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_004_001_007
{
<NS>Strohl<NE>
<VOICE "v_e14_004_001_007_c002">
Louis distorted her form through strange and terrible magics, but the curse is now dispelled! Her true form has been restored—
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_004_001_008
{
<NS>Gravedigger<NE>
<VOICE "v_e14_004_001_008_m886">
Oi! If that's really Her Highness, then tell us whyn't His Majesty in the sky stop all this bloodshed!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_004_001_009
{
<NS>Pro-Louis City Girl<NE>
<VOICE "v_e14_004_001_009_m887">
'Cause she's an impostor, just like Count Louis said. You'll not fool us again, beast!
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_004_001_012
{
<NS>Pro-Louis Mason<NE>
<VOICE "v_e14_004_001_012_m888">
Only thing traitors deserve is a tight rope and a stiff beam! And you want us to support the princess!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_004_001_013
{
<NS>Water Merchant<NE>
<VOICE "v_e14_004_001_013_m890">
Lady Junah, I can't believe this! I admired you! Why would you risk dying alongside some fake princess!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e14_004_001_017
{
<NS>Heismay<NE>
<VOICE "v_e14_004_001_017_c004">
What is all this? The truth of the princess hardly matters to them. Every one of them's only concerned with their own emotions and nothing else.
<WAIT>
}