//--------------------------
#SPEAKER_ID "51"
@MES_e14_035_001_002
{
<NS>More<NE>
<VOICE "v_e14_035_001_002_c051">
Afterwards... the powerless princess, her allies, and those who supported her were sought after and purged.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_e14_035_001_004
{
<NS>More<NE>
<VOICE "v_e14_035_001_004_c051">
And the fantasy that the princess believed in? It died as fiction, no truth to stave off its passing.
<WAIT>
}