//--------------------------
#SPEAKER_ID "51"
@MES_e14_026_001_008_00
{
<NS>More<NE>
<VOICE "v_e14_026_001_008_00_c051">
Across three nations, eight tribes, and humankind... To unite heroes across such abyssal divides would require surpassing power... the ruler of all Archetypes...
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_e14_026_001_009
{
<NS>More<NE>
<VOICE "v_e14_026_001_009_c051">
Is that the role you would seize? A true queen in body and soul!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "51"
@MES_e14_026_001_026
{
<NS>More<NE>
<VOICE "v_e14_026_001_026_c051">
Now. Onward, O Queen of a new dawn!
<WAIT>
}