//--------------------------
#SPEAKER_ID "6"
@MES_e14_033_001_015
{
<NS>Eupha<NE>
<VOICE "v_e14_033_001_015_c006">
I hear that many are concerned about her proficiency with statecraft. To be honest, I'm not so sure myself.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e14_033_001_016
{
<NS>Hulkenberg<NE>
<VOICE "v_e14_033_001_016_c003">
Junah will stand as moderator at the podium. Her Majesty will only be asked for a few brief answers.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_033_001_036
{
<NS>Strohl<NE>
<VOICE "v_e14_033_001_036_c002">
Well, let's go. To Her Majesty <HERO_NAME>, the new queen!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e14_033_001_031
{
<NS>Hulkenberg<NE>
<VOICE "v_e14_033_001_031_c003">
Well, 'tis time to make your first appearance as our queen. Let us brace ourselves.
<WAIT>
}