//--------------------------
#SPEAKER_ID "15"
@MES_e14_012_001_000
{
<NS>Louis<NE>
<VOICE "v_e14_012_001_000_c015">
Such a countenance. So you truly are the princess reborn... I must say, you and your father are cut from the same cloth. Quite unpredictable as death looms.
<WAIT>
}
//--------------------------
#SPEAKER_ID "15"
@MES_e14_012_001_022
{
<NS>Louis<NE>
<VOICE "v_e14_012_001_022_c015">
Delusions? You witnessed how the princess lost her very self to my spell, and then re-emerged, with powers and will burning ever brighter.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e14_012_001_023
{
<NS>Hulkenberg<NE>
<VOICE "v_e14_012_001_023_c003">
You mean... you would do to the people exactly what you did to her? You would use the royal magic to inflict such horrors on all the crown's subjects!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e14_012_001_040
{
<NS>Gallica<NE>
<VOICE "v_e14_012_001_040_c011">
Exactly! She's nothing like you!
<WAIT>
}
//--------------------------
#SPEAKER_ID "8"
@MES_e14_012_001_052
{
<NS>Basilio<NE>
<VOICE "v_e14_012_001_052_c008">
...She's got the right of it.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_012_001_002
{
<NS>Strohl<NE>
<VOICE "v_e14_012_001_002_c002">
Only the one who has earned the people's support is fit to be ruler. You and us, we can still end this without more bloodshed.
<WAIT>
}