//--------------------------
#SPEAKER_ID "47"
@MES_e14_002_001_003
{
<NS>Batlin<NE>
<VOICE "v_e14_002_001_003_c047">
I'll call that bet. All in on Her Highness the Princess.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1025_002"
@MES_e14_002_001_004
{
<NS>Loud Peddler<NE>
<VOICE "v_e14_002_001_004_m875">
Ha! A Sanctist bigwig gamblin' away his tithes? This really is the end of the world. Didn't know <i>Her Esteemed Princessliness</i> had any supporters left.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1026_002"
@MES_e14_002_001_005
{
<NS>Engineer Youth<NE>
<VOICE "v_e14_002_001_005_m873">
I mean, she's not really the princess, is she. Was actually a monster in disguise all along. Haven't you heard the news? The times we live in, I tell you.
<WAIT>
}
//--------------------------
#SPEAKER_ID "47"
@MES_e14_002_001_006
{
<NS>Batlin<NE>
<VOICE "v_e14_002_001_006_c047">
*sigh* Must be tough, being an easy mark. Didn't take much for you to buy everything Louis was selling about the princess.
<WAIT>
}