//--------------------------
#SPEAKER_ID "15"
@MES_e14_023_001_003
{
<NS>Louis<NE>
<VOICE "v_e14_023_001_003_c015">
<HERO_NAME>, do you wish to stop me? Or do you wish to be queen? What is it you truly want?
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e14_023_001_004 SEL 0
{
I want to stop you.<COLOR -1>
I want to be queen.<COLOR -1>
It's the same thing.<COLOR -1>
It doesn't matter.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e14_023_001_007
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e14_023_001_007_c001">
I will be queen, no matter what happens.
<WAIT>
}