//--------------------------
#SPEAKER_ID "3"
@MES_e14_016_104m_001
{
<NS>Hulkenberg<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_3036_c003">
...'Tis an oddly nostalgic triumph. Back then, I thought only to protect the home of the princess, that she might someday return. 'Twas my sole desperate intention.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_016_104m_002
{
<NS>Strohl<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
Though in fact, you'd been fighting alongside Her Highness the whole time.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_e14_016_104m_006
{
<NS>Junah<NE>
<BUSTUP 3 0 0>
<VOICE "v_co_5074_c005">
That's right. We'll have <HERO_NAME> get her royal bum on the throne just as soon as we've thrown Louis out on his.
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e14_016_104m_007
{
<NS>Eupha<NE>
<BUSTUP 2 0 0>
<VOICE "v_co_Dpv_PC_Eupha_reply_01_c006">
Just so. There are several favours I would ask of you not just as a friend, but as queen.
<WAIT>
}