//--------------------------
#SPEAKER_ID "3"
@MES_e14_006_002m_001
{
<NS>Hulkenberg<NE>
<VOICE "v_e14_006_002m_001_c003">
Your Majesty, do you hear me? I speak to you as Her Highness the Princess's royal guard, Hulkenberg, knight in your service.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e14_006_002m_002
{
<NS>Hulkenberg<NE>
<VOICE "v_e14_006_002m_002_c003">
Her Highness the Princess, your heiress apparent, has just arrived. Will Your Majesty break the spell and allow Her Highness to succeed the throne?
<WAIT>
}