//--------------------------
#SPEAKER_ID "M1023_106"
@MES_e14_007_001_000
{
<NS>King's Subject<NE>
<VOICE "v_e14_007_001_000_m917">
...Your Majesty, I must speak plain. Since the disappearance of Her Highness the Princess, you have left the land's governance to Sanctifex Forden.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1023_106"
@MES_e14_007_001_002
{
<NS>King's Subject<NE>
<VOICE "v_e14_007_001_002_m917">
I understand the weight of your grief. To lose not only your love, and now Her Highness...
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e14_007_001_011
{
<NS>Hulkenberg<NE>
<VOICE "v_e14_007_001_011_c003">
Perhaps... 'twas a memory from your life as a princess, restored to you?
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_007_001_012
{
<NS>Strohl<NE>
<VOICE "v_e14_007_001_012_c002">
No, this attendant mentioned the loss of Her Highness, right? So she must have been gone already. It can't have been something she experienced.
<WAIT>
}
//--------------------------
#SPEAKER_ID "6"
@MES_e14_007_001_014
{
<NS>Eupha<NE>
<VOICE "v_e14_007_001_014_c006">
Perhaps it was passed through the magla. And the memories are meant for her alone, as the king's child.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_e14_007_001_015
{
<NS>Heismay<NE>
<VOICE "v_e14_007_001_015_c004">
If all this is true... then it goes to show His Majesty was a parent like any other. He thought he'd lost his daughter, and that grief became his undoing...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e14_007_001_020
{
<NS>Strohl<NE>
<VOICE "v_e14_007_001_020_c002">
Right, a queen certainly does her kingdom a disservice by refusing to rule it. But Louis actively defiles it, and that's clearly the greater offense.
<WAIT>
}