//--------------------------
#SPEAKER_ID "47"
@MES_e14_028_001_002
{
<NS>Batlin<NE>
<VOICE "v_e14_028_001_002_c047">
Look! She's done it, she's finally beaten Louis!
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e14_028_001_003
{
<NS>Fabienne<NE>
<VOICE "v_e14_028_001_003_c067">
Does this mean she's won?
<WAIT>
}
//--------------------------
#SPEAKER_ID "40"
@MES_e14_028_001_004
{
<NS>Maria<NE>
<VOICE "v_e14_028_001_004_c040">
She did it?
<WAIT>
}