//--------------------------
#SPEAKER_ID "M1026_915"
@MES_e15_001_001_006
{
<NS>Civil Servant<NE>
<VOICE "v_e15_001_001_006_m1020">
Makes sense to me. After the clash between Her Majesty and Louis last year, everyone knows you don't really need an igniter to use magic.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1722_908"
@MES_e15_001_001_012
{
<NS>Crier<NE>
<VOICE "v_e15_001_001_012_m1019">
Credit where it's due, I think it's thanks to Her young Majesty...
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1722_908"
@MES_e15_001_001_015
{
<NS>Crier<NE>
<VOICE "v_e15_001_001_015_m1019">
It really is a tragedy, what happened to her father the king... but considering how his daughter's turned out, I hope he's at peace.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1722_908"
@MES_e15_001_001_017
{
<NS>Crier<NE>
<VOICE "v_e15_001_001_017_m1019">
Speaking of Her Majesty... I've also heard some folks saying they've seen a girl wandering round these parts who looks just like her. You don't suppose...?
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1026_915"
@MES_e15_001_001_018
{
<NS>Civil Servant<NE>
<VOICE "v_e15_001_001_018_m1020">
Bah, can't be. Without her escorts? Besides, what business would a queen have in this place? Haha...
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1722_908"
@MES_e15_001_001_004
{
<NS>Crier<NE>
<VOICE "v_e15_001_001_004_m1019">
Well, she <i>is</i> one of the Queen Six Partisans. If she managed to help save the world from Louis, I expect she knows a thing or two about magic.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1722_908"
@MES_e15_001_001_013
{
<NS>Crier<NE>
<VOICE "v_e15_001_001_013_m1019">
Remember last year's coronation? Unprecedented, that. Saw heroes of all different tribes celebrating the queen victory—celebrating among the commonfolk, even.
<WAIT>
}