//--------------------------
#SPEAKER_ID "3"
@MES_e15_002_001_013
{
<NS>Hulkenberg<NE>
When did she—I've said countless times
not to leave unannounced!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e15_002_001_016
{
<NS>Hulkenberg<NE>
Apologies, Strohl. I'll look for her now...
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e15_002_001_018
{
<NS>Strohl<NE>
I'd say life has changed plenty for us. Yet somehow our captain's same as she ever was.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e15_002_001_012_01
{
<NS>Gallica<NE>
Hey, isn't the queen supposed to be here!?
<WAIT>
}