//--------------------------
#SPEAKER_ID "M1526_022"
@MES_e15_003_001_007
{
<NS>Drunk Man<NE>
<VOICE "v_e15_003_001_007_m1024">
You know what, lass? You're all right! You ever need some good honest work, I'll get you squared, eh?
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e15_003_001_026
{
<NS>Fabienne<NE>
<VOICE "v_e15_003_001_026_c067">
Not dressed like that you won't. You know how she likes snooping around. Inconspicuously.
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e15_003_001_028
{
<NS>Fabienne<NE>
<VOICE "v_e15_003_001_028_c067">
She'll be fine. Her Majesty's not about to fall prey to some alleyway scoundrel, surely.
<WAIT>
}
//--------------------------
#SPEAKER_ID "67"
@MES_e15_003_001_009
{
<NS>Fabienne<NE>
<VOICE "v_e15_003_001_009_c067">
If you told them you're the queen, it'd knock them sideways.
<WAIT>
}