//--------------------------
#SPEAKER_ID "13"
@MES_e15_005_001_007
{
<NS>Neuras<NE>
<VOICE "v_e15_005_001_007_c013">
You're a queen now, lass. You've got the people's expectations on your shoulders. It's all right to just sit on your throne and mind the home front, you know?
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e15_005_001_013
{
<NS>Neuras<NE>
<VOICE "v_e15_005_001_013_c013">
Hahaha! Ever the fearless gadabout, eh? Well, I take your point, lass.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e15_005_001_026
{
<NS>Strohl<NE>
<VOICE "v_e15_005_001_026_c002">
Lady, you've really got to stop chasing these ideas all on your own. You'll be the death of us.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e15_005_001_027
{
<NS>Hulkenberg<NE>
<VOICE "v_e15_005_001_027_c003">
Once again, lady, I've asked you countless times to give word if you're to leave the castle! Such caprice...
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e15_005_001_005
{
<NS>Gallica<NE>
<VOICE "v_e15_005_001_005_c011">
You want to know what's going on in the world, huh? Well, I guess you ARE the queen.
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_e15_005_001_008 SEL 0
{
I don't care to be queen.<COLOR -1>
I just want to do what I can.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e15_005_001_009
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e15_005_001_009_c001">
I don't care to be queen. That's less important than doing what I need to do.
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e15_005_001_011
{
<NS>Protagonist (Normal)<NE>
<VOICE "v_e15_005_001_011_c001">
I want to do what I can for the people. If that's not queen, then the crown's just slowing me down.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e15_005_001_022
{
<NS>Neuras<NE>
<VOICE "v_e15_005_001_022_c013">
Sounds like a fine idea to me! A proper spot of fun besides! Wouldn't expect any less from our queen and captain.
<WAIT>
}
//--------------------------
#SPEAKER_ID "13"
@MES_e15_005_001_024
{
<NS>Neuras<NE>
<VOICE "v_e15_005_001_024_c013">
And, why, you're the dragonslayer queen! Bane of monsters all across the country! When I imagine what sort of wondrous encounters you've got next, well! I'm all agog!
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e15_005_001_039
{
<NS>Hulkenberg<NE>
<VOICE "v_e15_005_001_039_c003">
Even if decided justly and supported by prosperity, the people may struggle to trust a queen whose face they do not know. An <i>invisible</i> ruler is no cure for their fears.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_e15_005_001_040
{
<NS>Strohl<NE>
<VOICE "v_e15_005_001_040_c002">
Right. I'm not opposed to the idea of getting out into the world again. Really, it might be the wisest move to make sure you're a queen everyone knows.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e15_005_001_045
{
<NS>Hulkenberg<NE>
<VOICE "v_e15_005_001_045_c003">
'Tis natural course for the royal guard to accompany the queen. And I trust my corps is not so feeble that it will fall apart in my absence.
<WAIT>
}