//--------------------------
#SPEAKER_ID "8"
@MES_e15_004_002_001
{
<NS>Basilio<NE>
<VOICE "v_e15_004_002_001_c008">
Lady Junah, did you really come all this way in a runner? Could've asked Her Majesty to pop over and bring you back with a teleport or two.
<WAIT>
}
//--------------------------
#SPEAKER_ID "M1126_021"
@MES_e15_004_002_012
{
<NS>Onlooker<NE>
<VOICE "v_e15_004_002_012_m1028">
Oh—there she is, over there! See? I told you, that's Her Majesty, innit?
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_e15_004_002_006
{
<NS>Gallica<NE>
<VOICE "v_e15_004_002_006_c011">
I guess it's obvious, but just because you're queen now doesn't make you suddenly all-seeing.
<WAIT>
}
//--------------------------
#SPEAKER_ID "3"
@MES_e15_004_002_015
{
<NS>Hulkenberg<NE>
<VOICE "v_e15_004_002_015_c003">
You dare "hoy" the queen, you swine!?
<WAIT>
}
//--------------------------
#SPEAKER_ID "1"
@MES_e15_004_002_024_00
{
<NS>Protagonist<NE>
<VOICE "v_co_1090_c001">
I resolved to believe in my ideals no matter what may come even back then. Even if the world is slow to change, a queen beliefs can never waver.
<WAIT>
}