//--------------------------
@QuestInfo_048_000
{
Save the princess from her curse and defeat Louis Guiabern, the treasonous fiend who not only attacked the princess, but murdered the king.
<WAIT>
}
//--------------------------
@QuestInfo_048_003
{
Participating in the Tournament for the Throne should lead to increased recognition and thus access to Louis. If I can steal the curse formula from Louis, I may be able to lift the princess's curse!
<WAIT>
}
//--------------------------
@QuestInfo_048_004
{
Apparently the curse formula cannot be used to cure the princess. Now there is no choice but to kill Louis. But for the present, best obey him.
<WAIT>
}
//--------------------------
@QuestInfo_048_006
{
I finally managed to defeat Louis! That should have lifted the princess's curse, and yet...
<WAIT>
}
//--------------------------
@QuestInfo_048_007
{
Rella, who carried out the attack on the princess, is waiting for me. As the one who cast the hex, Rella must die to remove the curse.
<WAIT>
}
//--------------------------
@QuestInfo_048_008
{
In exchange for Rella's life, the princess's curse was finally lifted.
<WAIT>
}
//--------------------------
@QuestInfo_051_000
{
Pass through the tunnel to return to Grand Trad. By assassinating Louis there, the princess will finally rise from her sleep...
<WAIT>
}
//--------------------------
@QuestInfo_055_000
{
The infiltration route must be secured, so Louis's Room can be accessed on the day of the soiree. If I steal the curse formula, the princess's curse can be lifted!
<WAIT>
}
//--------------------------
@QuestInfo_055_002
{
The route to access Louis's Room has been secured. Now all that's left is to sneak in on the day of the soiree and swipe the curse formula. Then the princess's curse can be lifted...
<WAIT>
}
//--------------------------
@QuestInfo_111_002
{
I gave the <COLOR 3><ITEM 20483 2><COLOR -1> to the merchant. I also vowed to become queen and change the country in order to thaw the frozen hearts of the people.
<WAIT>
}