//--------------------------
#SPEAKER_ID "51,549"
@MES_BE_0633_001_000
{
<NS>More<NE>
<BUSTUP 9 0 0>
<VOICE "v_BE_0633_001_000_c051">
Forgive me, my daughter. But I cannot stand by and let you return to a world so devoid of mercy.
<WAIT>
}
//--------------------------
#SPEAKER_ID "51,549"
@MES_BE_0633_011_000
{
<NS>More<NE>
<BUSTUP 9 0 0>
<VOICE "v_BE_0633_011_000_c051">
That world is beyond your help. Beyond any utopia! You must face reality, my daughter!
<WAIT>
}