//--------------------------
#SPEAKER_ID "85,407"
@MES_BE_0704_002_000
{
<NS>Loveless<NE>
<BUSTUP 5 0 0>
<VOICE "v_BE_0704_002_000_c085">
Oh, I know what you're about. Two-faced phony princess! Milo told me everything! I know all about your sick games!
<WAIT>
}
//--------------------------
#SPEAKER_ID "85,407"
@MES_BE_0704_009_000
{
<NS>Loveless<NE>
<BUSTUP 0 0 0>
<VOICE "v_BE_0704_009_000_c085">
Said there's some impostor princess been goin' round, gettin' her kicks by killin' paripus and eugief and other tribes "beneath" her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "11"
@MES_BE_0704_015_000
{
<NS>Gallica<NE>
<BUSTUP 4 0 0>
<VOICE "v_BE_0704_015_000_c011">
I gotta say... I'm kinda surprised you're still around. Didn't really seem like the kinda girl who would survive to the end of the Tournament.
<WAIT>
}
//--------------------------
#SPEAKER_ID "4"
@MES_BE_0704_010_000
{
<NS>Heismay<NE>
<BUSTUP 4 0 0>
<VOICE "v_BE_0704_010_000_c004">
I stand with this girl, as does Basilio, and I can tell you we don't wander around murdering our own kin. Sounds like this Milo fellow's badly bamboozled you.
<WAIT>
}