//--------------------------
#SPEAKER_ID "91"
@MES_q01_100_005_029
{
<NS>Agrica<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
For a fairy to speak with the warmth and plenty of a person as you do is proof that you're an invaluable friend to her.
<WAIT>
}
//--------------------------
#SPEAKER_ID "91"
@MES_q01_100_005_040
{
<NS>Agrica<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_11910022_m1400">
As queen, thou shalt be no stranger to the burden of responsibility. Give it thine all.
<WAIT>
}
//--------------------------
#SPEAKER_ID "68"
@MES_q01_100_005_047
{
<NS>Mysterious Voice<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_68051_c068">
Go, then. To become a true queen... As a traveller, fearlessly chasing the unknown!
<WAIT>
}