//--------------------------
#SPEAKER_ID "50"
@MES_q01_100_001_023_01
{
<NS>Edeni<NE>
<BUSTUP 0 0 0>
<LIPSYNC>
Realistically, you are fighting Louis for the throne. Thus, allow me to pose the question. What qualities are desired in a ruler?
<WAIT>
}
//--------------------------
#SPEAKER_ID "50"
@MES_q01_100_001_023_08
{
<NS>Edeni<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_50020_c050">
As you say, that is precisely why a ruler must have such resolve. A ruler must have faith in the salvation of all, even when people cannot.
<WAIT>
}