//--------------------------
#SPEAKER_ID "4"
@MES_q01_100_004_011
{
<NS>Heismay<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_4081_c004">
"We offer a helping hand to anyone in need." That's what this lass's been saying ever since the day we met.
<WAIT>
}
//--------------------------
#SPEAKER_ID "5"
@MES_q01_100_004_012
{
<NS>Junah<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_5162_c005">
And it's gotten us into trouble, let me tell you... But really, people put their burdens on her because she's the kind of person you can believe in.
<WAIT>
}