//--------------------------
#SPEAKER_ID "0"
@MES_q01_132_002_008
{
<NS>Receptionist<NE>
<BUSTUP 0 0 0>
Awful lot of the coliseum's regulars are rooting for you. Seein' a tiny little girl, winning against those huge monsters...
<WAIT>
}
//--------------------------
#SPEAKER_ID "0"
@MES_q01_132_002_010
{
<NS>Receptionist<NE>
<BUSTUP 0 0 0>
You're gonna beat that bastard Louis and become queen, yeah? Normally I would've assumed that's just impossible, but something tells me you could actually make it happen.
<WAIT>
}