//--------------------------
#SPEAKER_ID "8"
@MES_q15_004_003_016
{
<NS>Basilio<NE>
<BUSTUP 1 0 0>
<VOICE "v_co_8185_c008">
Look at this lass here, she's just a scrawny little elda, I admit. But I believe she's got more power than Louis, truly.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_q15_004_003_018
{
<NS>Strohl<NE>
<BUSTUP 0 0 0>
<VOICE "v_co_2078_c002">
Strength isn't just about raw power. Look at her. Even with things being the way they are now, she's still offering you a helping hand.
<WAIT>
}
//--------------------------
#SPEAKER_ID "2"
@MES_q15_004_003_019
{
<NS>Strohl<NE>
<BUSTUP 1 0 0>
<LIPSYNC>
She really wants to create a world where no one has to shed tears over injustice. I reckon there's more hope in that ideal than in the world Louis is trying to make.
<WAIT>
}